-- Disposable PostgreSQL fixture; never apply to an application database.
CREATE TABLE social_event (id BIGSERIAL PRIMARY KEY,organizer_party_id VARCHAR NULL,title VARCHAR NOT NULL,description VARCHAR NULL,venue_id INTEGER NULL,event_type_id VARCHAR NULL,workflow_state_id VARCHAR NULL,timezone VARCHAR NULL,start_time TIMESTAMPTZ NOT NULL,end_time TIMESTAMPTZ NULL,price_cents INTEGER NULL,currency_id VARCHAR NULL,capacity INTEGER NULL,metadata VARCHAR NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE event_ticket_tier (id BIGSERIAL PRIMARY KEY,event_id INTEGER NOT NULL,code VARCHAR NOT NULL,name VARCHAR NOT NULL,description VARCHAR NULL,price_cents INTEGER NOT NULL,currency VARCHAR NOT NULL,currency_id VARCHAR NULL,quantity_total INTEGER NOT NULL,quantity_sold INTEGER NOT NULL,sales_start TIMESTAMPTZ NULL,sales_end TIMESTAMPTZ NULL,is_active BOOLEAN NOT NULL,position INTEGER NULL,enable_waitlist BOOLEAN NOT NULL DEFAULT FALSE,allow_transfers BOOLEAN NOT NULL DEFAULT FALSE,refund_policy VARCHAR NOT NULL DEFAULT 'none',refund_deadline TIMESTAMPTZ NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE event_ticket_order (id BIGSERIAL PRIMARY KEY,event_id INTEGER NOT NULL,tier_id INTEGER NOT NULL,buyer_party_id VARCHAR NULL,buyer_name VARCHAR NULL,buyer_email VARCHAR NULL,quantity INTEGER NOT NULL,amount_cents INTEGER NOT NULL,currency VARCHAR NOT NULL,status VARCHAR NOT NULL,metadata VARCHAR NULL,checkout_idempotency_key VARCHAR NULL,purchased_at TIMESTAMPTZ NOT NULL,stripe_payment_intent_id VARCHAR NULL,promo_code_id INTEGER NULL,original_amount_cents INTEGER NULL,payment_method VARCHAR NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE event_ticket (id BIGSERIAL PRIMARY KEY,event_id INTEGER NOT NULL,tier_ref_id INTEGER NOT NULL,order_ref_id INTEGER NOT NULL,holder_name VARCHAR NULL,holder_email VARCHAR NULL,code VARCHAR NOT NULL UNIQUE,status VARCHAR NOT NULL,checked_in_at TIMESTAMPTZ NULL,current_holder_party_id VARCHAR NULL,current_holder_email VARCHAR NULL,current_holder_name VARCHAR NULL,original_holder_party_id VARCHAR NULL,transfer_history VARCHAR NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE ticket_transfer (id BIGSERIAL PRIMARY KEY,ticket_id BIGINT NOT NULL REFERENCES event_ticket(id),from_party_id VARCHAR NULL,to_party_id VARCHAR NULL,to_email VARCHAR NULL,to_name VARCHAR NULL,status VARCHAR NOT NULL DEFAULT 'pending',transfer_code VARCHAR NOT NULL UNIQUE,message VARCHAR NULL,expires_at TIMESTAMPTZ NULL,accepted_at TIMESTAMPTZ NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE event_ticket_checkout_policy (id UUID PRIMARY KEY,event_id BIGINT NOT NULL,approval_status TEXT NOT NULL DEFAULT 'draft',transfer_allowed BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE event_ticket_checkout_runtime (order_id BIGINT PRIMARY KEY,policy_id UUID NOT NULL REFERENCES event_ticket_checkout_policy(id),event_id BIGINT NOT NULL,payment_status TEXT NOT NULL);

ALTER TABLE event_ticket_checkout_runtime ADD COLUMN checkout_id UUID;
CREATE TABLE commerce_payment_attempt (id UUID PRIMARY KEY,checkout_id UUID NOT NULL);
CREATE TABLE commerce_provider_binding (payment_attempt_id UUID NOT NULL,provider TEXT NOT NULL,environment TEXT NOT NULL,merchant_account_ref TEXT NOT NULL,provider_resource_id TEXT NOT NULL,resource_type TEXT NOT NULL);
CREATE TABLE commerce_reconciliation_exception (provider TEXT NOT NULL,environment TEXT NOT NULL,merchant_account_ref TEXT NOT NULL,provider_reference TEXT NOT NULL,internal_reference TEXT NOT NULL,exception_type TEXT NOT NULL,status TEXT NOT NULL);
