\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout='2s';
DO $guard$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='tdf_catalog_inventory' AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolinherit AND NOT rolreplication AND NOT rolbypassrls) OR has_schema_privilege('tdf_catalog_inventory','public','CREATE') THEN RAISE EXCEPTION 'Unexpected catalog-reader privileges'; END IF;
 IF (SELECT array_agg(c.relname::text ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND NOT has_table_privilege('tdf_catalog_inventory',c.oid,'SELECT')) IS DISTINCT FROM ARRAY['event_discovery_publication_approval','interaction_audit','interaction_comment','interaction_comment_attachment','interaction_comment_mention','interaction_comment_total','interaction_entity_kind','interaction_event','interaction_legacy_cutover','interaction_legacy_mapping','interaction_migration_state','interaction_notification','interaction_notification_actor','interaction_notification_preference','interaction_reaction','interaction_reaction_choice','interaction_reaction_total','interaction_report','interaction_request','interaction_runtime','interaction_subscription','interaction_target','interaction_target_comment_total','interaction_target_mention','social_v2_command','social_v2_pair','social_v2_preference','social_v2_publication','social_v2_runtime']::text[] THEN RAISE EXCEPTION 'Concurrent schema or grants changed'; END IF;
END $guard$;
GRANT SELECT ON TABLE public."event_discovery_publication_approval",public."interaction_audit",public."interaction_comment",public."interaction_comment_attachment",public."interaction_comment_mention",public."interaction_comment_total",public."interaction_entity_kind",public."interaction_event",public."interaction_legacy_cutover",public."interaction_legacy_mapping",public."interaction_migration_state",public."interaction_notification",public."interaction_notification_actor",public."interaction_notification_preference",public."interaction_reaction",public."interaction_reaction_choice",public."interaction_reaction_total",public."interaction_report",public."interaction_request",public."interaction_runtime",public."interaction_subscription",public."interaction_target",public."interaction_target_comment_total",public."interaction_target_mention",public."social_v2_command",public."social_v2_pair",public."social_v2_preference",public."social_v2_publication",public."social_v2_runtime" TO tdf_catalog_inventory;
DO $guard$ BEGIN
 IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND (NOT has_table_privilege('tdf_catalog_inventory',c.oid,'SELECT') OR has_table_privilege('tdf_catalog_inventory',c.oid,'INSERT,UPDATE,DELETE,TRUNCATE,TRIGGER,REFERENCES'))) THEN RAISE EXCEPTION 'Reader coverage or privilege validation failed'; END IF;
END $guard$;
COMMIT;
SELECT json_build_object('readableTables', count(*) FILTER (WHERE has_table_privilege('tdf_catalog_inventory',c.oid,'SELECT')), 'writableTables', count(*) FILTER (WHERE has_table_privilege('tdf_catalog_inventory',c.oid,'INSERT,UPDATE,DELETE,TRUNCATE')), 'schemaCreate',has_schema_privilege('tdf_catalog_inventory','public','CREATE')) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p');
