import collect,subprocess,json,datetime,time
P=collect.ROOT;repo=collect.REPO;cwd=P/'cutover';old='4031ed4a2c8f6c84df5e2a03b920f2643c16bd18';branch='codex/hetzner-cutover-evidence-20260928'
def api(path,*args):return json.loads(subprocess.check_output(['/usr/local/bin/gh','api',path,*args],env=collect.ENV,text=True))
def gql(q):return api('graphql','-f','query='+q)['data']
def ledger(**kw):
 with open(P/'mutations.jsonl','a') as f:f.write(json.dumps({'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),**kw})+'\n')
assert 'ℹ pass 122' in (P/'cutover-managed-image-tests.log').read_text() and 'ℹ fail 0' in (P/'cutover-managed-image-tests.log').read_text()
subprocess.run(['python3','scripts/specification-inventory.py','--check'],cwd=cwd,check=True)
sha=subprocess.check_output(['git','rev-parse','HEAD'],cwd=cwd,text=True).strip();subprocess.run(['git','merge-base','--is-ancestor',old,sha],cwd=cwd,check=True)
assert not subprocess.check_output(['git','status','--porcelain'],cwd=cwd,text=True).strip()
x=api(repo+'/pulls/468');assert x['state']=='open' and x['head']['sha']==old and x['base']['ref']=='main'
assert api(repo+'/git/ref/heads/'+branch)['object']['sha']==old
(P/'cutover-access-before.json').write_text(json.dumps(x,indent=2))
subprocess.run(['git','push','origin','HEAD:refs/heads/'+branch],cwd=cwd,env=collect.ENV,check=True)
assert api(repo+'/git/ref/heads/'+branch)['object']['sha']==sha
for _ in range(10):
 x=api(repo+'/pulls/468')
 if x['head']['sha']==sha:break
 time.sleep(2)
assert x['head']['sha']==sha;(P/'cutover-access-after.json').write_text(json.dumps(x,indent=2));ledger(action='pushed_verified_current_access_fix',pr=468,old_sha=old,sha=sha,url=x['html_url'],validation='6 production-access, 6 mail, 3 catalog tests; inventory and 3 Python/9 Node evidence gates pass. Live read-only catalog and installed scheduled mailbox command pass. No remote production writes.')
def state():
 x=gql('query{repository(owner:"diegueins680",name:"tdf-app"){pullRequest(number:468){state headRefOid baseRefName reviewThreads(first:100){nodes{id isResolved comments(first:100){nodes{id body url}}} pageInfo{hasNextPage}}}}}')['repository']['pullRequest'];assert x['state']=='OPEN' and x['headRefOid']==sha and x['baseRefName']=='main' and not x['reviewThreads']['pageInfo']['hasNextPage'];return x
for tid,msg in [
 ('PRRT_kwDOQPdUrM6myV4V','Replaced retired Fly discovery/SQL transport with the existing dedicated Hetzner SSH connection, verified from the deployment record and live host. Require strict SSH host identity, running production project/service/directory, API-to-database network/name binding and configured immutable image. Compare public health/commit with the inspected API and deployment identity before/after the unchanged bounded anonymized SQL. PostgreSQL starts read-only; original transaction/timeouts/exclusions remain. Live verified inventory succeeded: 766 records, 623 tables, database tdf_hq, read-only on, API commit cc244b1f86603055997b51379b297baebfd3e7ce. Private data/credential values are not in the audit report.'),
 ('PRRT_kwDOQPdUrM6myV4a','Moved credential retrieval to the existing protected Hetzner api.env, requiring mode-0600 protection, the verified production container/image/database identity, and agreement with runtime SMTP configuration. Only the two needed keys cross SSH into process memory; stderr/exception values are redacted. Read-only IMAP, BODY.PEEK, size limits, aggregate-only reports and failure behavior remain. Rechecked and atomically updated the installed monitor/helper with verified hashes; the existing LaunchAgent was unchanged and its exact scheduled command passed live with mailboxReadSucceeded=true, eight aggregate reports and zero errors. No email was sent.')
]:
 before=state();t=next(t for t in before['reviewThreads']['nodes'] if t['id']==tid);assert not t['isResolved'] and len(t['comments']['nodes'])==1
 (P/(tid+'-before.json')).write_text(json.dumps(before,indent=2));body=f'Fixed in {sha}. '+msg+' Six access regressions, six mail regressions, three catalog regressions and the current specification/evidence gates pass. Tests reject stale/incorrect bindings, changed deployments, unsafe credential permissions and secret-output failures.'
 r=gql('mutation{addPullRequestReviewThreadReply(input:{pullRequestReviewThreadId:'+json.dumps(tid)+',body:'+json.dumps(body)+'}){comment{id body url}}}')['addPullRequestReviewThreadReply']['comment'];assert r['body']==body;ledger(action='replied_to_review',pr=468,sha=sha,thread=tid,url=r['url'])
 current=state();t=next(t for t in current['reviewThreads']['nodes'] if t['id']==tid);assert not t['isResolved'] and len(t['comments']['nodes'])==2 and t['comments']['nodes'][-1]['id']==r['id']
 assert gql('mutation{resolveReviewThread(input:{threadId:'+json.dumps(tid)+'}){thread{id isResolved}}}')['resolveReviewThread']['thread']['isResolved']
 current=state();assert next(t for t in current['reviewThreads']['nodes'] if t['id']==tid)['isResolved'];(P/(tid+'-after.json')).write_text(json.dumps(current,indent=2));ledger(action='resolved_verified_review',pr=468,sha=sha,thread=tid,url=r['url']);print('Verified resolved',tid,flush=True)
x=api(repo+'/pulls/468');assert x['state']=='open' and x['head']['sha']==sha
body='The web-first cutover left scheduled/manual tools and repair instructions pointing at the retired Fly backend. Retarget enrichment, bundled artist import, course publishing and payment/social callback guidance to the canonical API. Recognize canonical API assets as managed without admitting lookalike hosts. Retire the old deployment guide as a production procedure, link the current guarded runbook and correct both frontend API examples. Make messaging monitoring read-only while retaining invalid/expiry failure notifications, support credential aliases without printing values, and make readiness diagnostics report observed results rather than unperformed payment tests.\n\nPreserve the recorded restore, callback migration, backups, retained Trader/shared Fly resources and YouTube activation evidence. Cutover validation remains incomplete: actual Google login and authenticated upload gates are still unperformed. Production catalog inventory and the installed mail monitor now use the existing verified Hetzner connection. The catalog retains bounded anonymized read-only SQL and checks public/deployment identity; mail credentials stay in memory and the installed monitor was verified with read-only IMAP. Automatic Hetzner credential rotation remains pending. No infrastructure credentials, provider callbacks, payments or deployment were changed by these repairs.\n\nValidation: final helper/token/enrichment/import suite passes 122 tests; CI/evidence/escrow tests pass 34 cases; specification regressions pass three cases. Course and callback commands are tested with mocked requests; shell syntax and regenerated specification hashes pass. The managed-host regression accepts canonical/legacy hosts and rejects lookalikes. Six access, six mail and three catalog regressions pass, including stale identity and secret-output controls. Live catalog inventory and the installed scheduled mailbox command pass with no production mutation or mail sent. The source commits and detailed results are recorded in the audit report. Fifteen concrete review findings are fixed; current-head hosted checks and independent review are required. Datadog still needs its external retired endpoint corrected without weakening assertions.\n'
api(repo+'/pulls/468','--method','PATCH','-f','body='+body)
y=api(repo+'/pulls/468');assert y['head']['sha']==sha and y['body']==body;(P/'cutover-access-description-after.json').write_text(json.dumps(y,indent=2));ledger(action='updated_validation_description',pr=468,sha=sha,url=y['html_url'])
print('Verified operator follow-up',sha)
