import collect,subprocess,json,datetime
P=collect.ROOT;W=P/'events-editorial-repair-20261003'
def api(path,*args):return json.loads(subprocess.check_output(['/usr/local/bin/gh','api',path,*args],env=collect.ENV,text=True))
pr=api(collect.REPO+'/pulls/465');head=json.loads((P/'completion-poll-push-verified.json').read_text())['head']['sha'];assert pr['head']['sha']==head and pr['state']=='open'
body=pr['body']+'\n\n### Task-completion expiry polling correction\n\nCurrent head `'+head+'` preserves the lifecycle fixes in34ca75d. The hosted PostgreSQL task-completion job failed with exit1 and no assertion diagnostic. Inspection found a15-second expiry window bounded by100 polls sleeping0.1seconds: on a fast runner that can time out before expiry. This follow-up allows200 polls and adds a precise timeout diagnostic, retaining every before-expiry, exact-blocker, after-expiry, denial, revision, history and rollback assertion.\n\nThe complete unchanged-source baseline passed locally because query overhead extends the window; this is not claimed as a reproduced CI failure. The corrected complete native PostgreSQL16 suite also passed:32 decision cases,12 RC/RR/Serializable races, four observed expiry waits, revocation ordering, rollback/reapply and aborted-first recovery. Shell syntax, whitespace, three specification-inventory tests and the generated inventory check pass. Fresh current-head hosted checks and independent approval remain required.\n'
(P/'completion-poll-pr-body.md').write_text(body)
updated=api(collect.REPO+'/pulls/465','--method','PATCH','-f','body='+body)
after=api(collect.REPO+'/pulls/465');assert after['body']==body and after['head']['sha']==head
(P/'completion-poll-body-verified.json').write_text(json.dumps(after,indent=2))
with (P/'mutations.jsonl').open('a') as f:f.write(json.dumps({'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'action':'updated_pull_request_body','pr':465,'sha':head,'url':after['html_url'],'evidence':'completion-poll-body-verified.json'})+'\n')
evidence={'head':head,'local_full_postgres_suite':'PASS','baseline_local_full_suite':'PASS; CI failure not reproduced on this slower client','assertions_retained':True,'polling_minimum_budget_seconds_before':10,'polling_minimum_budget_seconds_after':20,'fixture_expiry_seconds':15,'syntax':'PASS','inventory_check':'PASS','inventory_tests':3,'initial_incorrect_npm_script':'Missing script: specification:inventory:check; subsequently ran prescribed Python check successfully','hosted_result':'pending current head','review':'pending current head'}
(P/'completion-poll-validation.json').write_text(json.dumps(evidence,indent=2))
p=P/'events-lifecycle-validation.json';d=json.loads(p.read_text());d['prior_catalog_failure']='One changed DatabaseFailure fingerprint explicitly reviewed; previous decision retained. Final strict1171 gate passed.';p.write_text(json.dumps(d,indent=2))
(P/'browser-capability-recheck-20261004.txt').write_text('2026-10-04T00:39Z browser_tabs action=list: profile tdf-instagram remains in use by another session. No process/profile changed; actual Google login/upload remains unverified.\n')
print(head,'body and evidence verified')
