from pathlib import Path
p=Path(__file__).parent
f=p/'write_overview.py';s=f.read_text()
s=s.replace('published seven tested repair/consolidation PRs','published eight tested repair/consolidation PRs')
s=s.replace('Every remote branch was retained.','Every root-repository branch was retained. The companion mobile branch was deleted by its repository\'s normal automation after a concurrent merge; this is not an audit deletion.')
s=s.replace('Git/gh, Node/npm, Stack3.7.1/GHC9.10.3, PostgreSQL16, Docker and audit-local Java/TLA+/Alloy tooling were available.','Git/gh, Node/npm, Stack3.7.1/GHC9.10.3, PostgreSQL16, Docker and audit-local Java/TLA+/Alloy tooling were initially available. Java and the local model-checker JAR files were missing at the October4 continuation; current bounded model checks run in prescribed hosted CI, and no local rerun is claimed.')
s=s.replace('the separate local107 HTTP cases passed','the separate local110 HTTP cases passed')
s=s.replace('+ 4 audit PRs (465,469,472,475)', '+ 5 audit PRs (465,469,472,475,476)')
s=s.replace('134 + 7 concurrent branches + 4 audit branches = 145','134 + 7 concurrent branches + 5 audit branches = 146')
s=s.replace('| 7 — root463,465,468,469,472,475 and mobile115;', '| 8 — root463,465,468,469,472,475,476 and mobile115;')
s=s.replace('| 5 / 0 — four root PRs plus mobile115 |','| 6 / 0 — five root PRs plus mobile115 |')
s=s.replace('Closed PR441 retains unique delivery/recovery notes.','Closed PR441\'s unique delivery/recovery notes have been preserved with source attribution in documentation-rescue PR476, pending review and integration.')
s=s.replace('It remains unmerged pending independent review, which Diego is arranging. Root465 already pins ede1f2a and has reconciled current-main contracts; mobile integration and fresh root review/checks remain required.','Another actor subsequently merged the independently reviewed exact ede1f2a head atbca7f39cebcae24b62a4404bf5fd76bb9328f95a. Both normal post-merge workflows passed and ede1f2a is an ancestor of mobile main. The companion repository auto-deleted its source branch. These are observed concurrent actions, not audit mutations. Root465 pins the integrated ede1f2a; fresh root review/checks remain required.')
s=s.replace('Current-head hosted CI and independent approval remain mandatory; mobile115 integration is still a dependency.','The08acdfa hosted backend passed3587 examples/zero failures and107 HTTP examples; all applicable checks and exact-head approval passed. A fresh pre-merge guard stopped before mutation on two new review findings. Mobile115 integration is now verified.')
s=s.replace('The [append-only mutation ledger]', '''16. Fixed both legitimate lifecycle findings at34ca75d: retain the enabled feature-flag share lock through the transition transaction, and decode/bind lifecycle receipts inside SqlPersistT so malformed responses roll back all writes. Two pure decoder cases and one authenticated HTTP regression cover eight corrupt response forms. The complete native HTTP suite passed110 examples; the SQL negative control reproduced the old feature-flag race and all six fixed lock-order/isolation cases passed. Both review threads were replied to and resolved only after verified push and test evidence. All160 registered production SQL files remain byte-identical and the event adapter remains unregistered/disabled.
17. Hosted34ca task-completion CI failed with an opaque exit1. Inspection found the15-second expiry fixture had only100 polling intervals of0.1seconds on fast runners. Normal commit154f968aa permits200 polls and adds a timeout diagnostic without changing any security assertion. Both baseline and corrected full native PostgreSQL suites passed locally; this is explicitly not a reproduced hosted failure. Three inventory tests, generated inventory check, shell syntax and whitespace checks passed. Fresh current-head CI and review are required.
18. Rescued PR441\'s remaining unique historical notification delivery/recovery notes in standalone PR476 at6d00fa1463603bacecbb3210279b09ed88bbba0c, retaining exact source text and attribution with explicit September18 scope. No mobile pin changes or new device qualification claims. The original pin is an ancestor of the integrated mobile companion. Corrected the generated documentation hash in a normal follow-up commit and verified the inventory check. Source441 and both root branches remain. Current-head checks pass; independent review remains required.
19. After every normal mainf8925 workflow/check passed, closed source464 with exact-head ancestry, merged successor and recovery-SHA evidence. Both branches remain. No event source PR was closed.

The [append-only mutation ledger]''')
s=s.replace('No remote branch deletion occurred, so deletion recovery commands are N/A;', 'No audit branch deletion occurred, so audit deletion recovery commands are N/A; the concurrent mobile source branch can be recovered in the mobile repository with `git push origin ede1f2a0ccf75f3794c7892f291e1751b279d19e:refs/heads/audit/event-operations-client-20260928` after fresh safety checks;')
s=s.replace('[463,464,465,468,469,470,471,472,473,474,475]', '[463,464,465,468,469,470,471,472,473,474,475,476]')
s=s.replace('PR465 now at08acdfa after normal incorporation of mainf8925/PR475, with fresh review/checks required; mobile115 has passing checks and no independent review.', 'PR465 now at154f968aa after lifecycle review fixes and expiry-test correction, with fresh review/checks required; mobile115 is concurrently merged and both post-merge workflows passed.')
start=s.index('- **Mobile115 / root465 / 35 event originals:**');end=s.index('\n- **PR468:**',start)
s=s[:start]+'- **Root465 / 35 event originals:** mobile115 is integrated with passing post-merge checks. Root465 contains mainf8925, the integrated ede1f2a companion and lifecycle safety fixes34ca75d. Current154f968aa corrects the completion-test polling budget; require passing hosted checks and fresh independent approval. Only after replacement merge and passing target CI should source closures be reconsidered.'+s[end:]
s=s.replace('- **Closed PR441:** unique delivery/recovery notes need an explicit documentation destination before redundancy can be concluded.','- **PR476 / closed441:** the unique historical delivery/recovery notes are rescued in the existing notification document, with exact source attribution and no gitlink change. Current checks pass; complete independent review, then merge and verify the resulting document before classifying source441 as fully integrated.')
s=s.replace('Normal post-merge CI and any verified source464 closure are linked from the branch matrix and mutation ledger;', 'All normal mainf8925 checks/workflows passed and source464 closure is verified in the branch matrix and mutation ledger;')
f.write_text(s)
f=p/'render_report.py';s=f.read_text();pos=s.index("('PR475 at4100a04c'")
s=s[:pos]+"('PR465 at154f968aa','complete native PostgreSQL task-completion regression','PASS —32 decision cases,12 isolation races,four expiry waits,revocation orders and rollback/reapply; baseline also passes on this slower client, not a reproduced hosted failure','task-completion-native-fixed.log'),\n('PR465 at34ca75d','hosted task-completion job','FAILED — opaque exit1;15-second expiry fixture had100x0.1second polling budget; corrected at154f968aa without removing assertions, fresh hosted CI remains authoritative','events-lifecycle-completion-failure.log'),\n"+s[pos:];f.write_text(s)
print('Updated report generators with verified continuation and explicit pending gates')
