import collect,json,subprocess,datetime
P=collect.ROOT;head='ce1a71fe241ccc05b6114088fb36dd919974dc87'
def api(path,*args):return json.loads(subprocess.check_output(['/usr/local/bin/gh','api',collect.REPO+path,*args],env=collect.ENV,text=True))
p=api('/pulls/468');assert p['state']=='open' and p['head']['sha']==head
body=p['body']+'\n\n### Provenance review follow-up `ce1a71fe2`\n\nPreserves concurrent762e1ff changes. Catalog inventory now makes fresh DNS/TLS/peer-bound public health/version requests after SQL and revalidates the result against the inspected deployment. The shared helper verifies digest-pinned POSTGRES_IMAGE against the running database reference or registry digest in every access mode, and inventory binds that configured reference across the query.\n\nValidation:11 access,6 catalog,6 mail tests; strict1162-candidate catalog gate; generated inventory and whitespace checks. Old database validation fails15 new rejection cases; a no-post-query-recheck negative control fails the new orchestration regression. Both addressed review threads are verified resolved.\n\nCurrent live verification is blocked: the existing authorized SSH connection timed out on repeated read-only attempts. Public DNS still resolves to the expected server and HTTPS health returns200/databaseOK, which does not substitute for authenticated container/image verification. No production metadata or inventory success is claimed for this follow-up; no installed monitor update, production write, restart or manual deployment was performed. The separate actual Google login/authenticated upload gate remains open. Fresh current-head CI and independent approval are required.\n'
api('/pulls/468','--method','PATCH','-f','body='+body);after=api('/pulls/468');assert after['body']==body and after['head']['sha']==head
(P/'cutover-provenance-body-verified.json').write_text(json.dumps(after,indent=2))
with (P/'mutations.jsonl').open('a') as f:f.write(json.dumps({'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'action':'updated_pull_request_body','pr':468,'sha':head,'url':after['html_url'],'evidence':'cutover-provenance-body-verified.json'})+'\n')
print('Verified current body')
