import json,pathlib,collections,datetime
P=pathlib.Path(__file__).parent;R=P/'report'
F=sorted(p for p in P.glob('final-*') if p.is_dir() and (p/'completed.txt').exists())[-1]
rec=json.load(open(R/'reconciliation.json'));initial=json.load(open(R/'branches.json'));added=json.load(open(R/'added-branches.json'))
mut=[json.loads(x) for x in (P/'mutations.jsonl').read_text().splitlines()]
counts=collections.Counter(r['classification'] for r in initial);allcounts=counts+collections.Counter(r['classification'] for r in added)
mobile=json.load(open(F/'mobile-pr115.json'))
audit_closures=len({m['pr'] for m in mut if m.get('action')=='closed_unmerged'})
audit_merges=len({m['pr'] for m in mut if m.get('action') in ('merged_pull_request','observed_automatic_merge')}|{460})
def checks(n):
 p=json.load(open(F/f'prs/{n}/info.json'));path=F/f'checks/{p["head"]["sha"]}.json'
 if not path.exists():path=next((q for q in sorted(P.glob(f'final-*/checks/{p["head"]["sha"]}.json'),reverse=True) if q.exists()),path)
 cs=[c for pg in json.load(open(path)) for c in pg['check_runs']] if path.exists() else []
 ts=json.load(open(F/f'prs/{n}/threads.json'));v=ts[0]['data']['repository']['pullRequest']
 return p,dict(collections.Counter(c['conclusion'] or c['status'] for c in cs)),v['reviewDecision'],sum(not t['isResolved'] for pg in ts for t in pg['data']['repository']['pullRequest']['reviewThreads']['nodes'])
text=f'''# Remote branch audit — 2026-09-28 through 2026-10-03

**All 134 initially inventoried branches are accounted for.** This audit normally merged [PR469](https://github.com/diegueins680/tdf-app/pull/469) at `de76dc7df247937144e1802c17d1842f983cbe13` and [security follow-up PR472](https://github.com/diegueins680/tdf-app/pull/472) at `76c2c05c536586fd814f7a68d2052f0fd9d900ed`, normally merged [documentation rescue PR476](https://github.com/diegueins680/tdf-app/pull/476) at `c4d479c7f3da659368e5bc60464a1a43c99d9b7a`, published eight tested repair/consolidation PRs, including approved PR475 at4100a04c, now normally merged at `f8925e339447cb593f7cce5d86403d1396aaf5a5` with the exact tested tree, and closed {audit_closures} proven integrated PRs. This audit deleted no root-repository branch. Another session deleted73 refs; the user explicitly instructed keeping those deletions and retaining recovery evidence. All73 recorded heads are preserved in a verified Git bundle and remain ancestors of current main. The companion mobile branch was deleted by its repository's normal automation after a concurrent merge; this is not an audit deletion. The overall objective remains **partially blocked**, with precise remaining gates below; this report does not claim all work is merged.

## Complete evidence and matrices

- [Every initial branch](branch-matrix.md), [CSV](branches.csv), [detailed JSON](branches.json): 134 rows, one primary classification each, immutable initial heads plus current heads/target relations, PR URLs/states, reviews, checks, rules, operational references, changes, overlaps, rationale and verified actions.
- [Every added branch](added-branches.md), [added-branch JSON](added-branches.json): {len(added)} additional branches captured during concurrent work.
- [Concurrent deletion evidence and recovery commands](concurrent-deletions.md), [verified Git recovery bundle](../concurrent-deletions-recovery.bundle).
- [Executed tests and retained failures](validation.md), [per-branch blockers](blocked.md), [timestamped mutation ledger](mutations.jsonl), [count reconciliation](reconciliation.json).
- The adjacent raw snapshots and logs provide paginated API responses, review threads, status/check URLs, source/patch comparisons and test outcomes. No worktree, dependency cache or database is included in the archive.

## Capabilities and limits

The 2026-10-03 continuation refreshed permissions and a complete paginated snapshot. Earlier audit checkout Git metadata was missing; 325 absent top-level and 9,306 nested evidence files were restored and SHA256-verified against the durable archive without overwriting existing files, then a fresh full-history recovery clone and isolated repair worktree were created. All old directories were retained; this does not assert that their missing Git metadata is intact. Current permissions allow local and network operations without sandbox escalation. Two direct GitHub job-log requests returned504/503; the standard run-log endpoint then retrieved the successful exact-head evidence. The browser profile is occupied by another session, so the remaining production login/upload flow has not been validated. The Docker CLI is installed but its daemon capability check was unresponsive; only the owned read-only client was terminated, and isolated native PostgreSQL16 successfully executed the database checks.

The capability check preceded audit mutations. Git/SSH access and GitHub authentication as `diegueins680` worked; [repository permissions](../repository.json) report pull, push, triage, maintain and admin. Read, branch push, PR creation/update, review reply/resolution, issue/PR comment, PR closure and normal merge operations were verified. Issue write and ordinary branch-deletion permissions are supported by repository permissions; issue closure and branch deletion were not exercised merely to test them. No administrator bypass was used.

Main requires one approving review, dismisses stale approvals, and requires conversation resolution. Captured configuration has no CODEOWNERS, named required status contexts or merge queue; repository-prescribed validation still applies. [Protection](../main-protection.json) and [ruleset9478019](../ruleset-9478019.json) prohibit default-branch deletion and non-fast-forward updates. All merge strategies are enabled; normal merge preserves this repository's migration-introduction ancestry. Native-stack merging would rewrite descendants, so the rejected ordinary PR460 merge was followed by independent, history-preserving PR469 instead. No asynchronous stack merge was invoked.

Git/gh, Node/npm, Stack3.7.1/GHC9.10.3, PostgreSQL16, Docker and audit-local Java/TLA+/Alloy tooling were initially available. Java and the local model-checker JAR files were missing at the October4 continuation; current bounded model checks run in prescribed hosted CI, and no local rerun is claimed. Stack's prescribed compiler was used instead of the unsuitable system GHC. Native database/shared-memory, dependency downloads and global compiler caches required normal sandbox escalation. Mobile dependencies used an audit-owned npm cache because the shared cache had root-owned residue; no permission controls were changed. The mobile HTTPS OAuth credential lacked workflow scope; after its rejected push was verified unchanged, explicitly authorized existing SSH access completed the normal workflow-input push. See [transport limitation and resolution](../mobile-workflow-oauth-limitation.json).

Local Docker later became unresponsive; no daemon restart or unrelated container changes were attempted. The earlier154f968aa event head passed complete hosted backend/runtime/schema validation; the separate local110 HTTP cases passed against isolated native PostgreSQL16, not Docker. Visible-browser access failed with a closed transport, so actual Google login/upload is still unverified; PR468's earlier approval and passing CI never waived that acceptance gate; concurrent updates now require new review/checks. External preview/environment/automation configuration cannot be fully certified from repository metadata, preventing conclusive deletion clearance even for integrated branches. Independent approvals and actual production authentication/upload acceptance cannot be fabricated. Datadog access was initially unavailable; another actor corrected its endpoint, and unchanged current-head test reruns subsequently passed before PR469 merged. No monitor assertion was weakened.

The catalog/mail access blocker was resolved autonomously: existing deployment memory identified the dedicated TDF SSH connection, then strict host-key access verified running production containers, immutable image and database binding. The repaired catalog uses bounded read-only SQL; the installed mail monitor retrieves only the two needed protected credentials into memory. [Live catalog verification](../cutover-live-volume-verified.json) and [installed monitor verification](../cutover-live-mail-volume-verified.json) passed. No email was sent, application data changed, service restarted or deployment manually triggered. A dedicated SELECT-only catalog role was provisioned, and ambient PUBLIC schema CREATE was removed while preserving every existing named role's effective capability. An actual write attempt was denied even after disabling read-only defaults. After concurrent main645f56f added 29 tables, coverage correctly failed closed; each table was traced to its migration before explicit SELECT grants restored coverage. The latest live inventory passes with 777 records/652 tables, zero writable tables and no schema CREATE. Public DNS answers and the actual HTTPS socket peer must match the authenticated SSH server address, with normal TLS validation; regressions reject another healthy same-SHA host. The shared helper also requires the exact named production PostgreSQL volume and rejects shadowing child mounts. The installed monitor passed its unchanged scheduled command after an initial transient DNS failure, which is retained. Normal commit/merge CI and configured automation were allowed to run.

## Timestamped inventory and reconciliation

Initial paginated snapshot: **2026-09-28T03:24:04Z — 134 branches, 67 open PRs, 452 total PRs**. The reported 77/27 understated the live counts by **57 branches and 40 open PRs**. [Initial branch pages](../branches-pages.json) and [PR pages](../pulls-pages.json) include historical PR states, PR-less branches and non-default targets. GitHub does not expose a definitive branch creator; PR/commit authors are recorded without asserting creator identity. Age is supporting context only.

Latest complete snapshot: **{rec['timestamp_start'].strip()}–{rec['timestamp_end'].strip()} — {rec['current_branches']} branches, {rec['current_open_prs']} open PRs, {rec['current_total_prs']} total PRs**. Collection is paginated and timestamped, not an atomic transaction. All134 initial names are accounted for:68 remain live and66 are concurrently absent. Twelve additional historical names are also accounted for:five live andseven concurrently absent. No branch is unaccounted for. Earlier continuation notes incorrectly carried the145 count forward; raw snapshots show72 after the23:38 cleanup, then73 afterPR476 creation.

Observed root PR equation: `67 - {audit_closures} audit closures - {audit_merges} audit merges (including automatic460) - 6 concurrent merges (462,467,470,471,473,474) + 7 concurrent PRs (464,467,468,470,471,473,474) + 5 audit PRs (465,469,472,475,476) = {rec['current_open_prs']}`. Branch equation: `134 + 7 concurrent branches + 5 audit branches - 73 concurrent deletions = 73`. Mobile115 is outside root totals. The machine-readable reconciliation is authoritative if subsequent concurrent changes differ from these observed equations.

| Audit result | Verified count |
|---|---:|
| Merged PRs | {audit_merges} — root469,472,475,476 directly; root460 automatically recognized through469 |
| Repair/consolidation implementation PRs published | 8 — root463,465,468,469,472,475,476 and mobile115; PR475 normally merged after exact-head independent approval and passing checks |
| Existing PR target repaired | 1 — root460 |
| New PRs / reopened PRs | 6 / 0 — five root PRs plus mobile115 |
| Closed unmerged PRs | {audit_closures} |
| Remote branches deleted by audit / observed concurrently | 0 / 73 — user directed retaining the concurrent deletions; recovery bundle verified |
| Protected/operational branches | 7 classified;4 currently live,3 concurrently deleted and retained as recovery evidence per user direction |
| Primary blocked/ambiguous classification | {allcounts['BLOCKED_OR_AMBIGUOUS']} — see per-branch decisions |
| Linked issues closed / relevant issues retained open | 0 / 2 — issues128,130 |

## Classification and product intent

| Classification | Initial branches | All captured branches |
|---|---:|---:|
'''
for cls in sorted(allcounts):text+=f'| {cls} | {counts[cls]} | {allcounts[cls]} |\n'
text+='''
Classifications prioritize current architecture/tests/contracts/schemas/docs and configuration, then issue/PR acceptance, review discussions, live callers/flags and newer implementations. Age, inactivity, closed state or failed CI alone never establishes obsolescence. Exact ancestry and [verified squash/whole-range patch equivalence](../squash-proof.json) establish integrated work; they do not establish safe branch deletion.

The 35 event branches contain complementary current work. PR465 preserves their histories and the separate PR339 contribution, repairs current integrity/session/identity/analytics/replay boundaries, and preserves production migration ancestry. Originals remain open until the replacement is safely integrated. The 22 payment branches retain unique value but depend on unresolved root PR331 no-charge-finality evidence; current main intentionally defers provider expansion. Closed PR441's unique delivery/recovery notes have been preserved with source attribution in independently approved documentation-rescue PR476, now merged atc4d479c7 with exact target-tree verification. The discovery source histories are integrated through469, with PR460 automatically recognized merged and PR463 closed after final main CI passed. Editorial ownership/source464 is now integrated through475; its closure record requires passing target CI. Source branch presence is reported individually; concurrent deletions are retained per user direction.

## Dependency-ordered verified actions

1. Closed PR415 →409 →402 →397 →394 →391 →390, leaf first, after fresh exact-head ancestry proof into merged PR424 and current main. Each has a classification, evidence, successor and recovery-SHA comment. Every branch remains.
2. Retargeted PR460 to main without changing its head, validated it, then observed GitHub reject ordinary merging because of native-stack requirements. No history-rewriting endpoint was invoked.
3. Published mobile115's generated event contracts and root465's normal-merge event consolidation, preserving contributor attribution. Published and tested follow-up integrity/browser/client repairs; source PRs remain intact.
4. Repaired PR463's canonical shared capacity count and source-locked atomic completion; rescued PR464 failure propagation with attribution. Actual handler/Cron compilation, 28 focused examples and real PostgreSQL concurrency/rollback tests passed. Three original findings were resolved after verified pushes; the later unavailable-SHA thread was retained with ancestry evidence.
5. Published standalone PR469 from current main and exact PR460/463 history, retaining all 116 migration introductions. Verified full hosted backend/schema/runtime tests and independent approval. An unchanged social-client rerun passed; initial failures remain recorded.
6. Published operational PR468 fixes incrementally while preserving concurrent cutover/YouTube evidence: canonical scheduled/manual/import/course/callback paths, read-only messaging diagnostics, credential-alias/secret-output handling, managed-image recognition, accurate incomplete-gate documentation and historical-guide retirement. Current-host catalog/mail adapters and the installed monitor were repaired and live-verified. Final hardening uses registry references plus a database-enforced SELECT-only role and exact approved SQL; actual write denial is verified. The normal merge at 9bbd7d88f incorporated main76c2c05c and its passing security fix; operational files remain identical to live-tested source and 20 targeted tests pass again. Twenty-six concrete review findings were resolved; actual login/upload validation remains open. The ledger records every SHA and reply/resolution.
7. Corrected mobile API/upload profiles and native workflow inputs, then root465's gitlink. After mobile main advanced, normally merged it into mobile115 at `ede1f2a0ccf75f3794c7892f291e1751b279d19e`, resolving three conflicts while preserving stronger signing/runtime/association/API gates and additive event types. All 87 suites/553 tests, release checks and 12 Python tests passed. Another actor subsequently merged the independently reviewed exact ede1f2a head atbca7f39cebcae24b62a4404bf5fd76bb9328f95a. Both normal post-merge workflows passed and ede1f2a is an ancestor of mobile main. The companion repository auto-deleted its source branch. These are observed concurrent actions, not audit mutations. Root465 pins the integrated ede1f2a; current root-head review/checks govern integration.
8. Rechecked the externally corrected Datadog test and reran only the two failed synthetic jobs unchanged. They passed. Requeried PR469 head/base, exact-head checks/statuses, approvals, threads, mergeability, stack and branch-retention settings. Marked ready, normally merged, verified closed/merged state and commit `de76dc7df247937144e1802c17d1842f983cbe13`, and confirmed its tree exactly equals the tested candidate. Branch retained; normal CI was observed.
9. Post-merge CI newly rejected existing ip-address10.3.1 for two published advisories. Published focused PR472 at `d1f1affcd3fbd7e4fde78f2dce25ef0993c34b92`, changing only its compatible lock version/URL/integrity to10.7.2. The exact unchanged audit-ci gate passes; four old/new vulnerability cases and two public controls pass. No security allowlist, threshold or dependency range changed. After fresh exact-head independent approval and passing checks, normally merged PR472 at `76c2c05c536586fd814f7a68d2052f0fd9d900ed` and verified its target tree matches the tested candidate. Normal post-merge CI is tracked separately.

10. After main76c2c05c workflows/checks passed, closed PR463 with an exact-head ancestry/evidence/recovery comment and preserved its branch. GitHub had already automatically marked PR460 merged at PR469's merge commit; the closure safety check stopped before any further PR460 action. This is counted as a third merged PR, not a third direct merge operation.
11. Published 82c4c448a with actual TLS-peer/DNS binding to authenticated SSH metadata. Initial inventory attempts failed on table coverage after concurrent deployment; reviewed all 29 added table definitions and granted SELECT only under exact deployment/schema/role guards. The actual inventory then passed with 777 records/652 tables, zero writable tables and no schema CREATE. Published 60c7c42e7 with required --check replacement commands and verified both review resolutions. No application-data mutation or manual deployment. Follow-up 385cdb307 adds a required verify-token guard to both printed webhook commands; 95 token-workflow tests pass and the review resolution is verified.

12. Published cd915b8 with authoritative named-volume verification; ten access, five catalog and six mail tests passed. Verified actual production catalog provenance and the installed scheduled mailbox command; no messages sent. Resolved the addressed volume thread.
13. Normally merged main49f1 into event PR465 at23ff8f588, retaining mobile ede1f2a and preserving all source histories. Verified2648 UI tests, web build,3576 backend examples and107 real HTTP/PostgreSQL cases. Repaired catalog successor drift without changing regression assertions, and addressed disabled task discovery plus late follow-cache invalidation. The append-only ledger records the follow-up push and verified review resolutions; no event merge is claimed.

14. Published standalone draft PR475 at9ecac924a after fresh exact source/main and remote-branch absence checks. A normal merge preserves source464 and main49f1 histories; GitHub confirms draft state, targetmain and no native stack. Repository/formal/catalog/inventory gates and ten actual PostgreSQL16 source-derived predicate cases passed. The complete hosted backend job subsequently passed3553 examples/zero failures, the compiled PostgreSQL predicate,1141 social HTTP examples and all runtime/schema stages. A further directory-function gap was repaired through immutable migration6e7b87d8a and registration4100a04c;160-migration native schema/reapply/old-order/privacy tests and release82/CI27/formal/catalog gates pass. Fresh4100 hosted CI then passed all applicable checks, including3553 Hspec examples, compiled PostgreSQL and the automatic production-migration rehearsal. The local Stack-built3553-example suite and compiled PostgreSQL1+15 suites also passed; two local build-wrapper failures remain separately recorded. Marked ready only after fresh exact-head, conflict, check, review and thread verification. This was the pre-review checkpoint; PR475 subsequently received exact-head independent approval and merged normally atf8925e339. Its target tree and ancestry are verified. Source464 closure is recorded only after passing target CI. A later automated review cited a different commit when questioning migration ancestry. Fresh GitHub evidence and all160 local ancestry checks prove the actual4100 head and proposed normal merge retain the introduction; an evidence reply and resolved thread were verified. A normal merge was used, and no release guard was changed. See [ancestry verification](../editorial-review-ancestry-verified.json) and [resolved discussion](../editorial-ancestry-resolved-verified.json).

15. After fresh exact-head independent approval, protections/rules/checks/status/threads/base and branch-retention verification, normally merged PR475 atf8925e339. Verified both parents, exact tested tree and retained branch. Reconciled the resulting PR465 catalog conflict with a normal merge at08acdfa897832c42ef1582f26ffdd7c23f019b4c; all event decisions remain and both main additions are exact. Two current migration mappings now target the160-entry reviewed registry while retaining full prior mappings. Five unchanged catalog regressions, strict1171-candidate gate,83 release tests,32 CI tests, repository/formal/inventory gates pass. The08acdfa hosted backend passed3587 examples/zero failures and107 HTTP examples; all applicable checks and exact-head approval passed. A fresh pre-merge guard stopped before mutation on two new review findings. Mobile115 integration is now verified.

16. Fixed both legitimate lifecycle findings at34ca75d: retain the enabled feature-flag share lock through the transition transaction, and decode/bind lifecycle receipts inside SqlPersistT so malformed responses roll back all writes. Two pure decoder cases and one authenticated HTTP regression cover eight corrupt response forms. The complete native HTTP suite passed110 examples; the SQL negative control reproduced the old feature-flag race and all six fixed lock-order/isolation cases passed. Both review threads were replied to and resolved only after verified push and test evidence. All160 registered production SQL files remain byte-identical and the event adapter remains unregistered/disabled.
17. Hosted34ca task-completion CI failed with an opaque exit1. Inspection found the15-second expiry fixture had only100 polling intervals of0.1seconds on fast runners. Normal commit154f968aa permits200 polls and adds a timeout diagnostic without changing any security assertion. Both baseline and corrected full native PostgreSQL suites passed locally; this is explicitly not a reproduced hosted failure. Three inventory tests, generated inventory check, shell syntax and whitespace checks passed. Fresh current-head CI and review are required.
18. Rescued PR441's remaining unique historical notification delivery/recovery notes in standalone PR476 at6d00fa1463603bacecbb3210279b09ed88bbba0c, retaining exact source text and attribution with explicit September18 scope. No mobile pin changes or new device qualification claims. The original pin is an ancestor of the integrated mobile companion. Corrected the generated documentation hash in a normal follow-up commit and verified the inventory check. Source441 and both root branches remain. Current-head checks and independent review passed; PR476 merged normally atc4d479c7 with exact tested tree. Post-merge CI is tracked separately.
19. Published PR468 provenance fixes atce1a71fe2 after fresh remote-head checks, preserving concurrent762e1ff. All23 focused tests, strict1162 catalog candidates and inventory checks passed. Both addressed threads were replied to and resolved after verified push. SSH timeout blocks current live verification and installed-helper update; HTTPS health alone is not treated as authenticated deployment proof.
20. After exact-head approval, passing checks and fresh protections/rules/threads/base/settings verification, normally merged documentation PR476 atc4d479c7f3da659368e5bc60464a1a43c99d9b7a. Verified both parents, exact tested tree and retained branch.
21. After every normal mainf8925 workflow/check passed, closed source464 with exact-head ancestry, merged successor and recovery-SHA evidence. Both branches remain. No event source PR was closed.

The [append-only mutation ledger](mutations.jsonl) supplies exact timestamps, SHAs, URLs, rejected attempts and verification, including the installed monitor's original/new hashes. PR462/467/470/471/473/474 merges and PR464/467/468/470/471/473/474 creation/progress were concurrent actions, not audit mutations. No audit branch deletion occurred. All73 concurrent root deletions have exact recovery commands and a verified bundle in [concurrent deletion evidence](concurrent-deletions.md); the concurrent mobile source branch can be recovered in the mobile repository with `git push origin ede1f2a0ccf75f3794c7892f291e1751b279d19e:refs/heads/audit/event-operations-client-20260928` after fresh safety checks; initial and closure head SHAs remain available.

## Current candidates

| PR | Current head | State / draft | Review / unresolved | Captured check conclusions |
|---|---|---|---|---|
'''
for n in [463,464,465,468,469,470,471,472,473,474,475,476]:
 p,c,review,threads=checks(n)
 text+=f'| [#{n}]({p["html_url"]}) | `{p["head"]["sha"]}` | {p["state"]}, draft={p["draft"]}, merged={p["merged"]} | {review}; {threads} unresolved | {c} |\n'
text+=f'''
Mobile [PR115]({mobile['html_url']}) head `{mobile['head']['sha']}`, state `{mobile['state']}`, mergeability `{mobile['mergeable_state']}`. [Current checks](../{F.name}/mobile-checks.json) and [reviews](../{F.name}/mobile-reviews.json) govern integration. Earlier approvals/checks are not transferred to newer heads. The [latest candidate recheck](../latest-candidate-state.json) records the historical PR468 approval at cd915b8; concurrent762e1ff updates dismissed that approval the two new provenance review findings are fixed atce1a71fe2 with resolved threads, while the manual acceptance thread and live SSH validation remain open; PR465 now at ee58bd13 after current-main reconciliation, with current-head checks/review required; mobile115 is concurrently merged and both post-merge workflows passed. PR475 has exact-head independent approval and verified normal merge. Snapshot rows above supply the current check and review states.

## Remaining blockers and smallest next steps

- **PR472 / post-merge main:** the approved tested security fix is merged; all checks and workflow runs on main76c2c05c passed before the source closure, recorded in [final CI evidence](../discovery-closure-main-ci.json). PR469's intended source/tree is verified; its post-merge security failure is preserved and is not described as a green result. PR460 was automatically recognized merged and PR463 closed only after final main CI passed; the later concurrent deletion of PR460's source is preserved as recovery evidence.
- **Root465 / 35 event originals:** mobile115 is integrated with passing post-merge checks. Root465 contains mainf8925, the integrated ede1f2a companion and lifecycle safety fixes34ca75d. Its154f968aa had independent approval and all checks passing; normal reconciliationee58bd13 now publishes mainc4d479c7, preserves the reviewed document exactly and passes the generated inventory check. Fresh checks/review on ee58 govern integration. 154f968aa corrected the completion-test polling budget; require completion of hosted backend and target CI plus a final fresh review/thread/head/base recheck. Only after replacement merge and passing target CI should source closures be reconsidered.
- **PR468:** concurrent762e1ff incorporated current main and updated CI triggers; prior approval does not transfer. Two new findings were fixed and published atce1a71fe2: post-query public-origin revalidation and configured PostgreSQL-image verification. Both addressed threads are resolved with23 focused tests, strict1162-candidate catalog and inventory checks passing. Live SSH access currently times out, so this new helper has not been installed or live-verified. The browser profile remains occupied, so actual Google interactive login and authenticated upload remain unverified. Fresh exact-head review/checks and live operational validation remain required; no waiver is claimed.
- **22 payment branches / PR331:** authenticated merchant/environment-qualified terminal-resource or cancellation contract that rules out pending/late authorization/capture/hosted retry, with sandbox traces bound to checkout identity. Then address root review and integrate dependents topologically. Transport errors alone are insufficient.
- **PR475 / source464:** replacement475 is approved and normally merged atf8925e339, retaining the exact tested4100 tree and all migration introduction ancestry. All pre-merge hosted/local backend, database, migration and metadata-boundary tests passed. All normal mainf8925 checks/workflows passed and source464 closure is verified in the branch matrix and mutation ledger; source464 is never closed merely because its replacement merged. Both branches remain. This work no longer awaits PR475 approval.

- **Concurrent PR470/471/473/474 (integrated):** another actor merged interaction work, its stacked qualification tooling, the deletion/focus fix and the DOMPurify security repair. Their merged records and target ancestry are verified; the source refs were concurrently deleted and recovery evidence retained. Author-run deployment/native evidence is not claimed as audit-executed work. These are no longer pending integration cases; their refs were concurrently deleted and retained as recovery evidence per user direction. This audit manually deployed nothing.
- **PR476 / closed441:** documentation rescue476 is independently approved and normally merged atc4d479c7; exact target tree, retained source text and original mobile-pin ancestry are verified. Source441 is already closed and its branch remains. Normal post-merge CI is tracked separately; no issue acceptance or device qualification is inferred.
- **Integrated/operational branches:** this audit performs no deletion without conclusive clearance. The user explicitly directed retaining73 deletions performed by another session, including three operational refs. Their exact heads, commands and complete reachable history are preserved in a verified recovery bundle; no restoration is pending.
- **Issues128/130:** remain open. Issue128 requires first-install/signup enrollment, three arms across web/mobile, RSVP plus fanclub broadcast, shared analytics and 6–8 weeks of evaluation. Issue130 requires headliner resolution, deduplicated broadcast and preference/privacy behavior. Source integration alone proves neither acceptance criterion; [latest issue states](../final-linked-issues.json), [issue bodies](../issues.json) and [scope decision](../issues/128-comments.json) remain authoritative.

## Validation and workspace preservation

[The complete validation table](validation.md) records actual commands/logs and failed initial runs. It includes the event backend's 3,573 examples/zero failures/six separate-runner cases, eight isolated runtime suites, 107 production-auth HTTP examples, database races/rollback/negative controls, formal/catalog/schema checks, UI/browser suites and mobile tests. Discovery's exact-head hosted suite passed 3,542 examples/zero failures, 1,141 social HTTP examples and runtime/schema rehearsal. Duplicate local compilation stopped after hosted verification is recorded as exit130, not a pass. The initial UI failures and unchanged successful reruns are retained. Existing mobile dependency findings were not hidden or threshold-bypassed. The root security-audit pass uses the unchanged existing allowlist; four pre-existing high transitive findings remain in its captured output, so a policy pass is not a zero-vulnerability claim.

Current-main event validation adds2,648 UI tests/241 suites,3,576 backend examples with zero failures and six separately exercised runner cases,107 actual HTTP examples against isolated native PostgreSQL16,83 release and32 CI wiring tests, unchanged security/catalog gates and reproduced generated clients. Follow-up review repair adds27 focused UI tests (including two new late-mutation regressions) and five unchanged catalog regression tests. Current-head CI still governs merge readiness. Latest repairs add 553 mobile tests and 12 signing tests; 122 cutover helper tests; ten current-access, six mail and five catalog tests; four retired-writer tests; specification/evidence checks; actual read-only current-host catalog and installed mailbox verification; and the unchanged security audit plus four reproduced-before/fixed-after address cases and two controls. [Advisory1](https://github.com/advisories/GHSA-rpw4-54j3-4h4q) and [advisory2](https://github.com/advisories/GHSA-2vr4-cq9g-pvrc) identify the dependency flaws and patched ranges.

All 66 originally existing worktree directories and `/private/tmp/tdf-branch-audit-20260928` remain present. [Current preservation/disk check](../workspace-preservation-20261004.json) distinguishes directory presence from Git metadata integrity: three original temporary directories lack their `.git` entry, and old audit checkout metadata was also missing before this continuation. The audit deleted no worktrees and uses a new full-history clone rather than overwriting those directories. Authorized cleanup additionally reclaimed approximately3.2GiB: uv removed42,595 regenerable files/1.4GiB, and eight proven inactive npm CLI caches freed1,848,024KiB; active process/open-file use was rechecked and the browser cache preserved. Disk availability fluctuates with concurrent builds; reclaimed capacity is not asserted to remain free. [Cleanup evidence](../npm-unused-cli-cleanup.json) and the original [workspace snapshot](../tdf-disk-cleanup-20260928.json) are retained. Unrelated working-tree changes, existing worktrees, production credentials, shared history and repository controls were preserved.
'''
(R/'README.md').write_text(text)
print('Wrote complete current overview',F.name)
