-- This file is generated by scripts/sync-country-reference.mjs.
-- Source: https://unstats.un.org/unsd/methodology/m49/overview/
-- ISO supplement evidence: ISO 3166/MA TW/TWN/158.
{-# LANGUAGE OverloadedStrings #-}

module TDF.Catalog.CountryReferenceSeed
  ( CountryReferenceSeed(..)
  , countryReferenceSnapshotDate
  , countryReferenceSourceVersion
  , countryReferenceSeeds
  ) where

import Data.Text (Text)

data CountryReferenceSeed = CountryReferenceSeed
  { countrySeedAlpha2 :: Text
  , countrySeedAlpha3 :: Text
  , countrySeedNumericCode :: Text
  , countrySeedNameEs :: Text
  , countrySeedNameEn :: Text
  , countrySeedSortOrder :: Int
  } deriving (Eq, Show)

countryReferenceSnapshotDate :: Text
countryReferenceSnapshotDate = "2026-08-11"

countryReferenceSourceVersion :: Text
countryReferenceSourceVersion = "UN M49 2026-08-11 + ISO 3166/MA TW"

countryReferenceSeeds :: [CountryReferenceSeed]
countryReferenceSeeds =
  [ CountryReferenceSeed "AF" "AFG" "004" "Afganistán" "Afghanistan" 0
  , CountryReferenceSeed "AL" "ALB" "008" "Albania" "Albania" 1
  , CountryReferenceSeed "DE" "DEU" "276" "Alemania" "Germany" 2
  , CountryReferenceSeed "AD" "AND" "020" "Andorra" "Andorra" 3
  , CountryReferenceSeed "AO" "AGO" "024" "Angola" "Angola" 4
  , CountryReferenceSeed "AI" "AIA" "660" "Anguila" "Anguilla" 5
  , CountryReferenceSeed "AG" "ATG" "028" "Antigua y Barbuda" "Antigua and Barbuda" 6
  , CountryReferenceSeed "AQ" "ATA" "010" "Antártida" "Antarctica" 7
  , CountryReferenceSeed "SA" "SAU" "682" "Arabia Saudita" "Saudi Arabia" 8
  , CountryReferenceSeed "DZ" "DZA" "012" "Argelia" "Algeria" 9
  , CountryReferenceSeed "AR" "ARG" "032" "Argentina" "Argentina" 10
  , CountryReferenceSeed "AM" "ARM" "051" "Armenia" "Armenia" 11
  , CountryReferenceSeed "AW" "ABW" "533" "Aruba" "Aruba" 12
  , CountryReferenceSeed "AU" "AUS" "036" "Australia" "Australia" 13
  , CountryReferenceSeed "AT" "AUT" "040" "Austria" "Austria" 14
  , CountryReferenceSeed "AZ" "AZE" "031" "Azerbaiyán" "Azerbaijan" 15
  , CountryReferenceSeed "BS" "BHS" "044" "Bahamas" "Bahamas" 16
  , CountryReferenceSeed "BH" "BHR" "048" "Bahrein" "Bahrain" 17
  , CountryReferenceSeed "BD" "BGD" "050" "Bangladesh" "Bangladesh" 18
  , CountryReferenceSeed "BB" "BRB" "052" "Barbados" "Barbados" 19
  , CountryReferenceSeed "BY" "BLR" "112" "Belarús" "Belarus" 20
  , CountryReferenceSeed "BZ" "BLZ" "084" "Belice" "Belize" 21
  , CountryReferenceSeed "BJ" "BEN" "204" "Benin" "Benin" 22
  , CountryReferenceSeed "BM" "BMU" "060" "Bermuda" "Bermuda" 23
  , CountryReferenceSeed "BT" "BTN" "064" "Bhután" "Bhutan" 24
  , CountryReferenceSeed "BO" "BOL" "068" "Bolivia (Estado Plurinacional de)" "Bolivia (Plurinational State of)" 25
  , CountryReferenceSeed "BQ" "BES" "535" "Bonaire, San Eustaquio y Saba" "Bonaire, Sint Eustatius and Saba" 26
  , CountryReferenceSeed "BA" "BIH" "070" "Bosnia y Herzegovina" "Bosnia and Herzegovina" 27
  , CountryReferenceSeed "BW" "BWA" "072" "Botswana" "Botswana" 28
  , CountryReferenceSeed "BR" "BRA" "076" "Brasil" "Brazil" 29
  , CountryReferenceSeed "BN" "BRN" "096" "Brunei Darussalam" "Brunei Darussalam" 30
  , CountryReferenceSeed "BG" "BGR" "100" "Bulgaria" "Bulgaria" 31
  , CountryReferenceSeed "BF" "BFA" "854" "Burkina Faso" "Burkina Faso" 32
  , CountryReferenceSeed "BI" "BDI" "108" "Burundi" "Burundi" 33
  , CountryReferenceSeed "BE" "BEL" "056" "Bélgica" "Belgium" 34
  , CountryReferenceSeed "CV" "CPV" "132" "Cabo Verde" "Cabo Verde" 35
  , CountryReferenceSeed "KH" "KHM" "116" "Camboya" "Cambodia" 36
  , CountryReferenceSeed "CM" "CMR" "120" "Camerún" "Cameroon" 37
  , CountryReferenceSeed "CA" "CAN" "124" "Canadá" "Canada" 38
  , CountryReferenceSeed "TD" "TCD" "148" "Chad" "Chad" 39
  , CountryReferenceSeed "CZ" "CZE" "203" "Chequia" "Czechia" 40
  , CountryReferenceSeed "CL" "CHL" "152" "Chile" "Chile" 41
  , CountryReferenceSeed "CN" "CHN" "156" "China" "China" 42
  , CountryReferenceSeed "HK" "HKG" "344" "China, región administrativa especial de Hong Kong" "China, Hong Kong Special Administrative Region" 43
  , CountryReferenceSeed "MO" "MAC" "446" "China, región administrativa especial de Macao" "China, Macao Special Administrative Region" 44
  , CountryReferenceSeed "CY" "CYP" "196" "Chipre" "Cyprus" 45
  , CountryReferenceSeed "CO" "COL" "170" "Colombia" "Colombia" 46
  , CountryReferenceSeed "KM" "COM" "174" "Comoras" "Comoros" 47
  , CountryReferenceSeed "CG" "COG" "178" "Congo" "Congo" 48
  , CountryReferenceSeed "CR" "CRI" "188" "Costa Rica" "Costa Rica" 49
  , CountryReferenceSeed "HR" "HRV" "191" "Croacia" "Croatia" 50
  , CountryReferenceSeed "CU" "CUB" "192" "Cuba" "Cuba" 51
  , CountryReferenceSeed "CW" "CUW" "531" "Curazao" "Curaçao" 52
  , CountryReferenceSeed "CI" "CIV" "384" "Côte d’Ivoire" "Côte d’Ivoire" 53
  , CountryReferenceSeed "DK" "DNK" "208" "Dinamarca" "Denmark" 54
  , CountryReferenceSeed "DJ" "DJI" "262" "Djibouti" "Djibouti" 55
  , CountryReferenceSeed "DM" "DMA" "212" "Dominica" "Dominica" 56
  , CountryReferenceSeed "EC" "ECU" "218" "Ecuador" "Ecuador" 57
  , CountryReferenceSeed "EG" "EGY" "818" "Egipto" "Egypt" 58
  , CountryReferenceSeed "SV" "SLV" "222" "El Salvador" "El Salvador" 59
  , CountryReferenceSeed "AE" "ARE" "784" "Emiratos Árabes Unidos" "United Arab Emirates" 60
  , CountryReferenceSeed "ER" "ERI" "232" "Eritrea" "Eritrea" 61
  , CountryReferenceSeed "SK" "SVK" "703" "Eslovaquia" "Slovakia" 62
  , CountryReferenceSeed "SI" "SVN" "705" "Eslovenia" "Slovenia" 63
  , CountryReferenceSeed "ES" "ESP" "724" "España" "Spain" 64
  , CountryReferenceSeed "PS" "PSE" "275" "Estado de Palestina" "State of Palestine" 65
  , CountryReferenceSeed "US" "USA" "840" "Estados Unidos de América" "United States of America" 66
  , CountryReferenceSeed "EE" "EST" "233" "Estonia" "Estonia" 67
  , CountryReferenceSeed "SZ" "SWZ" "748" "Eswatini" "Eswatini" 68
  , CountryReferenceSeed "ET" "ETH" "231" "Etiopía" "Ethiopia" 69
  , CountryReferenceSeed "RU" "RUS" "643" "Federación de Rusia" "Russian Federation" 70
  , CountryReferenceSeed "FJ" "FJI" "242" "Fiji" "Fiji" 71
  , CountryReferenceSeed "PH" "PHL" "608" "Filipinas" "Philippines" 72
  , CountryReferenceSeed "FI" "FIN" "246" "Finlandia" "Finland" 73
  , CountryReferenceSeed "FR" "FRA" "250" "Francia" "France" 74
  , CountryReferenceSeed "GA" "GAB" "266" "Gabón" "Gabon" 75
  , CountryReferenceSeed "GM" "GMB" "270" "Gambia" "Gambia" 76
  , CountryReferenceSeed "GE" "GEO" "268" "Georgia" "Georgia" 77
  , CountryReferenceSeed "GS" "SGS" "239" "Georgia del Sur y las Islas Sandwich del Sur" "South Georgia and the South Sandwich Islands" 78
  , CountryReferenceSeed "GH" "GHA" "288" "Ghana" "Ghana" 79
  , CountryReferenceSeed "GI" "GIB" "292" "Gibraltar" "Gibraltar" 80
  , CountryReferenceSeed "GD" "GRD" "308" "Granada" "Grenada" 81
  , CountryReferenceSeed "GR" "GRC" "300" "Grecia" "Greece" 82
  , CountryReferenceSeed "GL" "GRL" "304" "Groenlandia" "Greenland" 83
  , CountryReferenceSeed "GP" "GLP" "312" "Guadalupe" "Guadeloupe" 84
  , CountryReferenceSeed "GU" "GUM" "316" "Guam" "Guam" 85
  , CountryReferenceSeed "GT" "GTM" "320" "Guatemala" "Guatemala" 86
  , CountryReferenceSeed "GF" "GUF" "254" "Guayana Francesa" "French Guiana" 87
  , CountryReferenceSeed "GG" "GGY" "831" "Guernsey" "Guernsey" 88
  , CountryReferenceSeed "GN" "GIN" "324" "Guinea" "Guinea" 89
  , CountryReferenceSeed "GQ" "GNQ" "226" "Guinea Ecuatorial" "Equatorial Guinea" 90
  , CountryReferenceSeed "GW" "GNB" "624" "Guinea-Bissau" "Guinea-Bissau" 91
  , CountryReferenceSeed "GY" "GUY" "328" "Guyana" "Guyana" 92
  , CountryReferenceSeed "HT" "HTI" "332" "Haití" "Haiti" 93
  , CountryReferenceSeed "HN" "HND" "340" "Honduras" "Honduras" 94
  , CountryReferenceSeed "HU" "HUN" "348" "Hungría" "Hungary" 95
  , CountryReferenceSeed "IN" "IND" "356" "India" "India" 96
  , CountryReferenceSeed "ID" "IDN" "360" "Indonesia" "Indonesia" 97
  , CountryReferenceSeed "IQ" "IRQ" "368" "Iraq" "Iraq" 98
  , CountryReferenceSeed "IE" "IRL" "372" "Irlanda" "Ireland" 99
  , CountryReferenceSeed "IR" "IRN" "364" "Irán (República Islámica del)" "Iran (Islamic Republic of)" 100
  , CountryReferenceSeed "BV" "BVT" "074" "Isla Bouvet" "Bouvet Island" 101
  , CountryReferenceSeed "CX" "CXR" "162" "Isla Christmas" "Christmas Island" 102
  , CountryReferenceSeed "NF" "NFK" "574" "Isla Norfolk" "Norfolk Island" 103
  , CountryReferenceSeed "IM" "IMN" "833" "Isla de Man" "Isle of Man" 104
  , CountryReferenceSeed "IS" "ISL" "352" "Islandia" "Iceland" 105
  , CountryReferenceSeed "KY" "CYM" "136" "Islas Caimán" "Cayman Islands" 106
  , CountryReferenceSeed "CC" "CCK" "166" "Islas Cocos (Keeling)" "Cocos (Keeling) Islands" 107
  , CountryReferenceSeed "CK" "COK" "184" "Islas Cook" "Cook Islands" 108
  , CountryReferenceSeed "FO" "FRO" "234" "Islas Feroe" "Faroe Islands" 109
  , CountryReferenceSeed "HM" "HMD" "334" "Islas Heard y McDonald" "Heard Island and McDonald Islands" 110
  , CountryReferenceSeed "FK" "FLK" "238" "Islas Malvinas (Falkland)" "Falkland Islands (Malvinas)" 111
  , CountryReferenceSeed "MP" "MNP" "580" "Islas Marianas Septentrionales" "Northern Mariana Islands" 112
  , CountryReferenceSeed "MH" "MHL" "584" "Islas Marshall" "Marshall Islands" 113
  , CountryReferenceSeed "SB" "SLB" "090" "Islas Salomón" "Solomon Islands" 114
  , CountryReferenceSeed "SJ" "SJM" "744" "Islas Svalbard y Jan Mayen" "Svalbard and Jan Mayen Islands" 115
  , CountryReferenceSeed "TC" "TCA" "796" "Islas Turcas y Caicos" "Turks and Caicos Islands" 116
  , CountryReferenceSeed "VG" "VGB" "092" "Islas Vírgenes Británicas" "British Virgin Islands" 117
  , CountryReferenceSeed "VI" "VIR" "850" "Islas Vírgenes de los Estados Unidos" "United States Virgin Islands" 118
  , CountryReferenceSeed "WF" "WLF" "876" "Islas Wallis y Futuna" "Wallis and Futuna Islands" 119
  , CountryReferenceSeed "UM" "UMI" "581" "Islas menores alejadas de Estados Unidos" "United States Minor Outlying Islands" 120
  , CountryReferenceSeed "AX" "ALA" "248" "Islas Åland" "Åland Islands" 121
  , CountryReferenceSeed "IL" "ISR" "376" "Israel" "Israel" 122
  , CountryReferenceSeed "IT" "ITA" "380" "Italia" "Italy" 123
  , CountryReferenceSeed "JM" "JAM" "388" "Jamaica" "Jamaica" 124
  , CountryReferenceSeed "JP" "JPN" "392" "Japón" "Japan" 125
  , CountryReferenceSeed "JE" "JEY" "832" "Jersey" "Jersey" 126
  , CountryReferenceSeed "JO" "JOR" "400" "Jordania" "Jordan" 127
  , CountryReferenceSeed "KZ" "KAZ" "398" "Kazajstán" "Kazakhstan" 128
  , CountryReferenceSeed "KE" "KEN" "404" "Kenya" "Kenya" 129
  , CountryReferenceSeed "KG" "KGZ" "417" "Kirguistán" "Kyrgyzstan" 130
  , CountryReferenceSeed "KI" "KIR" "296" "Kiribati" "Kiribati" 131
  , CountryReferenceSeed "KW" "KWT" "414" "Kuwait" "Kuwait" 132
  , CountryReferenceSeed "LS" "LSO" "426" "Lesotho" "Lesotho" 133
  , CountryReferenceSeed "LV" "LVA" "428" "Letonia" "Latvia" 134
  , CountryReferenceSeed "LR" "LBR" "430" "Liberia" "Liberia" 135
  , CountryReferenceSeed "LY" "LBY" "434" "Libia" "Libya" 136
  , CountryReferenceSeed "LI" "LIE" "438" "Liechtenstein" "Liechtenstein" 137
  , CountryReferenceSeed "LT" "LTU" "440" "Lituania" "Lithuania" 138
  , CountryReferenceSeed "LU" "LUX" "442" "Luxemburgo" "Luxembourg" 139
  , CountryReferenceSeed "LB" "LBN" "422" "Líbano" "Lebanon" 140
  , CountryReferenceSeed "MK" "MKD" "807" "Macedonia del Norte" "North Macedonia" 141
  , CountryReferenceSeed "MG" "MDG" "450" "Madagascar" "Madagascar" 142
  , CountryReferenceSeed "MY" "MYS" "458" "Malasia" "Malaysia" 143
  , CountryReferenceSeed "MW" "MWI" "454" "Malawi" "Malawi" 144
  , CountryReferenceSeed "MV" "MDV" "462" "Maldivas" "Maldives" 145
  , CountryReferenceSeed "MT" "MLT" "470" "Malta" "Malta" 146
  , CountryReferenceSeed "ML" "MLI" "466" "Malí" "Mali" 147
  , CountryReferenceSeed "MA" "MAR" "504" "Marruecos" "Morocco" 148
  , CountryReferenceSeed "MQ" "MTQ" "474" "Martinica" "Martinique" 149
  , CountryReferenceSeed "MU" "MUS" "480" "Mauricio" "Mauritius" 150
  , CountryReferenceSeed "MR" "MRT" "478" "Mauritania" "Mauritania" 151
  , CountryReferenceSeed "YT" "MYT" "175" "Mayotte" "Mayotte" 152
  , CountryReferenceSeed "FM" "FSM" "583" "Micronesia (Estados Federados de)" "Micronesia (Federated States of)" 153
  , CountryReferenceSeed "MN" "MNG" "496" "Mongolia" "Mongolia" 154
  , CountryReferenceSeed "ME" "MNE" "499" "Montenegro" "Montenegro" 155
  , CountryReferenceSeed "MS" "MSR" "500" "Montserrat" "Montserrat" 156
  , CountryReferenceSeed "MZ" "MOZ" "508" "Mozambique" "Mozambique" 157
  , CountryReferenceSeed "MM" "MMR" "104" "Myanmar" "Myanmar" 158
  , CountryReferenceSeed "MX" "MEX" "484" "México" "Mexico" 159
  , CountryReferenceSeed "MC" "MCO" "492" "Mónaco" "Monaco" 160
  , CountryReferenceSeed "NA" "NAM" "516" "Namibia" "Namibia" 161
  , CountryReferenceSeed "NR" "NRU" "520" "Nauru" "Nauru" 162
  , CountryReferenceSeed "NP" "NPL" "524" "Nepal" "Nepal" 163
  , CountryReferenceSeed "NI" "NIC" "558" "Nicaragua" "Nicaragua" 164
  , CountryReferenceSeed "NG" "NGA" "566" "Nigeria" "Nigeria" 165
  , CountryReferenceSeed "NU" "NIU" "570" "Niue" "Niue" 166
  , CountryReferenceSeed "NO" "NOR" "578" "Noruega" "Norway" 167
  , CountryReferenceSeed "NC" "NCL" "540" "Nueva Caledonia" "New Caledonia" 168
  , CountryReferenceSeed "NZ" "NZL" "554" "Nueva Zelandia" "New Zealand" 169
  , CountryReferenceSeed "NE" "NER" "562" "Níger" "Niger" 170
  , CountryReferenceSeed "OM" "OMN" "512" "Omán" "Oman" 171
  , CountryReferenceSeed "PK" "PAK" "586" "Pakistán" "Pakistan" 172
  , CountryReferenceSeed "PW" "PLW" "585" "Palau" "Palau" 173
  , CountryReferenceSeed "PA" "PAN" "591" "Panamá" "Panama" 174
  , CountryReferenceSeed "PG" "PNG" "598" "Papua Nueva Guinea" "Papua New Guinea" 175
  , CountryReferenceSeed "PY" "PRY" "600" "Paraguay" "Paraguay" 176
  , CountryReferenceSeed "NL" "NLD" "528" "Países Bajos (Reino de los)" "Netherlands (Kingdom of the)" 177
  , CountryReferenceSeed "PE" "PER" "604" "Perú" "Peru" 178
  , CountryReferenceSeed "PN" "PCN" "612" "Pitcairn" "Pitcairn" 179
  , CountryReferenceSeed "PF" "PYF" "258" "Polinesia Francesa" "French Polynesia" 180
  , CountryReferenceSeed "PL" "POL" "616" "Polonia" "Poland" 181
  , CountryReferenceSeed "PT" "PRT" "620" "Portugal" "Portugal" 182
  , CountryReferenceSeed "PR" "PRI" "630" "Puerto Rico" "Puerto Rico" 183
  , CountryReferenceSeed "QA" "QAT" "634" "Qatar" "Qatar" 184
  , CountryReferenceSeed "GB" "GBR" "826" "Reino Unido de Gran Bretaña e Irlanda del Norte" "United Kingdom of Great Britain and Northern Ireland" 185
  , CountryReferenceSeed "CF" "CAF" "140" "República Centroafricana" "Central African Republic" 186
  , CountryReferenceSeed "LA" "LAO" "418" "República Democrática Popular Lao" "Lao People's Democratic Republic" 187
  , CountryReferenceSeed "CD" "COD" "180" "República Democrática del Congo" "Democratic Republic of the Congo" 188
  , CountryReferenceSeed "DO" "DOM" "214" "República Dominicana" "Dominican Republic" 189
  , CountryReferenceSeed "KP" "PRK" "408" "República Popular Democrática de Corea" "Democratic People's Republic of Korea" 190
  , CountryReferenceSeed "TZ" "TZA" "834" "República Unida de Tanzanía" "United Republic of Tanzania" 191
  , CountryReferenceSeed "KR" "KOR" "410" "República de Corea" "Republic of Korea" 192
  , CountryReferenceSeed "MD" "MDA" "498" "República de Moldova" "Republic of Moldova" 193
  , CountryReferenceSeed "SY" "SYR" "760" "República Árabe Siria" "Syrian Arab Republic" 194
  , CountryReferenceSeed "RE" "REU" "638" "Reunión" "Réunion" 195
  , CountryReferenceSeed "RO" "ROU" "642" "Rumania" "Romania" 196
  , CountryReferenceSeed "RW" "RWA" "646" "Rwanda" "Rwanda" 197
  , CountryReferenceSeed "KN" "KNA" "659" "Saint Kitts y Nevis" "Saint Kitts and Nevis" 198
  , CountryReferenceSeed "WS" "WSM" "882" "Samoa" "Samoa" 199
  , CountryReferenceSeed "AS" "ASM" "016" "Samoa Americana" "American Samoa" 200
  , CountryReferenceSeed "BL" "BLM" "652" "San Barthélemy" "Saint Barthélemy" 201
  , CountryReferenceSeed "SM" "SMR" "674" "San Marino" "San Marino" 202
  , CountryReferenceSeed "SX" "SXM" "534" "San Martín (parte Holandesa)" "Sint Maarten (Dutch part)" 203
  , CountryReferenceSeed "MF" "MAF" "663" "San Martín (parte francesa)" "Saint Martin (French Part)" 204
  , CountryReferenceSeed "PM" "SPM" "666" "San Pedro y Miquelón" "Saint Pierre and Miquelon" 205
  , CountryReferenceSeed "VC" "VCT" "670" "San Vicente y las Granadinas" "Saint Vincent and the Grenadines" 206
  , CountryReferenceSeed "SH" "SHN" "654" "Santa Elena" "Saint Helena" 207
  , CountryReferenceSeed "LC" "LCA" "662" "Santa Lucía" "Saint Lucia" 208
  , CountryReferenceSeed "VA" "VAT" "336" "Santa Sede" "Holy See" 209
  , CountryReferenceSeed "ST" "STP" "678" "Santo Tomé y Príncipe" "Sao Tome and Principe" 210
  , CountryReferenceSeed "SN" "SEN" "686" "Senegal" "Senegal" 211
  , CountryReferenceSeed "RS" "SRB" "688" "Serbia" "Serbia" 212
  , CountryReferenceSeed "SC" "SYC" "690" "Seychelles" "Seychelles" 213
  , CountryReferenceSeed "SL" "SLE" "694" "Sierra Leona" "Sierra Leone" 214
  , CountryReferenceSeed "SG" "SGP" "702" "Singapur" "Singapore" 215
  , CountryReferenceSeed "SO" "SOM" "706" "Somalia" "Somalia" 216
  , CountryReferenceSeed "LK" "LKA" "144" "Sri Lanka" "Sri Lanka" 217
  , CountryReferenceSeed "ZA" "ZAF" "710" "Sudáfrica" "South Africa" 218
  , CountryReferenceSeed "SD" "SDN" "729" "Sudán" "Sudan" 219
  , CountryReferenceSeed "SS" "SSD" "728" "Sudán del Sur" "South Sudan" 220
  , CountryReferenceSeed "SE" "SWE" "752" "Suecia" "Sweden" 221
  , CountryReferenceSeed "CH" "CHE" "756" "Suiza" "Switzerland" 222
  , CountryReferenceSeed "SR" "SUR" "740" "Suriname" "Suriname" 223
  , CountryReferenceSeed "EH" "ESH" "732" "Sáhara Occidental" "Western Sahara" 224
  , CountryReferenceSeed "TH" "THA" "764" "Tailandia" "Thailand" 225
  , CountryReferenceSeed "TW" "TWN" "158" "Taiwán" "Taiwan, Province of China" 226
  , CountryReferenceSeed "TJ" "TJK" "762" "Tayikistán" "Tajikistan" 227
  , CountryReferenceSeed "IO" "IOT" "086" "Territorio Británico del Océano Índico" "British Indian Ocean Territory" 228
  , CountryReferenceSeed "TF" "ATF" "260" "Territorio de las Tierras Australes Francesas" "French Southern Territories" 229
  , CountryReferenceSeed "TL" "TLS" "626" "Timor-Leste" "Timor-Leste" 230
  , CountryReferenceSeed "TG" "TGO" "768" "Togo" "Togo" 231
  , CountryReferenceSeed "TK" "TKL" "772" "Tokelau" "Tokelau" 232
  , CountryReferenceSeed "TO" "TON" "776" "Tonga" "Tonga" 233
  , CountryReferenceSeed "TT" "TTO" "780" "Trinidad y Tabago" "Trinidad and Tobago" 234
  , CountryReferenceSeed "TM" "TKM" "795" "Turkmenistán" "Turkmenistan" 235
  , CountryReferenceSeed "TV" "TUV" "798" "Tuvalu" "Tuvalu" 236
  , CountryReferenceSeed "TN" "TUN" "788" "Túnez" "Tunisia" 237
  , CountryReferenceSeed "TR" "TUR" "792" "Türkiye" "Türkiye" 238
  , CountryReferenceSeed "UA" "UKR" "804" "Ucrania" "Ukraine" 239
  , CountryReferenceSeed "UG" "UGA" "800" "Uganda" "Uganda" 240
  , CountryReferenceSeed "UY" "URY" "858" "Uruguay" "Uruguay" 241
  , CountryReferenceSeed "UZ" "UZB" "860" "Uzbekistán" "Uzbekistan" 242
  , CountryReferenceSeed "VU" "VUT" "548" "Vanuatu" "Vanuatu" 243
  , CountryReferenceSeed "VE" "VEN" "862" "Venezuela (República Bolivariana de)" "Venezuela (Bolivarian Republic of)" 244
  , CountryReferenceSeed "VN" "VNM" "704" "Viet Nam" "Viet Nam" 245
  , CountryReferenceSeed "YE" "YEM" "887" "Yemen" "Yemen" 246
  , CountryReferenceSeed "ZM" "ZMB" "894" "Zambia" "Zambia" 247
  , CountryReferenceSeed "ZW" "ZWE" "716" "Zimbabwe" "Zimbabwe" 248
  ]
