name: tdf-hq
version: 1.0.0
github: "diegueins680/tdf-app"
license: MIT
author: "TDF Records"
maintainer: "dev@tdfrecords.com"

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant
  - servant-server
  - persistent
  - persistent-postgresql
  - persistent-template
  - text
  - time
  - transformers
  - mtl
  - monad-logger
  - bytestring
  - gitrev
  - template-haskell
  - wai
  - wai-cors

library:
  source-dirs: src
  exposed-modules:
    - TDF.Models
    - TDF.API
    - TDF.DTO
    - TDF.DB
    - TDF.Server

executables:
  tdf-hq:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tdf-hq
      - warp
      - wai
      - wai-cors