name: tdf-hq
version: 1.0.0
github: "diegueins680/tdf-app"
license: MIT
author: "TDF Records"
maintainer: "dev@tdfrecords.com"

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base64-bytestring
  - bcrypt
  - bytestring
  - conduit
  - containers
  - directory
  - entropy
  - file-embed
  - filepath
  - gitrev
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - http2
  - mime-mail
  - monad-logger
  - mtl
  - path-pieces
  - persistent
  - persistent-postgresql
  - persistent-sqlite
  - persistent-template
  - postgresql-simple
  - process
  - random
  - resource-pool
  - resourcet
  - safe-exceptions
  - scientific
  - servant
  - servant-server
  - servant-multipart
  - smtp-mail
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - uuid-types
  - vector
  - wai
  - wai-cors
  - warp

extra-source-files:
  - sql/2025-11-16_leads_whatsapp.sql

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wmissing-signatures
    - -Wmissing-export-lists
  exposed-modules:
    - TDF.Models
    - TDF.API
    - TDF.DTO
    - TDF.DB
    - TDF.Server

executables:
  tdf-hq:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tdf-hq
      - warp
      - wai
      - wai-cors

tests:
  tdf-hq-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wredundant-constraints
    dependencies:
      - tdf-hq
      - hspec
