import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { checkGeneratedApi } from '../check-generated-api.mjs';

function fixture(t) {
  const root = mkdtempSync(path.join(os.tmpdir(), 'tdf-api-drift-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const git = (repo, ...args) => execFileSync('git', ['-c', 'user.name=Conformance test',
    '-c', 'user.email=conformance@example.invalid', '-c', 'commit.gpgsign=false', ...args],
  { cwd: repo, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  const mobile = path.join(root, 'tdf-mobile');
  mkdirSync(mobile);
  for (const repo of [root, mobile]) git(repo, 'init', '-q');
  const webFile = 'tdf-hq-ui/src/api/generated/types.ts';
  const mobileFile = 'src/api/generated/types.ts';
  const write = (repo, file, content) => {
    mkdirSync(path.dirname(path.join(repo, file)), { recursive: true });
    writeFileSync(path.join(repo, file), content);
  };
  for (const [repo, file] of [[mobile, mobileFile], [root, webFile]]) {
    write(repo, file, 'export interface Contract {}\n');
    git(repo, 'add', file);
    git(repo, 'commit', '-qm', 'fixture');
  }
  const revision = git(mobile, 'rev-parse', 'HEAD');
  git(root, 'update-index', '--add', '--cacheinfo', `160000,${revision},tdf-mobile`);
  git(root, 'commit', '-qm', 'pin mobile');
  return { root, mobile, webFile, mobileFile, git, write };
}

test('accepts both clean generated clients at the exact Mobile pin', t => {
  assert.equal(checkGeneratedApi(fixture(t).root).clients, 2);
});

for (const target of ['web', 'mobile']) {
  test(`rejects staged ${target} drift after regenerating the working tree`, t => {
    const f = fixture(t);
    const repo = target === 'web' ? f.root : f.mobile;
    const file = target === 'web' ? f.webFile : f.mobileFile;
    f.write(repo, file, 'export interface BrokenContract {}\n');
    f.git(repo, 'add', file);
    f.write(repo, file, f.git(repo, 'show', `HEAD:${file}`) + '\n');
    assert.throws(() => checkGeneratedApi(f.root), /Generated API drift/);
  });
  for (const staged of [false, true]) {
    test(`rejects ${staged ? 'staged' : 'unstaged'} ${target} generated drift`, t => {
      const f = fixture(t);
      const repo = target === 'web' ? f.root : f.mobile;
      const file = target === 'web' ? f.webFile : f.mobileFile;
      f.write(repo, file, 'export interface BrokenContract {}\n');
      if (staged) f.git(repo, 'add', file);
      if (target === 'mobile') {
        // Negative control: the former CI command returns success for this drift.
        assert.equal(f.git(f.root, 'diff', '--exit-code', '--', f.webFile,
          `tdf-mobile/${f.mobileFile}`), '');
      }
      assert.throws(() => checkGeneratedApi(f.root), /Generated API drift/);
    });
  }
}

test('rejects staged Mobile pin changes even with the committed checkout', t => {
  const f = fixture(t);
  const oldPin = f.git(f.mobile, 'rev-parse', 'HEAD');
  f.git(f.mobile, 'commit', '--allow-empty', '-qm', 'different revision');
  f.git(f.root, 'add', 'tdf-mobile');
  f.git(f.mobile, 'checkout', '--detach', oldPin);
  assert.throws(() => checkGeneratedApi(f.root), /Staged Mobile gitlink/);
});

test('rejects a different Mobile revision even if generated bytes agree', t => {
  const f = fixture(t);
  f.git(f.mobile, 'commit', '--allow-empty', '-qm', 'different revision');
  assert.throws(() => checkGeneratedApi(f.root), /differs from pinned/);
});

test('rejects an uninitialized Mobile checkout', t => {
  const f = fixture(t);
  rmSync(f.mobile, { recursive: true });
  mkdirSync(f.mobile);
  assert.throws(() => checkGeneratedApi(f.root), /not initialized/);
});

test('rejects a missing generated client', t => {
  const f = fixture(t);
  rmSync(path.join(f.mobile, f.mobileFile));
  assert.throws(() => checkGeneratedApi(f.root), /ENOENT/);
});
