export const COURSE_REGISTRATIONS_NAV_LABEL = 'Inscripciones de cursos';

const FRIENDLY_SEGMENTS: Record<string, string> = {
  inicio: 'Inicio',
  marketplace: 'Tienda',
  fans: 'Comunidad',
  records: 'Lanzamientos',
  'mi-profesor': 'Portal del profesor',
  crm: 'CRM',
  contactos: 'Contactos',
  empresas: 'Empresas',
  leads: 'Leads',
  estudio: 'Estudio',
  salas: 'Salas',
  ordenes: 'Órdenes',
  servicios: 'Servicios',
  pipelines: 'Pipelines',
  'live-sessions': 'Sesiones en vivo',
  reportes: 'Reportes',
  escuela: 'Escuela',
  profesores: 'Profesores',
  clases: 'Clases',
  'trial-lessons': 'Clases de prueba',
  'trial-queue': 'Solicitudes de prueba',
  label: 'Sello',
  artistas: 'Artistas',
  proyectos: 'Proyectos',
  releases: 'Lanzamientos',
  tracks: 'Pistas',
  assets: 'Activos',
  operacion: 'Operación',
  inventario: 'Inventario',
  'ordenes-marketplace': 'Órdenes tienda',
  'calendario-domo': 'Calendario domo',
  'reservas-equipo': 'Reservas equipo',
  mantenimiento: 'Mantenimiento',
  paquetes: 'Paquetes',
  configuracion: 'Configuración',
  'inscripciones-curso': COURSE_REGISTRATIONS_NAV_LABEL,
  cursos: 'Cursos',
  logs: 'Logs',
  estado: 'Estado sistema',
  'usuarios-admin': 'Usuarios admin',
  'roles-permisos': 'Roles y permisos',
  diagnosticos: 'Diagnósticos',
  'impuestos-series': 'Impuestos y series',
  'unidades-negocio': 'Unidades de negocio',
  sedes: 'Sedes',
  marcas: 'Marcas',
  integraciones: 'Integraciones',
  calendario: 'Calendario Google',
  cms: 'CMS',
  preferencias: 'Preferencias',
  finanzas: 'Finanzas',
  cotizaciones: 'Cotizaciones',
  facturas: 'Facturas',
  cobros: 'Cobros',
  pagos: 'Pagos',
  recibos: 'Recibos',
  regalias: 'Regalías',
  docs: 'Documentación',
  acerca: 'Acerca de',
  manual: 'Manual',
  seguridad: 'Seguridad',
  feedback: 'Sugerencias',
  herramientas: 'Herramientas',
  'tidal-agent': 'Agente Tidal',
  'creador-musical': 'Creador musical',
  'token-admin': 'Token API',
};

export const formatFriendlyPath = (path: string) => {
  const parts = path.split('/').filter(Boolean);
  if (parts.length === 0) return 'Inicio';
  return parts
    .map((part) => FRIENDLY_SEGMENTS[part] ?? part.replace(/-/g, ' '))
    .map((part) => (part.length > 0 ? part.charAt(0).toUpperCase() + part.slice(1) : part))
    .join(' / ');
};
