-- Generated from checked FanEffects Commit observations. Do not hand-edit.
module FanEffectsModelCases (FanCase(..), fanCases) where
-- runtime, governance, eligibility/session, source state, observed result/state
data FanCase = FanCase Bool Bool Bool Bool Bool Bool Bool Bool [Int] Int Bool Bool Bool [Int] Int
  deriving Show
fanCases :: [FanCase]
fanCases =
  [ FanCase False False False True False False False False [] 0 False False False [] 0
  , FanCase False False False True False False False False [] 1 False False False [] 1
  , FanCase False False False True False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False False False True False False False False [1,2] 1 False False False [1,2] 1
  , FanCase False False False True False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False False True False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False False False True False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False False False True False False False False [3,4] 1 False False False [3,4] 1
  , FanCase False False False True False False True False [] 0 False False False [] 0
  , FanCase False False False True False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False False False True False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False False True False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False False False True False False True True [] 0 False False True [] 0
  , FanCase False False False True False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False False False True False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False False False True False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False False False True False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False False False True False True False False [] 0 False True False [] 0
  , FanCase False False False True False True False False [] 1 False True False [] 1
  , FanCase False False False True False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False False False True False True False False [1,2] 1 False True False [1,2] 1
  , FanCase False False False True False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False False True False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False False False True False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False False False True False True False False [3,4] 1 False True False [3,4] 1
  , FanCase False False False True False True True False [] 0 False True False [] 0
  , FanCase False False False True False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False False False True False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False False True False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False False False True False True True True [] 0 False True True [] 0
  , FanCase False False False True False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False False False True False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False False False True False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False False False True False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False False False True True False False False [] 0 True True False [] 1
  , FanCase False False False True True False False False [] 1 True True False [] 2
  , FanCase False False False True True False False False [1,2] 0 True True False [1,2] 1
  , FanCase False False False True True False False False [1,2] 1 True True False [1,2] 2
  , FanCase False False False True True False False False [1,2,3,4] 0 True True False [1,2,3,4] 1
  , FanCase False False False True True False False False [1,2,3,4] 1 True True False [1,2,3,4] 2
  , FanCase False False False True True False False False [3,4] 0 True True False [3,4] 1
  , FanCase False False False True True False False False [3,4] 1 True True False [3,4] 2
  , FanCase False False False True True False True False [] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True False [1,2] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True False [1,2,3,4] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True False [3,4] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True True [] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True True [1,2] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True True [1,2,3,4] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True False True True [1,2,3,4] 1 True True True [1,2,3,4] 2
  , FanCase False False False True True False True True [3,4] 0 True True True [1,2,3,4] 1
  , FanCase False False False True True True False False [] 0 True True False [] 0
  , FanCase False False False True True True False False [] 1 True True False [] 1
  , FanCase False False False True True True False False [1,2] 0 True True False [1,2] 0
  , FanCase False False False True True True False False [1,2] 1 True True False [1,2] 1
  , FanCase False False False True True True False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False False False True True True False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase False False False True True True False False [3,4] 0 True True False [3,4] 0
  , FanCase False False False True True True False False [3,4] 1 True True False [3,4] 1
  , FanCase False False False True True True True False [] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True False [1,2] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True False [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True False [3,4] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True True [] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True True [1,2] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False False False True True True True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase False False False True True True True True [3,4] 0 True True True [1,2,3,4] 0
  , FanCase False False True False False False False False [] 0 False False False [] 0
  , FanCase False False True False False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False False True False False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False True False False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False False True False False False True False [] 0 False False False [] 0
  , FanCase False False True False False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False False True False False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False True False False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False False True False False False True True [] 0 False False True [] 0
  , FanCase False False True False False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False False True False False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False False True False False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False False True False False True False False [] 0 False True False [] 0
  , FanCase False False True False False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False False True False False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False True False False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False False True False False True True False [] 0 False True False [] 0
  , FanCase False False True False False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False False True False False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False True False False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False False True False False True True True [] 0 False True True [] 0
  , FanCase False False True False False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False False True False False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False False True False False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False False True False True False False False [] 0 False False False [] 0
  , FanCase False False True False True False False False [1,2] 0 False False False [1,2] 0
  , FanCase False False True False True False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False True False True False False False [3,4] 0 False False False [3,4] 0
  , FanCase False False True False True False True False [] 0 False False False [] 0
  , FanCase False False True False True False True False [1,2] 0 False False False [1,2] 0
  , FanCase False False True False True False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False True False True False True False [3,4] 0 False False False [3,4] 0
  , FanCase False False True False True False True True [] 0 False False True [] 0
  , FanCase False False True False True False True True [1,2] 0 False False True [1,2] 0
  , FanCase False False True False True False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False False True False True False True True [3,4] 0 False False True [3,4] 0
  , FanCase False False True False True True False False [] 0 False True False [] 0
  , FanCase False False True False True True False False [1,2] 0 False True False [1,2] 0
  , FanCase False False True False True True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False True False True True False False [3,4] 0 False True False [3,4] 0
  , FanCase False False True False True True True False [] 0 False True False [] 0
  , FanCase False False True False True True True False [1,2] 0 False True False [1,2] 0
  , FanCase False False True False True True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False True False True True True False [3,4] 0 False True False [3,4] 0
  , FanCase False False True False True True True True [] 0 False True True [] 0
  , FanCase False False True False True True True True [1,2] 0 False True True [1,2] 0
  , FanCase False False True False True True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False False True False True True True True [3,4] 0 False True True [3,4] 0
  , FanCase False False True True False False False False [] 0 False False False [] 0
  , FanCase False False True True False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False False True True False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False True True False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False False True True False False True False [] 0 False False False [] 0
  , FanCase False False True True False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False False True True False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False False True True False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False False True True False False True True [] 0 False False True [] 0
  , FanCase False False True True False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False False True True False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False False True True False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False False True True False True False False [] 0 False True False [] 0
  , FanCase False False True True False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False False True True False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False True True False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False False True True False True True False [] 0 False True False [] 0
  , FanCase False False True True False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False False True True False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False False True True False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False False True True False True True True [] 0 False True True [] 0
  , FanCase False False True True False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False False True True False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False False True True False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False False True True True False False False [] 0 True True False [] 0
  , FanCase False False True True True False False False [1,2] 0 True True False [1,2] 0
  , FanCase False False True True True False False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False False True True True False False False [3,4] 0 True True False [3,4] 0
  , FanCase False False True True True False True False [] 0 True True False [] 0
  , FanCase False False True True True False True False [1,2] 0 True True False [1,2] 0
  , FanCase False False True True True False True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False False True True True False True False [3,4] 0 True True False [3,4] 0
  , FanCase False False True True True False True True [] 0 True True True [] 0
  , FanCase False False True True True False True True [1,2] 0 True True True [1,2] 0
  , FanCase False False True True True False True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False False True True True False True True [3,4] 0 True True True [3,4] 0
  , FanCase False False True True True True False False [] 0 True True False [] 0
  , FanCase False False True True True True False False [1,2] 0 True True False [1,2] 0
  , FanCase False False True True True True False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False False True True True True False False [3,4] 0 True True False [3,4] 0
  , FanCase False False True True True True True False [] 0 True True False [] 0
  , FanCase False False True True True True True False [1,2] 0 True True False [1,2] 0
  , FanCase False False True True True True True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False False True True True True True False [3,4] 0 True True False [3,4] 0
  , FanCase False False True True True True True True [] 0 True True True [] 0
  , FanCase False False True True True True True True [1,2] 0 True True True [1,2] 0
  , FanCase False False True True True True True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False False True True True True True True [3,4] 0 True True True [3,4] 0
  , FanCase False True False False False False False False [] 0 False False False [] 0
  , FanCase False True False False False False False False [] 1 False False False [] 1
  , FanCase False True False False False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False True False False False False False False [1,2] 1 False False False [1,2] 1
  , FanCase False True False False False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True False False False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False True False False False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False True False False False False False False [3,4] 1 False False False [3,4] 1
  , FanCase False True False False False False True False [] 0 False False False [] 0
  , FanCase False True False False False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False True False False False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True False False False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False True False False False False True True [] 0 False False True [] 0
  , FanCase False True False False False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False True False False False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False True False False False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False True False False False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False True False False False True False False [] 0 False True False [] 0
  , FanCase False True False False False True False False [] 1 False True False [] 1
  , FanCase False True False False False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False True False False False True False False [1,2] 1 False True False [1,2] 1
  , FanCase False True False False False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True False False False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False True False False False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False True False False False True False False [3,4] 1 False True False [3,4] 1
  , FanCase False True False False False True True False [] 0 False True False [] 0
  , FanCase False True False False False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False True False False False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True False False False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False True False False False True True True [] 0 False True True [] 0
  , FanCase False True False False False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False True False False False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False True False False False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False True False False False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False True False False True False False False [] 0 False False False [] 0
  , FanCase False True False False True False False False [] 1 False False False [] 1
  , FanCase False True False False True False False False [1,2] 0 False False False [1,2] 0
  , FanCase False True False False True False False False [1,2] 1 False False False [1,2] 1
  , FanCase False True False False True False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True False False True False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False True False False True False False False [3,4] 0 False False False [3,4] 0
  , FanCase False True False False True False False False [3,4] 1 False False False [3,4] 1
  , FanCase False True False False True False True False [] 0 False False False [] 0
  , FanCase False True False False True False True False [1,2] 0 False False False [1,2] 0
  , FanCase False True False False True False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True False False True False True False [3,4] 0 False False False [3,4] 0
  , FanCase False True False False True False True True [] 0 False False True [] 0
  , FanCase False True False False True False True True [1,2] 0 False False True [1,2] 0
  , FanCase False True False False True False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False True False False True False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False True False False True False True True [3,4] 0 False False True [3,4] 0
  , FanCase False True False False True True False False [] 0 False True False [] 0
  , FanCase False True False False True True False False [] 1 False True False [] 1
  , FanCase False True False False True True False False [1,2] 0 False True False [1,2] 0
  , FanCase False True False False True True False False [1,2] 1 False True False [1,2] 1
  , FanCase False True False False True True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True False False True True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False True False False True True False False [3,4] 0 False True False [3,4] 0
  , FanCase False True False False True True False False [3,4] 1 False True False [3,4] 1
  , FanCase False True False False True True True False [] 0 False True False [] 0
  , FanCase False True False False True True True False [1,2] 0 False True False [1,2] 0
  , FanCase False True False False True True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True False False True True True False [3,4] 0 False True False [3,4] 0
  , FanCase False True False False True True True True [] 0 False True True [] 0
  , FanCase False True False False True True True True [1,2] 0 False True True [1,2] 0
  , FanCase False True False False True True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False True False False True True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False True False False True True True True [3,4] 0 False True True [3,4] 0
  , FanCase False True False True False False False False [] 0 False False False [] 0
  , FanCase False True False True False False False False [] 1 False False False [] 1
  , FanCase False True False True False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False True False True False False False False [1,2] 1 False False False [1,2] 1
  , FanCase False True False True False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True False True False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False True False True False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False True False True False False False False [3,4] 1 False False False [3,4] 1
  , FanCase False True False True False False True False [] 0 False False False [] 0
  , FanCase False True False True False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False True False True False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True False True False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False True False True False False True True [] 0 False False True [] 0
  , FanCase False True False True False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False True False True False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False True False True False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False True False True False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False True False True False True False False [] 0 False True False [] 0
  , FanCase False True False True False True False False [] 1 False True False [] 1
  , FanCase False True False True False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False True False True False True False False [1,2] 1 False True False [1,2] 1
  , FanCase False True False True False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True False True False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False True False True False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False True False True False True False False [3,4] 1 False True False [3,4] 1
  , FanCase False True False True False True True False [] 0 False True False [] 0
  , FanCase False True False True False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False True False True False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True False True False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False True False True False True True True [] 0 False True True [] 0
  , FanCase False True False True False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False True False True False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False True False True False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False True False True False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False True False True True False False False [] 0 True True False [] 0
  , FanCase False True False True True False False False [] 1 True True False [] 1
  , FanCase False True False True True False False False [1,2] 0 True True False [1,2] 0
  , FanCase False True False True True False False False [1,2] 1 True True False [1,2] 1
  , FanCase False True False True True False False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True False True True False False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase False True False True True False False False [3,4] 0 True True False [3,4] 0
  , FanCase False True False True True False False False [3,4] 1 True True False [3,4] 1
  , FanCase False True False True True False True False [] 0 True True False [] 0
  , FanCase False True False True True False True False [1,2] 0 True True False [1,2] 0
  , FanCase False True False True True False True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True False True True False True False [3,4] 0 True True False [3,4] 0
  , FanCase False True False True True False True True [] 0 True True True [] 0
  , FanCase False True False True True False True True [1,2] 0 True True True [1,2] 0
  , FanCase False True False True True False True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False True False True True False True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase False True False True True False True True [3,4] 0 True True True [3,4] 0
  , FanCase False True False True True True False False [] 0 True True False [] 0
  , FanCase False True False True True True False False [] 1 True True False [] 1
  , FanCase False True False True True True False False [1,2] 0 True True False [1,2] 0
  , FanCase False True False True True True False False [1,2] 1 True True False [1,2] 1
  , FanCase False True False True True True False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True False True True True False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase False True False True True True False False [3,4] 0 True True False [3,4] 0
  , FanCase False True False True True True False False [3,4] 1 True True False [3,4] 1
  , FanCase False True False True True True True False [] 0 True True False [] 0
  , FanCase False True False True True True True False [1,2] 0 True True False [1,2] 0
  , FanCase False True False True True True True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True False True True True True False [3,4] 0 True True False [3,4] 0
  , FanCase False True False True True True True True [] 0 True True True [] 0
  , FanCase False True False True True True True True [1,2] 0 True True True [1,2] 0
  , FanCase False True False True True True True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False True False True True True True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase False True False True True True True True [3,4] 0 True True True [3,4] 0
  , FanCase False True True False False False False False [] 0 False False False [] 0
  , FanCase False True True False False False False False [] 1 False False False [] 1
  , FanCase False True True False False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False True True False False False False False [1,2] 1 False False False [1,2] 1
  , FanCase False True True False False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True True False False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False True True False False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False True True False False False False False [3,4] 1 False False False [3,4] 1
  , FanCase False True True False False False True False [] 0 False False False [] 0
  , FanCase False True True False False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False True True False False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True True False False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False True True False False False True True [] 0 False False True [] 0
  , FanCase False True True False False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False True True False False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False True True False False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False True True False False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False True True False False True False False [] 0 False True False [] 0
  , FanCase False True True False False True False False [] 1 False True False [] 1
  , FanCase False True True False False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False True True False False True False False [1,2] 1 False True False [1,2] 1
  , FanCase False True True False False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True True False False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False True True False False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False True True False False True False False [3,4] 1 False True False [3,4] 1
  , FanCase False True True False False True True False [] 0 False True False [] 0
  , FanCase False True True False False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False True True False False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True True False False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False True True False False True True True [] 0 False True True [] 0
  , FanCase False True True False False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False True True False False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False True True False False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False True True False False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False True True False True False False False [] 0 False False False [] 0
  , FanCase False True True False True False False False [] 1 False False False [] 1
  , FanCase False True True False True False False False [1,2] 0 False False False [1,2] 0
  , FanCase False True True False True False False False [1,2] 1 False False False [1,2] 1
  , FanCase False True True False True False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True True False True False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False True True False True False False False [3,4] 0 False False False [3,4] 0
  , FanCase False True True False True False False False [3,4] 1 False False False [3,4] 1
  , FanCase False True True False True False True False [] 0 False False False [] 0
  , FanCase False True True False True False True False [1,2] 0 False False False [1,2] 0
  , FanCase False True True False True False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True True False True False True False [3,4] 0 False False False [3,4] 0
  , FanCase False True True False True False True True [] 0 False False True [] 0
  , FanCase False True True False True False True True [1,2] 0 False False True [1,2] 0
  , FanCase False True True False True False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False True True False True False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False True True False True False True True [3,4] 0 False False True [3,4] 0
  , FanCase False True True False True True False False [] 0 False True False [] 0
  , FanCase False True True False True True False False [] 1 False True False [] 1
  , FanCase False True True False True True False False [1,2] 0 False True False [1,2] 0
  , FanCase False True True False True True False False [1,2] 1 False True False [1,2] 1
  , FanCase False True True False True True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True True False True True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False True True False True True False False [3,4] 0 False True False [3,4] 0
  , FanCase False True True False True True False False [3,4] 1 False True False [3,4] 1
  , FanCase False True True False True True True False [] 0 False True False [] 0
  , FanCase False True True False True True True False [1,2] 0 False True False [1,2] 0
  , FanCase False True True False True True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True True False True True True False [3,4] 0 False True False [3,4] 0
  , FanCase False True True False True True True True [] 0 False True True [] 0
  , FanCase False True True False True True True True [1,2] 0 False True True [1,2] 0
  , FanCase False True True False True True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False True True False True True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False True True False True True True True [3,4] 0 False True True [3,4] 0
  , FanCase False True True True False False False False [] 0 False False False [] 0
  , FanCase False True True True False False False False [] 1 False False False [] 1
  , FanCase False True True True False False False False [1,2] 0 False False False [1,2] 0
  , FanCase False True True True False False False False [1,2] 1 False False False [1,2] 1
  , FanCase False True True True False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True True True False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase False True True True False False False False [3,4] 0 False False False [3,4] 0
  , FanCase False True True True False False False False [3,4] 1 False False False [3,4] 1
  , FanCase False True True True False False True False [] 0 False False False [] 0
  , FanCase False True True True False False True False [1,2] 0 False False False [1,2] 0
  , FanCase False True True True False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase False True True True False False True False [3,4] 0 False False False [3,4] 0
  , FanCase False True True True False False True True [] 0 False False True [] 0
  , FanCase False True True True False False True True [1,2] 0 False False True [1,2] 0
  , FanCase False True True True False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase False True True True False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase False True True True False False True True [3,4] 0 False False True [3,4] 0
  , FanCase False True True True False True False False [] 0 False True False [] 0
  , FanCase False True True True False True False False [] 1 False True False [] 1
  , FanCase False True True True False True False False [1,2] 0 False True False [1,2] 0
  , FanCase False True True True False True False False [1,2] 1 False True False [1,2] 1
  , FanCase False True True True False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True True True False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase False True True True False True False False [3,4] 0 False True False [3,4] 0
  , FanCase False True True True False True False False [3,4] 1 False True False [3,4] 1
  , FanCase False True True True False True True False [] 0 False True False [] 0
  , FanCase False True True True False True True False [1,2] 0 False True False [1,2] 0
  , FanCase False True True True False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase False True True True False True True False [3,4] 0 False True False [3,4] 0
  , FanCase False True True True False True True True [] 0 False True True [] 0
  , FanCase False True True True False True True True [1,2] 0 False True True [1,2] 0
  , FanCase False True True True False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase False True True True False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase False True True True False True True True [3,4] 0 False True True [3,4] 0
  , FanCase False True True True True False False False [] 0 True True False [] 0
  , FanCase False True True True True False False False [] 1 True True False [] 1
  , FanCase False True True True True False False False [1,2] 0 True True False [1,2] 0
  , FanCase False True True True True False False False [1,2] 1 True True False [1,2] 1
  , FanCase False True True True True False False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True True True True False False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase False True True True True False False False [3,4] 0 True True False [3,4] 0
  , FanCase False True True True True False False False [3,4] 1 True True False [3,4] 1
  , FanCase False True True True True False True False [] 0 True True False [] 0
  , FanCase False True True True True False True False [1,2] 0 True True False [1,2] 0
  , FanCase False True True True True False True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True True True True False True False [3,4] 0 True True False [3,4] 0
  , FanCase False True True True True False True True [] 0 True True True [] 0
  , FanCase False True True True True False True True [1,2] 0 True True True [1,2] 0
  , FanCase False True True True True False True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False True True True True False True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase False True True True True False True True [3,4] 0 True True True [3,4] 0
  , FanCase False True True True True True False False [] 0 True True False [] 0
  , FanCase False True True True True True False False [] 1 True True False [] 1
  , FanCase False True True True True True False False [1,2] 0 True True False [1,2] 0
  , FanCase False True True True True True False False [1,2] 1 True True False [1,2] 1
  , FanCase False True True True True True False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True True True True True False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase False True True True True True False False [3,4] 0 True True False [3,4] 0
  , FanCase False True True True True True False False [3,4] 1 True True False [3,4] 1
  , FanCase False True True True True True True False [] 0 True True False [] 0
  , FanCase False True True True True True True False [1,2] 0 True True False [1,2] 0
  , FanCase False True True True True True True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase False True True True True True True False [3,4] 0 True True False [3,4] 0
  , FanCase False True True True True True True True [] 0 True True True [] 0
  , FanCase False True True True True True True True [1,2] 0 True True True [1,2] 0
  , FanCase False True True True True True True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase False True True True True True True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase False True True True True True True True [3,4] 0 True True True [3,4] 0
  , FanCase True True False False False False False False [] 0 False False False [] 0
  , FanCase True True False False False False False False [] 1 False False False [] 1
  , FanCase True True False False False False False False [1,2] 0 False False False [1,2] 0
  , FanCase True True False False False False False False [1,2] 1 False False False [1,2] 1
  , FanCase True True False False False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True False False False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase True True False False False False False False [3,4] 0 False False False [3,4] 0
  , FanCase True True False False False False False False [3,4] 1 False False False [3,4] 1
  , FanCase True True False False False False True False [] 0 False False False [] 0
  , FanCase True True False False False False True False [1,2] 0 False False False [1,2] 0
  , FanCase True True False False False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True False False False False True False [3,4] 0 False False False [3,4] 0
  , FanCase True True False False False False True True [] 0 False False True [] 0
  , FanCase True True False False False False True True [1,2] 0 False False True [1,2] 0
  , FanCase True True False False False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase True True False False False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase True True False False False False True True [3,4] 0 False False True [3,4] 0
  , FanCase True True False False False True False False [] 0 False True False [] 0
  , FanCase True True False False False True False False [] 1 False True False [] 1
  , FanCase True True False False False True False False [1,2] 0 False True False [1,2] 0
  , FanCase True True False False False True False False [1,2] 1 False True False [1,2] 1
  , FanCase True True False False False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True False False False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase True True False False False True False False [3,4] 0 False True False [3,4] 0
  , FanCase True True False False False True False False [3,4] 1 False True False [3,4] 1
  , FanCase True True False False False True True False [] 0 False True False [] 0
  , FanCase True True False False False True True False [1,2] 0 False True False [1,2] 0
  , FanCase True True False False False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True False False False True True False [3,4] 0 False True False [3,4] 0
  , FanCase True True False False False True True True [] 0 False True True [] 0
  , FanCase True True False False False True True True [1,2] 0 False True True [1,2] 0
  , FanCase True True False False False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase True True False False False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase True True False False False True True True [3,4] 0 False True True [3,4] 0
  , FanCase True True False False True False False False [] 0 False False False [] 0
  , FanCase True True False False True False False False [] 1 False False False [] 1
  , FanCase True True False False True False False False [1,2] 0 False False False [1,2] 0
  , FanCase True True False False True False False False [1,2] 1 False False False [1,2] 1
  , FanCase True True False False True False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True False False True False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase True True False False True False False False [3,4] 0 False False False [3,4] 0
  , FanCase True True False False True False False False [3,4] 1 False False False [3,4] 1
  , FanCase True True False False True False True False [] 0 False False False [] 0
  , FanCase True True False False True False True False [1,2] 0 False False False [1,2] 0
  , FanCase True True False False True False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True False False True False True False [3,4] 0 False False False [3,4] 0
  , FanCase True True False False True False True True [] 0 False False True [] 0
  , FanCase True True False False True False True True [1,2] 0 False False True [1,2] 0
  , FanCase True True False False True False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase True True False False True False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase True True False False True False True True [3,4] 0 False False True [3,4] 0
  , FanCase True True False False True True False False [] 0 False True False [] 0
  , FanCase True True False False True True False False [] 1 False True False [] 1
  , FanCase True True False False True True False False [1,2] 0 False True False [1,2] 0
  , FanCase True True False False True True False False [1,2] 1 False True False [1,2] 1
  , FanCase True True False False True True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True False False True True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase True True False False True True False False [3,4] 0 False True False [3,4] 0
  , FanCase True True False False True True False False [3,4] 1 False True False [3,4] 1
  , FanCase True True False False True True True False [] 0 False True False [] 0
  , FanCase True True False False True True True False [1,2] 0 False True False [1,2] 0
  , FanCase True True False False True True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True False False True True True False [3,4] 0 False True False [3,4] 0
  , FanCase True True False False True True True True [] 0 False True True [] 0
  , FanCase True True False False True True True True [1,2] 0 False True True [1,2] 0
  , FanCase True True False False True True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase True True False False True True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase True True False False True True True True [3,4] 0 False True True [3,4] 0
  , FanCase True True False True False False False False [] 0 False False False [] 0
  , FanCase True True False True False False False False [] 1 False False False [] 1
  , FanCase True True False True False False False False [1,2] 0 False False False [1,2] 0
  , FanCase True True False True False False False False [1,2] 1 False False False [1,2] 1
  , FanCase True True False True False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True False True False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase True True False True False False False False [3,4] 0 False False False [3,4] 0
  , FanCase True True False True False False False False [3,4] 1 False False False [3,4] 1
  , FanCase True True False True False False True False [] 0 False False False [] 0
  , FanCase True True False True False False True False [1,2] 0 False False False [1,2] 0
  , FanCase True True False True False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True False True False False True False [3,4] 0 False False False [3,4] 0
  , FanCase True True False True False False True True [] 0 False False True [] 0
  , FanCase True True False True False False True True [1,2] 0 False False True [1,2] 0
  , FanCase True True False True False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase True True False True False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase True True False True False False True True [3,4] 0 False False True [3,4] 0
  , FanCase True True False True False True False False [] 0 False True False [] 0
  , FanCase True True False True False True False False [] 1 False True False [] 1
  , FanCase True True False True False True False False [1,2] 0 False True False [1,2] 0
  , FanCase True True False True False True False False [1,2] 1 False True False [1,2] 1
  , FanCase True True False True False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True False True False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase True True False True False True False False [3,4] 0 False True False [3,4] 0
  , FanCase True True False True False True False False [3,4] 1 False True False [3,4] 1
  , FanCase True True False True False True True False [] 0 False True False [] 0
  , FanCase True True False True False True True False [1,2] 0 False True False [1,2] 0
  , FanCase True True False True False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True False True False True True False [3,4] 0 False True False [3,4] 0
  , FanCase True True False True False True True True [] 0 False True True [] 0
  , FanCase True True False True False True True True [1,2] 0 False True True [1,2] 0
  , FanCase True True False True False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase True True False True False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase True True False True False True True True [3,4] 0 False True True [3,4] 0
  , FanCase True True False True True False False False [] 0 True True False [] 0
  , FanCase True True False True True False False False [] 1 True True False [] 1
  , FanCase True True False True True False False False [1,2] 0 True True False [1,2] 0
  , FanCase True True False True True False False False [1,2] 1 True True False [1,2] 1
  , FanCase True True False True True False False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True False True True False False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase True True False True True False False False [3,4] 0 True True False [3,4] 0
  , FanCase True True False True True False False False [3,4] 1 True True False [3,4] 1
  , FanCase True True False True True False True False [] 0 True True False [] 0
  , FanCase True True False True True False True False [1,2] 0 True True False [1,2] 0
  , FanCase True True False True True False True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True False True True False True False [3,4] 0 True True False [3,4] 0
  , FanCase True True False True True False True True [] 0 True True True [] 0
  , FanCase True True False True True False True True [1,2] 0 True True True [1,2] 0
  , FanCase True True False True True False True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase True True False True True False True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase True True False True True False True True [3,4] 0 True True True [3,4] 0
  , FanCase True True False True True True False False [] 0 True True False [] 0
  , FanCase True True False True True True False False [] 1 True True False [] 1
  , FanCase True True False True True True False False [1,2] 0 True True False [1,2] 0
  , FanCase True True False True True True False False [1,2] 1 True True False [1,2] 1
  , FanCase True True False True True True False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True False True True True False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase True True False True True True False False [3,4] 0 True True False [3,4] 0
  , FanCase True True False True True True False False [3,4] 1 True True False [3,4] 1
  , FanCase True True False True True True True False [] 0 True True False [] 0
  , FanCase True True False True True True True False [1,2] 0 True True False [1,2] 0
  , FanCase True True False True True True True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True False True True True True False [3,4] 0 True True False [3,4] 0
  , FanCase True True False True True True True True [] 0 True True True [] 0
  , FanCase True True False True True True True True [1,2] 0 True True True [1,2] 0
  , FanCase True True False True True True True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase True True False True True True True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase True True False True True True True True [3,4] 0 True True True [3,4] 0
  , FanCase True True True False False False False False [] 0 False False False [] 0
  , FanCase True True True False False False False False [] 1 False False False [] 1
  , FanCase True True True False False False False False [1,2] 0 False False False [1,2] 0
  , FanCase True True True False False False False False [1,2] 1 False False False [1,2] 1
  , FanCase True True True False False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True True False False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase True True True False False False False False [3,4] 0 False False False [3,4] 0
  , FanCase True True True False False False False False [3,4] 1 False False False [3,4] 1
  , FanCase True True True False False False True False [] 0 False False False [] 0
  , FanCase True True True False False False True False [1,2] 0 False False False [1,2] 0
  , FanCase True True True False False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True True False False False True False [3,4] 0 False False False [3,4] 0
  , FanCase True True True False False False True True [] 0 False False True [] 0
  , FanCase True True True False False False True True [1,2] 0 False False True [1,2] 0
  , FanCase True True True False False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase True True True False False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase True True True False False False True True [3,4] 0 False False True [3,4] 0
  , FanCase True True True False False True False False [] 0 False True False [] 0
  , FanCase True True True False False True False False [] 1 False True False [] 1
  , FanCase True True True False False True False False [1,2] 0 False True False [1,2] 0
  , FanCase True True True False False True False False [1,2] 1 False True False [1,2] 1
  , FanCase True True True False False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True True False False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase True True True False False True False False [3,4] 0 False True False [3,4] 0
  , FanCase True True True False False True False False [3,4] 1 False True False [3,4] 1
  , FanCase True True True False False True True False [] 0 False True False [] 0
  , FanCase True True True False False True True False [1,2] 0 False True False [1,2] 0
  , FanCase True True True False False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True True False False True True False [3,4] 0 False True False [3,4] 0
  , FanCase True True True False False True True True [] 0 False True True [] 0
  , FanCase True True True False False True True True [1,2] 0 False True True [1,2] 0
  , FanCase True True True False False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase True True True False False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase True True True False False True True True [3,4] 0 False True True [3,4] 0
  , FanCase True True True False True False False False [] 0 False False False [] 0
  , FanCase True True True False True False False False [] 1 False False False [] 1
  , FanCase True True True False True False False False [1,2] 0 False False False [1,2] 0
  , FanCase True True True False True False False False [1,2] 1 False False False [1,2] 1
  , FanCase True True True False True False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True True False True False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase True True True False True False False False [3,4] 0 False False False [3,4] 0
  , FanCase True True True False True False False False [3,4] 1 False False False [3,4] 1
  , FanCase True True True False True False True False [] 0 False False False [] 0
  , FanCase True True True False True False True False [1,2] 0 False False False [1,2] 0
  , FanCase True True True False True False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True True False True False True False [3,4] 0 False False False [3,4] 0
  , FanCase True True True False True False True True [] 0 False False True [] 0
  , FanCase True True True False True False True True [1,2] 0 False False True [1,2] 0
  , FanCase True True True False True False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase True True True False True False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase True True True False True False True True [3,4] 0 False False True [3,4] 0
  , FanCase True True True False True True False False [] 0 False True False [] 0
  , FanCase True True True False True True False False [] 1 False True False [] 1
  , FanCase True True True False True True False False [1,2] 0 False True False [1,2] 0
  , FanCase True True True False True True False False [1,2] 1 False True False [1,2] 1
  , FanCase True True True False True True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True True False True True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase True True True False True True False False [3,4] 0 False True False [3,4] 0
  , FanCase True True True False True True False False [3,4] 1 False True False [3,4] 1
  , FanCase True True True False True True True False [] 0 False True False [] 0
  , FanCase True True True False True True True False [1,2] 0 False True False [1,2] 0
  , FanCase True True True False True True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True True False True True True False [3,4] 0 False True False [3,4] 0
  , FanCase True True True False True True True True [] 0 False True True [] 0
  , FanCase True True True False True True True True [1,2] 0 False True True [1,2] 0
  , FanCase True True True False True True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase True True True False True True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase True True True False True True True True [3,4] 0 False True True [3,4] 0
  , FanCase True True True True False False False False [] 0 False False False [] 0
  , FanCase True True True True False False False False [] 1 False False False [] 1
  , FanCase True True True True False False False False [1,2] 0 False False False [1,2] 0
  , FanCase True True True True False False False False [1,2] 1 False False False [1,2] 1
  , FanCase True True True True False False False False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True True True False False False False [1,2,3,4] 1 False False False [1,2,3,4] 1
  , FanCase True True True True False False False False [3,4] 0 False False False [3,4] 0
  , FanCase True True True True False False False False [3,4] 1 False False False [3,4] 1
  , FanCase True True True True False False True False [] 0 False False False [] 0
  , FanCase True True True True False False True False [1,2] 0 False False False [1,2] 0
  , FanCase True True True True False False True False [1,2,3,4] 0 False False False [1,2,3,4] 0
  , FanCase True True True True False False True False [3,4] 0 False False False [3,4] 0
  , FanCase True True True True False False True True [] 0 False False True [] 0
  , FanCase True True True True False False True True [1,2] 0 False False True [1,2] 0
  , FanCase True True True True False False True True [1,2,3,4] 0 False False True [1,2,3,4] 0
  , FanCase True True True True False False True True [1,2,3,4] 1 False False True [1,2,3,4] 1
  , FanCase True True True True False False True True [3,4] 0 False False True [3,4] 0
  , FanCase True True True True False True False False [] 0 False True False [] 0
  , FanCase True True True True False True False False [] 1 False True False [] 1
  , FanCase True True True True False True False False [1,2] 0 False True False [1,2] 0
  , FanCase True True True True False True False False [1,2] 1 False True False [1,2] 1
  , FanCase True True True True False True False False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True True True False True False False [1,2,3,4] 1 False True False [1,2,3,4] 1
  , FanCase True True True True False True False False [3,4] 0 False True False [3,4] 0
  , FanCase True True True True False True False False [3,4] 1 False True False [3,4] 1
  , FanCase True True True True False True True False [] 0 False True False [] 0
  , FanCase True True True True False True True False [1,2] 0 False True False [1,2] 0
  , FanCase True True True True False True True False [1,2,3,4] 0 False True False [1,2,3,4] 0
  , FanCase True True True True False True True False [3,4] 0 False True False [3,4] 0
  , FanCase True True True True False True True True [] 0 False True True [] 0
  , FanCase True True True True False True True True [1,2] 0 False True True [1,2] 0
  , FanCase True True True True False True True True [1,2,3,4] 0 False True True [1,2,3,4] 0
  , FanCase True True True True False True True True [1,2,3,4] 1 False True True [1,2,3,4] 1
  , FanCase True True True True False True True True [3,4] 0 False True True [3,4] 0
  , FanCase True True True True True False False False [] 0 True True False [] 0
  , FanCase True True True True True False False False [] 1 True True False [] 1
  , FanCase True True True True True False False False [1,2] 0 True True False [1,2] 0
  , FanCase True True True True True False False False [1,2] 1 True True False [1,2] 1
  , FanCase True True True True True False False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True True True True False False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase True True True True True False False False [3,4] 0 True True False [3,4] 0
  , FanCase True True True True True False False False [3,4] 1 True True False [3,4] 1
  , FanCase True True True True True False True False [] 0 True True False [] 0
  , FanCase True True True True True False True False [1,2] 0 True True False [1,2] 0
  , FanCase True True True True True False True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True True True True False True False [3,4] 0 True True False [3,4] 0
  , FanCase True True True True True False True True [] 0 True True True [] 0
  , FanCase True True True True True False True True [1,2] 0 True True True [1,2] 0
  , FanCase True True True True True False True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase True True True True True False True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase True True True True True False True True [3,4] 0 True True True [3,4] 0
  , FanCase True True True True True True False False [] 0 True True False [] 0
  , FanCase True True True True True True False False [] 1 True True False [] 1
  , FanCase True True True True True True False False [1,2] 0 True True False [1,2] 0
  , FanCase True True True True True True False False [1,2] 1 True True False [1,2] 1
  , FanCase True True True True True True False False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True True True True True False False [1,2,3,4] 1 True True False [1,2,3,4] 1
  , FanCase True True True True True True False False [3,4] 0 True True False [3,4] 0
  , FanCase True True True True True True False False [3,4] 1 True True False [3,4] 1
  , FanCase True True True True True True True False [] 0 True True False [] 0
  , FanCase True True True True True True True False [1,2] 0 True True False [1,2] 0
  , FanCase True True True True True True True False [1,2,3,4] 0 True True False [1,2,3,4] 0
  , FanCase True True True True True True True False [3,4] 0 True True False [3,4] 0
  , FanCase True True True True True True True True [] 0 True True True [] 0
  , FanCase True True True True True True True True [1,2] 0 True True True [1,2] 0
  , FanCase True True True True True True True True [1,2,3,4] 0 True True True [1,2,3,4] 0
  , FanCase True True True True True True True True [1,2,3,4] 1 True True True [1,2,3,4] 1
  , FanCase True True True True True True True True [3,4] 0 True True True [3,4] 0
  ]
