-- Generated from TLC ConsentTraces graph; do not hand-edit.
DO $$ BEGIN
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,0);
ASSERT NOT (social_v2_mutate(3,4,'request',0,'model-1') ? 'error'), 'model action 1';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(true,false,false,false,1::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 1';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,0);
ASSERT NOT (social_v2_mutate(3,4,'block',0,'model-2') ? 'error'), 'model action 2';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,false,1::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 2';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,0);
ASSERT NOT (social_v2_mutate(4,3,'request',0,'model-3') ? 'error'), 'model action 3';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,true,false,false,1::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 3';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,0);
ASSERT NOT (social_v2_mutate(4,3,'block',0,'model-4') ? 'error'), 'model action 4';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,true,1::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 4';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,false,false,false,1);
ASSERT NOT (social_v2_mutate(3,4,'disconnect',1,'model-5') ? 'error'), 'model action 5';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 5';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,false,false,false,1);
ASSERT NOT (social_v2_mutate(3,4,'block',1,'model-6') ? 'error'), 'model action 6';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 6';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,false,false,false,1);
ASSERT NOT (social_v2_mutate(4,3,'request',1,'model-7') ? 'error'), 'model action 7';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(true,true,false,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 7';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,false,false,false,1);
ASSERT NOT (social_v2_mutate(4,3,'block',1,'model-8') ? 'error'), 'model action 8';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,true,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 8';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,true,false,1);
ASSERT NOT (social_v2_mutate(3,4,'unblock',1,'model-9') ? 'error'), 'model action 9';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 9';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,true,false,1);
ASSERT NOT (social_v2_mutate(4,3,'block',1,'model-10') ? 'error'), 'model action 10';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,true,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 10';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,true,false,false,1);
ASSERT NOT (social_v2_mutate(3,4,'request',1,'model-11') ? 'error'), 'model action 11';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(true,true,false,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 11';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,true,false,false,1);
ASSERT NOT (social_v2_mutate(3,4,'block',1,'model-12') ? 'error'), 'model action 12';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 12';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,true,false,false,1);
ASSERT NOT (social_v2_mutate(4,3,'disconnect',1,'model-13') ? 'error'), 'model action 13';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 13';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,true,false,false,1);
ASSERT NOT (social_v2_mutate(4,3,'block',1,'model-14') ? 'error'), 'model action 14';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,true,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 14';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,true,1);
ASSERT NOT (social_v2_mutate(3,4,'block',1,'model-15') ? 'error'), 'model action 15';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,true,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 15';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,true,1);
ASSERT NOT (social_v2_mutate(4,3,'unblock',1,'model-16') ? 'error'), 'model action 16';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,false,2::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 16';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,2);
ASSERT NOT (social_v2_mutate(3,4,'request',2,'model-17') ? 'error'), 'model action 17';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(true,false,false,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 17';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,2);
ASSERT NOT (social_v2_mutate(3,4,'block',2,'model-18') ? 'error'), 'model action 18';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 18';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,2);
ASSERT NOT (social_v2_mutate(4,3,'request',2,'model-19') ? 'error'), 'model action 19';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,true,false,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 19';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,false,2);
ASSERT NOT (social_v2_mutate(4,3,'block',2,'model-20') ? 'error'), 'model action 20';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,true,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 20';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,true,false,2);
ASSERT NOT (social_v2_mutate(3,4,'unblock',2,'model-21') ? 'error'), 'model action 21';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 21';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,true,false,2);
ASSERT NOT (social_v2_mutate(4,3,'block',2,'model-22') ? 'error'), 'model action 22';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,true,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 22';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,true,false,false,2);
ASSERT NOT (social_v2_mutate(3,4,'disconnect',2,'model-23') ? 'error'), 'model action 23';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,true,false,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 23';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,true,false,false,2);
ASSERT NOT (social_v2_mutate(3,4,'block',2,'model-24') ? 'error'), 'model action 24';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 24';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,true,false,false,2);
ASSERT NOT (social_v2_mutate(4,3,'disconnect',2,'model-25') ? 'error'), 'model action 25';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(true,false,false,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 25';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,true,true,false,false,2);
ASSERT NOT (social_v2_mutate(4,3,'block',2,'model-26') ? 'error'), 'model action 26';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,true,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 26';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,true,2);
ASSERT NOT (social_v2_mutate(3,4,'block',2,'model-27') ? 'error'), 'model action 27';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,true,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 27';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,false,true,2);
ASSERT NOT (social_v2_mutate(4,3,'unblock',2,'model-28') ? 'error'), 'model action 28';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 28';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,true,true,2);
ASSERT NOT (social_v2_mutate(3,4,'unblock',2,'model-29') ? 'error'), 'model action 29';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,false,true,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 29';
DELETE FROM social_v2_command WHERE actor IN (3,4);
DELETE FROM social_v2_pair WHERE party_a=3 AND party_b=4;
INSERT INTO social_v2_pair(party_a,party_b,consent_a,consent_b,block_a,block_b,revision) VALUES(3,4,false,false,true,true,2);
ASSERT NOT (social_v2_mutate(4,3,'unblock',2,'model-30') ? 'error'), 'model action 30';
ASSERT (SELECT ROW(consent_a,consent_b,block_a,block_b,revision)=ROW(false,false,true,false,3::bigint) FROM social_v2_pair WHERE party_a=3 AND party_b=4), 'model state 30';
END $$;
SELECT 'PASS: 30 TLC-generated consent transitions';
