name:                 bcrypt
version:              0.0.11
visibility:           public
id:                   bcrypt-0.0.11-f48f6bb3
key:                  bcrypt-0.0.11-f48f6bb3
license:              BSD-3-Clause
copyright:            Copyright (C) 2011 Andrew Miller
maintainer:           andrew@amxl.com
author:               Andrew Miller
stability:            experimental
synopsis:             Haskell bindings to the bcrypt password hash
description:
    Haskell bindings to the bcrypt password hash.

    Unlike other bindings already in existence, this package is designed to allow users to work directly with password hash strings that include information about the hashing algorithm, strength, and salt. This approach allows hashed passwords to be stored in a single field that can also be used by non-Haskell applications, and makes it easy to implement a policy of updating passwords hashed to an old policy next time the plaintext password is available.

    Version 1.1.3 of the OpenWall C source for bcrypt is included in this package (<http://www.openwall.com/crypt/>). The only modification is that the flag which enables the use of assembler has been disabled.
    Announcements about hs-bcrypt (including security announcements) will be sent to https://groups.google.com/forum/#!forum/hs-bcrypt-announce/join - if you use this library please consider subscribing. This mailing list is moderated and is expected to have a very low volume of mail traffic.

category:             Data, Cryptography
abi:                  c1f9dae2eb0c667eba33773f94f0f617
exposed:              True
exposed-modules:      Crypto.BCrypt
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/bcrypt-0.0.11-f48f6bb3/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/bcrypt-0.0.11-f48f6bb3/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/bcrypt-0.0.11-f48f6bb3/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/bcrypt-0.0.11-f48f6bb3/share

hs-libraries:         HSbcrypt-0.0.11-f48f6bb3
depends:
    base-4.17.2.1 bytestring-0.11.5.3 dt-dflt-0.8.0.2-7fb53fa0
    ntrpy-0.4.1.11-b04ee622 mmry-0.18.0-e767045c

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/bcrypt-0.0.11-f48f6bb3/share/doc/html/bcrypt.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/bcrypt-0.0.11-f48f6bb3/share/doc/html
