name:                 crypton-asn1-parse
version:              0.10.0
visibility:           public
id:                   cryptn-sn1-prs-0.10.0-01a1d7eb
key:                  cryptn-sn1-prs-0.10.0-01a1d7eb
license:              BSD-3-Clause
copyright:            Vincent Hanquez <vincent@snarc.org>
maintainer:
    Mike Pilgrem <public@pilgrem.com>,
    Kazu Yamamoto <kazu@iij.ad.jp>

author:               Vincent Hanquez <vincent@snarc.org>
stability:            experimental
homepage:             https://github.com/mpilgrem/crypton-asn1
synopsis:             A monadic parser combinator for a ASN.1 stream.
description:
    A library providing a monadic parser combinator for use with a stream of
    Abstract Syntax Notation One (ASN.1) standard values.

category:             Data
abi:                  a4bc172b3a3db5e72e38683190d0f4de
exposed:              True
exposed-modules:
    Data.ASN1.Parse,
    Data.ASN1.Types from cryptn-sn1-typs-0.4.1-48c1c377:Data.ASN1.Types

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-sn1-prs-0.10.0-01a1d7eb/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-sn1-prs-0.10.0-01a1d7eb/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-sn1-prs-0.10.0-01a1d7eb/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-sn1-prs-0.10.0-01a1d7eb/share

hs-libraries:         HScryptn-sn1-prs-0.10.0-01a1d7eb
depends:
    base-4.17.2.1 bytestring-0.11.5.3 cryptn-sn1-typs-0.4.1-48c1c377

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-sn1-prs-0.10.0-01a1d7eb/share/doc/html/crypton-asn1-parse.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-sn1-prs-0.10.0-01a1d7eb/share/doc/html
