name:                 crypton-pem
version:              0.3.0
visibility:           public
id:                   cryptn-pm-0.3.0-31c07f16
key:                  cryptn-pm-0.3.0-31c07f16
license:              BSD-3-Clause
copyright:            Vincent Hanquez <vincent@snarc.org>
maintainer:
    Mike Pilgrem <public@pilgrem.com>,
    Kazu Yamamoto <kazu@iij.ad.jp>

author:               Vincent Hanquez <vincent@snarc.org>
stability:            experimental
homepage:             http://github.com/mpilgrem/crypton-pem
synopsis:             Privacy Enhanced Mail (PEM) file format reader and writer.
description:
    A library to read and write files in the Privacy Enhanced Mail (PEM) format.

category:             Data
abi:                  3e007f1afba0603a03d9766ba42fc8cf
exposed:              True
exposed-modules:      Data.PEM
hidden-modules:       Data.PEM.Parser Data.PEM.Types Data.PEM.Writer
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-pm-0.3.0-31c07f16/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-pm-0.3.0-31c07f16/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-pm-0.3.0-31c07f16/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-pm-0.3.0-31c07f16/share

hs-libraries:         HScryptn-pm-0.3.0-31c07f16
depends:
    base-4.17.2.1 bs64-1.0-3bc0fba9 bytestring-0.11.5.3 deepseq-1.4.8.0
    text-2.0.2

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-pm-0.3.0-31c07f16/share/doc/html/crypton-pem.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/cryptn-pm-0.3.0-31c07f16/share/doc/html
