name:                 fast-logger
version:              3.2.6
visibility:           public
id:                   fst-lggr-3.2.6-2d7b1df2
key:                  fst-lggr-3.2.6-2d7b1df2
license:              BSD-3-Clause
maintainer:           Kazu Yamamoto <kazu@iij.ad.jp>
author:               Kazu Yamamoto <kazu@iij.ad.jp>
homepage:             https://github.com/kazu-yamamoto/logger
synopsis:             A fast logging system
description:          A fast logging system for Haskell
category:             System
abi:                  14c11c494e61d328659e35c869926ca9
exposed:              True
exposed-modules:
    System.Log.FastLogger System.Log.FastLogger.Date
    System.Log.FastLogger.File System.Log.FastLogger.Internal
    System.Log.FastLogger.LoggerSet System.Log.FastLogger.Types

hidden-modules:
    System.Log.FastLogger.Imports System.Log.FastLogger.FileIO
    System.Log.FastLogger.IO System.Log.FastLogger.LogStr
    System.Log.FastLogger.MultiLogger
    System.Log.FastLogger.SingleLogger System.Log.FastLogger.Write

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/fst-lggr-3.2.6-2d7b1df2/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/fst-lggr-3.2.6-2d7b1df2/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/fst-lggr-3.2.6-2d7b1df2/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/fst-lggr-3.2.6-2d7b1df2/share

hs-libraries:         HSfst-lggr-3.2.6-2d7b1df2
depends:
    array-0.5.4.0 t-pdt-0.2.6-fee1ad2d base-4.17.2.1
    bytestring-0.11.5.3 directory-1.3.7.1 sy-fl-0.2.5-73fa829d
    filepath-1.4.2.2 stm-2.5.1.0 text-2.0.2 nx-cmpt-0.7.4.1-7cc809f6
    nx-tm-0.4.17-2c3fdda4

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/fst-lggr-3.2.6-2d7b1df2/share/doc/html/fast-logger.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/fst-lggr-3.2.6-2d7b1df2/share/doc/html
