name:                 hspec-expectations
version:              0.8.4
visibility:           public
id:                   hspc-xpcttns-0.8.4-cf6a95a2
key:                  hspc-xpcttns-0.8.4-cf6a95a2
license:              MIT
copyright:            (c) 2011-2023 Simon Hengel
maintainer:           Simon Hengel <sol@typeful.net>
author:               Simon Hengel <sol@typeful.net>
homepage:             https://github.com/hspec/hspec-expectations#readme
synopsis:             Catchy combinators for HUnit
description:
    Catchy combinators for HUnit: <https://github.com/hspec/hspec-expectations#readme>

category:             Testing
abi:                  f6f9eead998de1e4b55ad2806b161691
exposed:              True
exposed-modules:
    Test.Hspec.Expectations Test.Hspec.Expectations.Contrib

hidden-modules:
    Test.Hspec.Expectations.Matcher Paths_hspec_expectations

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/hspc-xpcttns-0.8.4-cf6a95a2/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/hspc-xpcttns-0.8.4-cf6a95a2/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/hspc-xpcttns-0.8.4-cf6a95a2/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/hspc-xpcttns-0.8.4-cf6a95a2/share

hs-libraries:         HShspc-xpcttns-0.8.4-cf6a95a2
depends:
    HUnt-1.6.2.0-c38e4d65 base-4.17.2.1 cll-stck-0.4.0-31c5656b

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/hspc-xpcttns-0.8.4-cf6a95a2/share/doc/html/hspec-expectations.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/hspc-xpcttns-0.8.4-cf6a95a2/share/doc/html
