name:                 http-api-data
version:              0.6.3
visibility:           public
id:                   http-p-dt-0.6.3-9f22ee0f
key:                  http-p-dt-0.6.3-9f22ee0f
license:              BSD-3-Clause
maintainer:           Nickolay Kudasov <nickolay.kudasov@gmail.com>
author:               Nickolay Kudasov <nickolay.kudasov@gmail.com>
stability:            unstable
homepage:             http://github.com/fizruk/http-api-data
synopsis:
    Converting to/from HTTP API data like URL pieces, headers and query parameters.

description:
    This package defines typeclasses used for converting Haskell data types to and from HTTP API data.

    Please see README.md

category:             Web
abi:                  5194de33110bb74e76c310c42343d3db
exposed:              True
exposed-modules:
    Web.FormUrlEncoded Web.HttpApiData Web.Internal.FormUrlEncoded
    Web.Internal.HttpApiData

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/http-p-dt-0.6.3-9f22ee0f/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/http-p-dt-0.6.3-9f22ee0f/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/http-p-dt-0.6.3-9f22ee0f/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/http-p-dt-0.6.3-9f22ee0f/share

hs-libraries:         HShttp-p-dt-0.6.3-9f22ee0f
depends:
    base-4.17.2.1 bytestring-0.11.5.3 containers-0.6.7
    ck-0.5.1-a3929a6b hshbl-1.4.7.0-aee9b33f http-typs-0.12.4-7e184036
    tggd-0.8.10-632f416a text-2.0.2 txt-s8601-0.1.1-91af75e3
    tm-cmpt-1.9.8-611e216d nrdrd-cntnrs-0.2.21-a93a7ffd
    d-typs-1.0.6-948bb3eb

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/http-p-dt-0.6.3-9f22ee0f/share/doc/html/http-api-data.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/http-p-dt-0.6.3-9f22ee0f/share/doc/html
