name:                 HUnit
version:              1.6.2.0
visibility:           public
id:                   HUnt-1.6.2.0-c38e4d65
key:                  HUnt-1.6.2.0-c38e4d65
license:              BSD-3-Clause
maintainer:           Simon Hengel <sol@typeful.net>
author:               Dean Herington
stability:            stable
homepage:             https://github.com/hspec/HUnit#readme
synopsis:             A unit testing framework for Haskell
description:
    HUnit is a unit testing framework for Haskell, inspired by the
    JUnit tool for Java, see: <http://www.junit.org>.

category:             Testing
abi:                  0077a272365e8b85cd45c5034dc11096
exposed:              True
exposed-modules:
    Test.HUnit Test.HUnit.Base Test.HUnit.Lang Test.HUnit.Terminal
    Test.HUnit.Text

hidden-modules:       Paths_HUnit
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/HUnt-1.6.2.0-c38e4d65/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/HUnt-1.6.2.0-c38e4d65/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/HUnt-1.6.2.0-c38e4d65/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/HUnt-1.6.2.0-c38e4d65/share

hs-libraries:         HSHUnt-1.6.2.0-c38e4d65
depends:              base-4.17.2.1 cll-stck-0.4.0-31c5656b deepseq-1.4.8.0
haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/HUnt-1.6.2.0-c38e4d65/share/doc/html/HUnit.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/HUnt-1.6.2.0-c38e4d65/share/doc/html
