name:                 kan-extensions
version:              5.2.8
visibility:           public
id:                   kn-xtnsns-5.2.8-d5d37fa6
key:                  kn-xtnsns-5.2.8-d5d37fa6
license:              BSD-3-Clause
copyright:            Copyright (C) 2008-2016 Edward A. Kmett
maintainer:           Edward A. Kmett <ekmett@gmail.com>
author:               Edward A. Kmett
stability:            provisional
homepage:             http://github.com/ekmett/kan-extensions/
synopsis:
    Kan extensions, Kan lifts, the Yoneda lemma, and (co)density (co)monads

description:
    Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads.

category:             Data Structures, Monads, Comonads, Functors
abi:                  fde0b78ed91b95f4cf9c05b330068043
exposed:              True
exposed-modules:
    Control.Comonad.Density Control.Monad.Co Control.Monad.Codensity
    Data.Functor.Contravariant.Coyoneda Data.Functor.Contravariant.Day
    Data.Functor.Contravariant.Yoneda Data.Functor.Coyoneda
    Data.Functor.Day Data.Functor.Day.Curried
    Data.Functor.Invariant.Day Data.Functor.Kan.Lan
    Data.Functor.Kan.Ran Data.Functor.Yoneda

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/kn-xtnsns-5.2.8-d5d37fa6/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/kn-xtnsns-5.2.8-d5d37fa6/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/kn-xtnsns-5.2.8-d5d37fa6/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/kn-xtnsns-5.2.8-d5d37fa6/share

hs-libraries:         HSkn-xtnsns-5.2.8-d5d37fa6
depends:
    djnctns-4.4.4-a1d58197 base-4.17.2.1 cmnd-5.0.10-640722d8
    cntrvrnt-1.5.6-8e0d0196 dstrbtv-0.6.3-7dee684b exceptions-0.10.5
    fr-5.2-12689e69 nvrnt-0.6.5-e159635d mtl-2.2.2
    prfnctrs-5.6.3-4895d642 smgrpds-6.0.2-4bc20059 transformers-0.5.6.2

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/kn-xtnsns-5.2.8-d5d37fa6/share/doc/html/kan-extensions.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/kn-xtnsns-5.2.8-d5d37fa6/share/doc/html
