name:                 lifted-base
version:              0.2.3.12
visibility:           public
id:                   lftd-bs-0.2.3.12-dbb10c19
key:                  lftd-bs-0.2.3.12-dbb10c19
license:              BSD-3-Clause
copyright:            (c) 2011-2012 Bas van Dijk, Anders Kaseorg
maintainer:           Bas van Dijk <v.dijk.bas@gmail.com>
author:               Bas van Dijk, Anders Kaseorg
homepage:             https://github.com/basvandijk/lifted-base
synopsis:             lifted IO operations from the base library
description:
    @lifted-base@ exports IO operations from the base library lifted to
    any instance of 'MonadBase' or 'MonadBaseControl'.

    Note that not all modules from @base@ are converted yet. If
    you need a lifted version of a function from @base@, just
    ask me to add it or send me a patch.

    The package includes a copy of the @monad-peel@ testsuite written
    by Anders Kaseorg The tests can be performed using @cabal test@.

category:             Control
abi:                  a23778192da5c0fa295345f5cfce17fa
exposed:              True
exposed-modules:
    Control.Concurrent.Chan.Lifted Control.Concurrent.Lifted
    Control.Concurrent.MVar.Lifted Control.Concurrent.QSem.Lifted
    Control.Concurrent.QSemN.Lifted Control.Exception.Lifted
    Data.IORef.Lifted Foreign.Marshal.Utils.Lifted
    System.Timeout.Lifted

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lftd-bs-0.2.3.12-dbb10c19/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lftd-bs-0.2.3.12-dbb10c19/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lftd-bs-0.2.3.12-dbb10c19/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lftd-bs-0.2.3.12-dbb10c19/share

hs-libraries:         HSlftd-bs-0.2.3.12-dbb10c19
includes:             inlinable.h
depends:
    base-4.17.2.1 mnd-cntrl-1.0.3.1-ad11ff08
    trnsfrmrs-bs-0.4.6-e2e2be60

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lftd-bs-0.2.3.12-dbb10c19/share/doc/html/lifted-base.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lftd-bs-0.2.3.12-dbb10c19/share/doc/html
