name:                 monad-control
version:              1.0.3.1
visibility:           public
id:                   mnd-cntrl-1.0.3.1-ad11ff08
key:                  mnd-cntrl-1.0.3.1-ad11ff08
license:              BSD-3-Clause
copyright:            (c) 2011 Bas van Dijk, Anders Kaseorg
maintainer:
    Oleg Grenrus <oleg.grenrus@iki.fi>, Bas van Dijk <v.dijk.bas@gmail.com>

author:               Bas van Dijk, Anders Kaseorg
homepage:             https://github.com/basvandijk/monad-control
synopsis:
    Lift control operations, like exception catching, through monad transformers

description:
    This package defines the type class @MonadBaseControl@, a subset of
    @MonadBase@ into which generic control operations such as @catch@ can be
    lifted from @IO@ or any other base monad. Instances are based on monad
    transformers in @MonadTransControl@, which includes all standard monad
    transformers in the @transformers@ library except @ContT@.

    See the <http://hackage.haskell.org/package/lifted-base lifted-base>
    package which uses @monad-control@ to lift @IO@
    operations from the @base@ library (like @catch@ or @bracket@) into any monad
    that is an instance of @MonadBase@ or @MonadBaseControl@.

    Note that this package is a rewrite of Anders Kaseorg's @monad-peel@
    library. The main difference is that this package provides CPS style operators
    and exploits the @RankNTypes@ and @TypeFamilies@ language extensions to
    simplify and speedup most definitions.

category:             Control
abi:                  1685fdb4b8ba8d6de9a621efdeb72588
exposed:              True
exposed-modules:      Control.Monad.Trans.Control
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-cntrl-1.0.3.1-ad11ff08/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-cntrl-1.0.3.1-ad11ff08/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-cntrl-1.0.3.1-ad11ff08/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-cntrl-1.0.3.1-ad11ff08/share

hs-libraries:         HSmnd-cntrl-1.0.3.1-ad11ff08
depends:
    base-4.17.2.1 stm-2.5.1.0 transformers-0.5.6.2
    trnsfrmrs-bs-0.4.6-e2e2be60 trnsfrmrs-cmpt-0.7.2-8a6d2e60

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-cntrl-1.0.3.1-ad11ff08/share/doc/html/monad-control.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-cntrl-1.0.3.1-ad11ff08/share/doc/html
