name:                 monad-loops
version:              0.4.3
visibility:           public
id:                   mnd-lps-0.4.3-3b19afdd
key:                  mnd-lps-0.4.3-3b19afdd
license:              LicenseRef-PublicDomain
maintainer:           James Cook <mokus@deepbondi.net>
author:               James Cook <mokus@deepbondi.net>
stability:            provisional
homepage:             https://github.com/mokus0/monad-loops
synopsis:             Monadic loops
description:
    Some useful control operators for looping.

    New in 0.4: STM loop operators have been split into a
    new package instead of being conditionally-built.

    New in 0.3.2.0: various functions for traversing lists and
    computing minima/maxima using arbitrary procedures to compare
    or score the elements.

category:             Control
abi:                  613ab89c4852a733e5fb621a1fed6e3a
exposed:              True
exposed-modules:      Control.Monad.Loops
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-lps-0.4.3-3b19afdd/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-lps-0.4.3-3b19afdd/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-lps-0.4.3-3b19afdd/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-lps-0.4.3-3b19afdd/share

hs-libraries:         HSmnd-lps-0.4.3-3b19afdd
depends:              base-4.17.2.1
haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-lps-0.4.3-3b19afdd/share/doc/html/monad-loops.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/mnd-lps-0.4.3-3b19afdd/share/doc/html
