name:                 parallel
version:              3.3.0.0
visibility:           public
id:                   prlll-3.3.0.0-9ebaba93
key:                  prlll-3.3.0.0-9ebaba93
license:              BSD-3-Clause
maintainer:           libraries@haskell.org
synopsis:             Parallel programming library
description:
    This package provides a library for parallel programming.

    For documentation, start from the "Control.Parallel.Strategies"
    module below.

    For more tutorial documentation, see the book <https://simonmar.github.io/pages/pcph.html Parallel and Concurrent Programming in Haskell>.

    To understand the principles behind the library, see
    <https://simonmar.github.io/bib/papers/strategies.pdf Seq no more: Better Strategies for Parallel Haskell>.

category:             Control, Parallelism
abi:                  f45d31a329cb636261ec8d5fb361fbbd
exposed:              True
exposed-modules:
    Control.Parallel Control.Parallel.Strategies Control.Seq

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prlll-3.3.0.0-9ebaba93/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prlll-3.3.0.0-9ebaba93/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prlll-3.3.0.0-9ebaba93/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prlll-3.3.0.0-9ebaba93/share

hs-libraries:         HSprlll-3.3.0.0-9ebaba93
depends:
    array-0.5.4.0 base-4.17.2.1 containers-0.6.7 deepseq-1.4.8.0

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prlll-3.3.0.0-9ebaba93/share/doc/html/parallel.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prlll-3.3.0.0-9ebaba93/share/doc/html
