name:               persistent-template
version:            2.12.0.0
visibility:         public
id:                 prsstnt-tmplt-2.12.0.0-edf1cd4b
key:                prsstnt-tmplt-2.12.0.0-edf1cd4b
license:            MIT
maintainer:
    Michael Snoyman <michael@snoyman.com>, Greg Weber <greg@gregweber.info>

author:             Michael Snoyman <michael@snoyman.com>
stability:          Stable
homepage:           http://www.yesodweb.com/book/persistent
synopsis:           Type-safe, non-relational, multi-backend persistence.
description:
    Hackage documentation generation is not reliable. For up to date documentation, please see: <http://www.stackage.org/package/persistent-template>.

category:           Database, Yesod
abi:                12d776480acf79c658d9432f8261bf55
exposed:            True
data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prsstnt-tmplt-2.12.0.0-edf1cd4b/share

depends:            base-4.17.2.1
haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prsstnt-tmplt-2.12.0.0-edf1cd4b/share/doc/html/persistent-template.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/prsstnt-tmplt-2.12.0.0-edf1cd4b/share/doc/html
