name:                 quickcheck-io
version:              0.2.0
visibility:           public
id:                   qckchck--0.2.0-1afdddd1
key:                  qckchck--0.2.0-1afdddd1
license:              MIT
copyright:            (c) 2013-2017 Simon Hengel
maintainer:           Simon Hengel <sol@typeful.net>
author:               Simon Hengel <sol@typeful.net>
homepage:             https://github.com/hspec/quickcheck-io#readme
synopsis:             Use HUnit assertions as QuickCheck properties
description:
    This package provides an orphan instance that allows you to
    use HUnit assertions as QuickCheck properties.

category:             Testing
abi:                  1a931c302e7f4d02fa937283c5382b7d
exposed:              True
exposed-modules:      Test.QuickCheck.IO
hidden-modules:       Paths_quickcheck_io
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/qckchck--0.2.0-1afdddd1/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/qckchck--0.2.0-1afdddd1/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/qckchck--0.2.0-1afdddd1/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/qckchck--0.2.0-1afdddd1/share

hs-libraries:         HSqckchck--0.2.0-1afdddd1
depends:
    HUnt-1.6.2.0-c38e4d65 QckChck-2.16.0.0-2a5db76a base-4.17.2.1

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/qckchck--0.2.0-1afdddd1/share/doc/html/quickcheck-io.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/qckchck--0.2.0-1afdddd1/share/doc/html
