name:                 servant-multipart-api
version:              0.12.1
visibility:           public
id:                   srvnt-mltprt-p-0.12.1-f6d73c7d
key:                  srvnt-mltprt-p-0.12.1-f6d73c7d
license:              BSD-3-Clause
copyright:
    2016-2017 Alp Mestanogullari, 2018-2019 Servant Contributors

maintainer:           alpmestan@gmail.com
author:               Alp Mestanogullari
homepage:             https://github.com/haskell-servant/servant-multipart#readme
synopsis:             multipart/form-data (e.g file upload) support for servant
description:
    This package contains servant API types that support multiform upload, used by
    servant-multipart and servant-multipart-client for backend/client implementation.

category:             Web, Servant
abi:                  299d1d05daa6d53523fe82a1368e8d2c
exposed:              True
exposed-modules:      Servant.Multipart.API
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/srvnt-mltprt-p-0.12.1-f6d73c7d/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/srvnt-mltprt-p-0.12.1-f6d73c7d/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/srvnt-mltprt-p-0.12.1-f6d73c7d/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/srvnt-mltprt-p-0.12.1-f6d73c7d/share

hs-libraries:         HSsrvnt-mltprt-p-0.12.1-f6d73c7d
depends:
    base-4.17.2.1 bytestring-0.11.5.3 srvnt-0.20.3.0-b498cd20
    text-2.0.2 transformers-0.5.6.2

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/srvnt-mltprt-p-0.12.1-f6d73c7d/share/doc/html/servant-multipart-api.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/srvnt-mltprt-p-0.12.1-f6d73c7d/share/doc/html
