name:                 stm-chans
version:              3.0.0.9
visibility:           public
id:                   stm-chns-3.0.0.9-c98b64a2
key:                  stm-chns-3.0.0.9-c98b64a2
license:              BSD-3-Clause
copyright:            2011–2023 wren romano
maintainer:           wren@cpan.org
author:               wren gayle romano, Thomas DuBuisson
stability:            provisional
homepage:             https://wrengr.org/software/hackage.html
synopsis:             Additional types of channels for STM.
description:          Additional types of channels for STM.
category:             Concurrency
abi:                  96606f0683ff5ee35c01acf7062f96bd
exposed:              True
exposed-modules:
    Control.Concurrent.STM.TBChan Control.Concurrent.STM.TBMChan
    Control.Concurrent.STM.TBMQueue Control.Concurrent.STM.TMChan
    Control.Concurrent.STM.TMQueue

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/stm-chns-3.0.0.9-c98b64a2/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/stm-chns-3.0.0.9-c98b64a2/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/stm-chns-3.0.0.9-c98b64a2/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/stm-chns-3.0.0.9-c98b64a2/share

hs-libraries:         HSstm-chns-3.0.0.9-c98b64a2
depends:              base-4.17.2.1 stm-2.5.1.0
haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/stm-chns-3.0.0.9-c98b64a2/share/doc/html/stm-chans.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/stm-chns-3.0.0.9-c98b64a2/share/doc/html
