name:                 transformers-compat
version:              0.7.2
visibility:           public
id:                   trnsfrmrs-cmpt-0.7.2-8a6d2e60
key:                  trnsfrmrs-cmpt-0.7.2-8a6d2e60
license:              BSD-3-Clause
copyright:            Copyright (C) 2012-2015 Edward A. Kmett
maintainer:           Edward A. Kmett <ekmett@gmail.com>
author:               Edward A. Kmett
stability:            provisional
homepage:             http://github.com/ekmett/transformers-compat/
synopsis:             A small compatibility shim for the transformers library
description:
    This package includes backported versions of types that were added
    to transformers in transformers 0.3, 0.4, and 0.5 for users who need strict
    transformers 0.2 or 0.3 compatibility to run on old versions of the
    platform, but also need those types.

    Those users should be able to just depend on @transformers >= 0.2@
    and @transformers-compat >= 0.3@.

    Note: missing methods are not supplied, but this at least permits the types to be used.

category:             Compatibility
abi:                  a8653cc3d8deadb730ef0d658ccb53a6
exposed:              True
exposed-modules:
    Control.Monad.Trans.Instances Data.Functor.Classes.Generic
    Data.Functor.Classes.Generic.Internal

hidden-modules:       Paths_transformers_compat
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/trnsfrmrs-cmpt-0.7.2-8a6d2e60/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/trnsfrmrs-cmpt-0.7.2-8a6d2e60/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/trnsfrmrs-cmpt-0.7.2-8a6d2e60/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/trnsfrmrs-cmpt-0.7.2-8a6d2e60/share

hs-libraries:         HStrnsfrmrs-cmpt-0.7.2-8a6d2e60
depends:              base-4.17.2.1 ghc-prim-0.9.1 transformers-0.5.6.2
haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/trnsfrmrs-cmpt-0.7.2-8a6d2e60/share/doc/html/transformers-compat.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/trnsfrmrs-cmpt-0.7.2-8a6d2e60/share/doc/html
