name:                 attoparsec-aeson
version:              2.2.2.0
visibility:           public
id:                   ttprsc-sn-2.2.2.0-c9d74ee1
key:                  ttprsc-sn-2.2.2.0-c9d74ee1
license:              BSD-3-Clause
copyright:
    (c) 2011-2016 Bryan O'Sullivan
    (c) 2011 MailRank, Inc.

maintainer:           Oleg Grenrus <oleg.grenrus@iki.fi>
author:               Bryan O'Sullivan <bos@serpentine.com>
stability:            experimental
homepage:             https://github.com/haskell/aeson
synopsis:             Parsing of aeson's Value with attoparsec
description:
    Parsing of aeson's Value with attoparsec, originally from aeson.

category:             Parsing
abi:                  0051881a7628c71ca30696f18c557ff6
exposed:              True
exposed-modules:      Data.Aeson.Parser Data.Aeson.Parser.Internal
hidden-modules:
    Data.Aeson.Internal.ByteString Data.Aeson.Internal.Text

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/ttprsc-sn-2.2.2.0-c9d74ee1/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/ttprsc-sn-2.2.2.0-c9d74ee1/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/ttprsc-sn-2.2.2.0-c9d74ee1/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/ttprsc-sn-2.2.2.0-c9d74ee1/share

hs-libraries:         HSttprsc-sn-2.2.2.0-c9d74ee1
depends:
    sn-2.2.3.0-eed95da1 ttprsc-0.14.4-7021719c base-4.17.2.1
    bytestring-0.11.5.3 chrctr-ps-0.1-efb6e8b9
    ntgr-cnvrsn-0.1.1-54863df5 prmtv-0.9.1.0-20c46843
    scntfc-0.3.8.1-8b1b5acf text-2.0.2 vctr-0.13.2.0-0fc0d17a

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/ttprsc-sn-2.2.2.0-c9d74ee1/share/doc/html/attoparsec-aeson.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/ttprsc-sn-2.2.2.0-c9d74ee1/share/doc/html
