name:                 vector-algorithms
version:              0.9.1.0
visibility:           public
id:                   vctr-lgrthms-0.9.1.0-28b80c0c
key:                  vctr-lgrthms-0.9.1.0-28b80c0c
license:              BSD-3-Clause
copyright:
    (c) 2008,2009,2010,2011,2012,2013,2014,2015 Dan Doel
    (c) 2015 Tim Baumann

maintainer:
    Dan Doel <dan.doel@gmail.com>
    Erik de Castro Lopo <erikd@mega-nerd.com>

author:               Dan Doel
homepage:             https://github.com/erikd/vector-algorithms/
synopsis:             Efficient algorithms for vector arrays
description:
    Efficient algorithms for sorting vector arrays. At some stage
    other vector algorithms may be added.

category:             Data
abi:                  620ee156d499f670073ef4f6e84b9a35
exposed:              True
exposed-modules:
    Data.Vector.Algorithms Data.Vector.Algorithms.AmericanFlag
    Data.Vector.Algorithms.Heap Data.Vector.Algorithms.Insertion
    Data.Vector.Algorithms.Intro Data.Vector.Algorithms.Merge
    Data.Vector.Algorithms.Optimal Data.Vector.Algorithms.Radix
    Data.Vector.Algorithms.Search Data.Vector.Algorithms.Tim

hidden-modules:       Data.Vector.Algorithms.Common
import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/share

hs-libraries:         HSvctr-lgrthms-0.9.1.0-28b80c0c
include-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/lib//include

depends:
    base-4.17.2.1 btvc-1.1.5.0-319759d2 bytestring-0.11.5.3
    prmtv-0.9.1.0-20c46843 vctr-0.13.2.0-0fc0d17a

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/share/doc/html/vector-algorithms.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/vctr-lgrthms-0.9.1.0-28b80c0c/share/doc/html
