name:                 wai-logger
version:              2.5.0
visibility:           public
id:                   w-lggr-2.5.0-a37e07c3
key:                  w-lggr-2.5.0-a37e07c3
license:              BSD-3-Clause
maintainer:           Kazu Yamamoto <kazu@iij.ad.jp>
author:               Kazu Yamamoto <kazu@iij.ad.jp>
synopsis:             A logging system for WAI
description:          A logging system for WAI(Web Application Interface)
category:             Web, Yesod
abi:                  374697a6469de1109e73c5a294a1594d
exposed:              True
exposed-modules:      Network.Wai.Logger
hidden-modules:
    Network.Wai.Logger.Apache Network.Wai.Logger.IP
    Network.Wai.Logger.IORef

import-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/w-lggr-2.5.0-a37e07c3/lib

library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/w-lggr-2.5.0-a37e07c3/lib

library-dirs-static:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/w-lggr-2.5.0-a37e07c3/lib

dynamic-library-dirs:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/lib

data-dir:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/w-lggr-2.5.0-a37e07c3/share

hs-libraries:         HSw-lggr-2.5.0-a37e07c3
depends:
    base-4.17.2.1 bytrdr-1.0.4-cc470617 bytestring-0.11.5.3
    fst-lggr-3.2.6-2d7b1df2 http-typs-0.12.4-7e184036
    ntwrk-3.2.8.0-948adf32 w-3.2.4-d80ca33f

haddock-interfaces:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/w-lggr-2.5.0-a37e07c3/share/doc/html/wai-logger.haddock

haddock-html:
    /Users/diegosaa/GitHub/tdf-app/tdf-hq/.cabal/store/ghc-9.4.8/w-lggr-2.5.0-a37e07c3/share/doc/html
