-- Explicit opt-in; no historical policy or order changes its commercial basis.
BEGIN;
ALTER TABLE event_ticket_checkout_policy ADD COLUMN IF NOT EXISTS tax_included BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE event_ticket_checkout_runtime ADD COLUMN IF NOT EXISTS tax_included BOOLEAN NOT NULL DEFAULT FALSE;

-- Replace only the two original additive amount constraints, regardless of the
-- autogenerated names assigned by PostgreSQL. Keep all identity/payment guards.
DO $$ DECLARE c RECORD;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint
    WHERE conrelid='event_ticket_checkout_runtime'::regclass AND contype='c'
      AND pg_get_constraintdef(oid) IN (
        'CHECK ((checkout_total_minor = ((net_face_value_minor + buyer_fee_minor) + tax_minor)))',
        'CHECK ((organizer_payable_minor = (net_face_value_minor - organizer_fee_minor)))')
  LOOP EXECUTE format('ALTER TABLE event_ticket_checkout_runtime DROP CONSTRAINT %I',c.conname); END LOOP;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='event_ticket_checkout_runtime'::regclass AND conname='ticket_tax_mode_total') THEN
    ALTER TABLE event_ticket_checkout_runtime ADD CONSTRAINT ticket_tax_mode_total CHECK (
      checkout_total_minor::numeric = net_face_value_minor::numeric + buyer_fee_minor + CASE WHEN tax_included THEN 0 ELSE tax_minor END);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='event_ticket_checkout_runtime'::regclass AND conname='ticket_tax_mode_payable') THEN
    ALTER TABLE event_ticket_checkout_runtime ADD CONSTRAINT ticket_tax_mode_payable CHECK (
      organizer_payable_minor::numeric = net_face_value_minor::numeric - organizer_fee_minor - CASE WHEN tax_included THEN tax_minor ELSE 0 END);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='event_ticket_checkout_runtime'::regclass AND conname='ticket_included_tax_arithmetic') THEN
    ALTER TABLE event_ticket_checkout_runtime ADD CONSTRAINT ticket_included_tax_arithmetic CHECK (
      NOT tax_included OR (
        tax_minor = round((net_face_value_minor::numeric + buyer_fee_minor) * tax_bps / (10000 + tax_bps))
        AND buyer_fee_minor = round(net_face_value_minor::numeric * buyer_fee_bps / 10000)
        AND organizer_fee_minor = round(net_face_value_minor::numeric * organizer_fee_bps / 10000)));
  END IF;
END $$;

-- Published policy immutability already covers every field via to_jsonb.
-- Independently bind the new runtime field; an old writer cannot silently apply
-- additive tax to a policy whose advertised prices include it.
CREATE OR REPLACE FUNCTION event_ticket_checkout_tax_mode_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE policy_tax_included BOOLEAN;
BEGIN
  IF TG_OP='UPDATE' THEN
    IF NEW.tax_included IS DISTINCT FROM OLD.tax_included THEN
      RAISE EXCEPTION 'Purchased ticket tax mode is immutable' USING ERRCODE='23514';
    END IF;
  ELSE
    SELECT tax_included INTO policy_tax_included FROM event_ticket_checkout_policy WHERE id=NEW.policy_id FOR SHARE;
    IF policy_tax_included IS NULL OR NEW.tax_included IS DISTINCT FROM policy_tax_included THEN
      RAISE EXCEPTION 'Ticket tax mode must match the approved policy' USING ERRCODE='23514';
    END IF;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_event_ticket_checkout_tax_mode ON event_ticket_checkout_runtime;
CREATE TRIGGER trg_event_ticket_checkout_tax_mode BEFORE INSERT OR UPDATE ON event_ticket_checkout_runtime
FOR EACH ROW EXECUTE FUNCTION event_ticket_checkout_tax_mode_guard();

-- Preserve original history bytes and authors; annotate the legacy default.
LOCK TABLE event_ticket_checkout_policy_history IN SHARE ROW EXCLUSIVE MODE;
INSERT INTO event_ticket_checkout_policy_history(policy_id,event_id,policy_version,snapshot,changed_by)
SELECT h.policy_id,h.event_id,h.policy_version,
 h.snapshot || jsonb_build_object('tax_included',false,'tax_mode_origin_history_id',h.id,'tax_mode_origin_changed_at',h.changed_at),
 'migration:2026-10-05_ticket_inclusive_tax'
FROM event_ticket_checkout_policy_history h
WHERE NOT (h.snapshot ? 'tax_included') AND NOT EXISTS (
 SELECT 1 FROM event_ticket_checkout_policy_history c
 WHERE c.changed_by='migration:2026-10-05_ticket_inclusive_tax' AND c.snapshot->>'tax_mode_origin_history_id'=h.id::text);
COMMIT;
