-- Normalize the equivalent constraint name generated by older Persistent
-- schemas without changing the checksum of the applied base migration.
BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '10min';

DO $compatibility$
DECLARE
    canonical_exists BOOLEAN;
    legacy_exists BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
        WHERE conrelid = 'public.ticket_qr_code'::regclass
          AND conname = 'unique_ticket_qr_code'
          AND contype = 'u'
    ) INTO canonical_exists;

    SELECT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
        WHERE conrelid = 'public.ticket_qr_code'::regclass
          AND conname = 'unique_ticket_q_r_code'
          AND contype = 'u'
    ) INTO legacy_exists;

    IF canonical_exists AND legacy_exists THEN
        ALTER TABLE public.ticket_qr_code
            DROP CONSTRAINT unique_ticket_q_r_code;
    ELSIF NOT canonical_exists AND legacy_exists THEN
        ALTER TABLE public.ticket_qr_code
            RENAME CONSTRAINT unique_ticket_q_r_code TO unique_ticket_qr_code;
    ELSIF NOT canonical_exists THEN
        RAISE EXCEPTION 'ticket_qr_code is missing its ticket uniqueness constraint';
    END IF;
END
$compatibility$;

COMMIT;
