-- Generated from the four Persistent catalog migrations in
-- TDF.Catalog.Models, then wrapped with a fail-closed idempotency gate.
\set ON_ERROR_STOP on

BEGIN;
SET LOCAL statement_timeout = '15min';
SET LOCAL lock_timeout = '2s';
SELECT pg_advisory_xact_lock(hashtextextended('tdf-catalog-canonical-schema-v1', 0));
SELECT to_regclass('public.catalog_definition') IS NULL AS apply_catalog_canonical_schema \gset
\if :apply_catalog_canonical_schema

CREATe TABLE "workflow_definition"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sensitive" BOOLEAN NOT NULL DEFAULT False,"public_read" BOOLEAN NOT NULL DEFAULT False,"cache_revision" INT8 NOT NULL DEFAULT 1,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "workflow_definition" ADD CONSTRAINT "unique_workflow_definition_code" UNIQUE("code");
CREATe TABLE "workflow_state"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"workflow_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"terminal" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "workflow_state" ADD CONSTRAINT "unique_workflow_state_code" UNIQUE("workflow_id","code");
ALTER TABLE "workflow_state" ADD CONSTRAINT "workflow_state_workflow_id_fkey" FOREIGN KEY("workflow_id") REFERENCES "workflow_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "workflow_transition"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"workflow_id" uuid NOT NULL,"from_state_id" uuid NOT NULL,"to_state_id" uuid NOT NULL,"required_permission_id" uuid NULL,"requires_review" BOOLEAN NOT NULL DEFAULT False,"requires_distinct_approver" BOOLEAN NOT NULL DEFAULT False,"effective_from" TIMESTAMP WITH TIME ZONE NULL,"effective_until" TIMESTAMP WITH TIME ZONE NULL,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" INT8 NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "workflow_transition" ADD CONSTRAINT "unique_workflow_transition" UNIQUE("workflow_id","from_state_id","to_state_id");
ALTER TABLE "workflow_transition" ADD CONSTRAINT "workflow_transition_workflow_id_fkey" FOREIGN KEY("workflow_id") REFERENCES "workflow_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "workflow_transition" ADD CONSTRAINT "workflow_transition_from_state_id_fkey" FOREIGN KEY("from_state_id") REFERENCES "workflow_state"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "workflow_transition" ADD CONSTRAINT "workflow_transition_to_state_id_fkey" FOREIGN KEY("to_state_id") REFERENCES "workflow_state"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "workflow_default_state"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"workflow_id" uuid NOT NULL,"state_id" uuid NOT NULL,"context" VARCHAR NOT NULL DEFAULT 'initial',"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "workflow_default_state" ADD CONSTRAINT "workflow_default_state_workflow_id_fkey" FOREIGN KEY("workflow_id") REFERENCES "workflow_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "workflow_default_state" ADD CONSTRAINT "workflow_default_state_state_id_fkey" FOREIGN KEY("state_id") REFERENCES "workflow_state"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "workflow_state_capability"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"state_id" uuid NOT NULL,"capability_code" VARCHAR NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "workflow_state_capability" ADD CONSTRAINT "unique_workflow_state_capability" UNIQUE("state_id","capability_code");
ALTER TABLE "workflow_state_capability" ADD CONSTRAINT "workflow_state_capability_state_id_fkey" FOREIGN KEY("state_id") REFERENCES "workflow_state"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_definition"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"classification" VARCHAR NOT NULL,"entity_kind" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"public_read" BOOLEAN NOT NULL DEFAULT False,"sensitive" BOOLEAN NOT NULL DEFAULT False,"ordering_mode" VARCHAR NOT NULL DEFAULT 'manual',"workflow_id" uuid NOT NULL,"source_name" VARCHAR NULL,"source_version" VARCHAR NULL,"source_effective_date" DATE NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NULL,"cache_revision" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "catalog_definition" ADD CONSTRAINT "unique_catalog_definition_code" UNIQUE("code");
ALTER TABLE "catalog_definition" ADD CONSTRAINT "unique_catalog_definition_entity_kind" UNIQUE("entity_kind");
ALTER TABLE "catalog_definition" ADD CONSTRAINT "catalog_definition_workflow_id_fkey" FOREIGN KEY("workflow_id") REFERENCES "workflow_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_revision"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"entity_id" uuid NOT NULL,"workflow_state_id" uuid NOT NULL,"base_version" INT8 NOT NULL,"proposed_version" INT8 NOT NULL,"previous_values" VARCHAR NULL,"new_values" VARCHAR NOT NULL,"created_by" INT8 NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"submitted_at" TIMESTAMP WITH TIME ZONE NULL,"reviewed_by" INT8 NULL,"reviewed_at" TIMESTAMP WITH TIME ZONE NULL,"approved_by" INT8 NULL,"approved_at" TIMESTAMP WITH TIME ZONE NULL,"reviewer_notes" VARCHAR NULL,"rejection_reason" VARCHAR NULL,"scheduled_publish_at" TIMESTAMP WITH TIME ZONE NULL,"published_at" TIMESTAMP WITH TIME ZONE NULL,"source_platform" VARCHAR NOT NULL,"correlation_id" VARCHAR NOT NULL,"reason" VARCHAR NULL,"result" VARCHAR NULL,"import_job_id" uuid NULL);
ALTER TABLE "catalog_revision" ADD CONSTRAINT "unique_catalog_entity_revision" UNIQUE("catalog_id","entity_id","proposed_version");
ALTER TABLE "catalog_revision" ADD CONSTRAINT "catalog_revision_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "catalog_revision" ADD CONSTRAINT "catalog_revision_workflow_state_id_fkey" FOREIGN KEY("workflow_state_id") REFERENCES "workflow_state"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_audit_event"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"entity_id" uuid NOT NULL,"revision_id" uuid NULL,"operation" VARCHAR NOT NULL,"previous_values" VARCHAR NULL,"new_values" VARCHAR NULL,"actor_id" INT8 NULL,"reviewer_id" INT8 NULL,"approver_id" INT8 NULL,"occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"source_platform" VARCHAR NOT NULL,"import_job_id" uuid NULL,"reason" VARCHAR NULL,"correlation_id" VARCHAR NOT NULL,"result" VARCHAR NOT NULL,"affected_relationships" VARCHAR NULL);
ALTER TABLE "catalog_audit_event" ADD CONSTRAINT "catalog_audit_event_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "catalog_audit_event" ADD CONSTRAINT "catalog_audit_event_revision_id_fkey" FOREIGN KEY("revision_id") REFERENCES "catalog_revision"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_import_job"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"source_name" VARCHAR NOT NULL,"source_version" VARCHAR NOT NULL DEFAULT '',"original_filename" VARCHAR NULL,"content_sha256" VARCHAR NOT NULL,"dry_run" BOOLEAN NOT NULL DEFAULT True,"status" VARCHAR NOT NULL,"total_rows" INT8 NOT NULL DEFAULT 0,"accepted_rows" INT8 NOT NULL DEFAULT 0,"rejected_rows" INT8 NOT NULL DEFAULT 0,"ambiguous_rows" INT8 NOT NULL DEFAULT 0,"error_report" VARCHAR NULL,"requested_by" INT8 NOT NULL,"reviewed_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"completed_at" TIMESTAMP WITH TIME ZONE NULL,"correlation_id" VARCHAR NOT NULL);
ALTER TABLE "catalog_import_job" ADD CONSTRAINT "unique_catalog_import_digest" UNIQUE("catalog_id","content_sha256","source_version");
ALTER TABLE "catalog_import_job" ADD CONSTRAINT "catalog_import_job_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_import_review_entry"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"import_job_id" uuid NOT NULL,"source_row" INT8 NOT NULL,"original_value" VARCHAR NOT NULL,"candidate_matches" VARCHAR NOT NULL,"status" VARCHAR NOT NULL,"resolution" VARCHAR NULL,"resolved_by" INT8 NULL,"resolved_at" TIMESTAMP WITH TIME ZONE NULL,"evidence" VARCHAR NULL);
ALTER TABLE "catalog_import_review_entry" ADD CONSTRAINT "unique_catalog_import_review_row" UNIQUE("import_job_id","source_row");
ALTER TABLE "catalog_import_review_entry" ADD CONSTRAINT "catalog_import_review_entry_import_job_id_fkey" FOREIGN KEY("import_job_id") REFERENCES "catalog_import_job"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_backfill_run"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"run_code" VARCHAR NOT NULL,"candidate_revision" VARCHAR NOT NULL,"dry_run" BOOLEAN NOT NULL DEFAULT True,"status" VARCHAR NOT NULL,"safety_threshold" INT8 NOT NULL DEFAULT 0,"scanned_rows" INT8 NOT NULL DEFAULT 0,"mapped_rows" INT8 NOT NULL DEFAULT 0,"ambiguous_rows" INT8 NOT NULL DEFAULT 0,"rejected_rows" INT8 NOT NULL DEFAULT 0,"started_by" INT8 NULL,"started_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"completed_at" TIMESTAMP WITH TIME ZONE NULL,"report" VARCHAR NULL,"correlation_id" VARCHAR NOT NULL);
ALTER TABLE "catalog_backfill_run" ADD CONSTRAINT "unique_catalog_backfill_run" UNIQUE("run_code","candidate_revision","dry_run");
CREATe TABLE "catalog_migration_mapping"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"run_id" uuid NOT NULL,"source_table" VARCHAR NOT NULL,"source_column" VARCHAR NOT NULL,"source_record_id" VARCHAR NOT NULL DEFAULT '',"original_value" VARCHAR NOT NULL,"normalized_value" VARCHAR NOT NULL,"catalog_id" uuid NOT NULL,"entity_id" uuid NULL,"status" VARCHAR NOT NULL,"evidence" VARCHAR NULL,"source_count" INT8 NOT NULL DEFAULT 0,"reviewed_by" INT8 NULL,"resolved_at" TIMESTAMP WITH TIME ZONE NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "catalog_migration_mapping" ADD CONSTRAINT "unique_catalog_migration_source" UNIQUE("run_id","source_table","source_column","source_record_id","original_value");
ALTER TABLE "catalog_migration_mapping" ADD CONSTRAINT "catalog_migration_mapping_run_id_fkey" FOREIGN KEY("run_id") REFERENCES "catalog_backfill_run"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "catalog_migration_mapping" ADD CONSTRAINT "catalog_migration_mapping_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "workflow_migration_mapping"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"run_id" uuid NOT NULL,"workflow_id" uuid NOT NULL,"source_table" VARCHAR NOT NULL,"source_column" VARCHAR NOT NULL,"source_record_id" VARCHAR NOT NULL DEFAULT '',"original_value" VARCHAR NOT NULL,"normalized_value" VARCHAR NOT NULL,"state_id" uuid NULL,"status" VARCHAR NOT NULL,"evidence" VARCHAR NULL,"source_count" INT8 NOT NULL DEFAULT 0,"reviewed_by" INT8 NULL,"resolved_at" TIMESTAMP WITH TIME ZONE NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "workflow_migration_mapping" ADD CONSTRAINT "unique_workflow_migration_source" UNIQUE("run_id","source_table","source_column","source_record_id","original_value");
ALTER TABLE "workflow_migration_mapping" ADD CONSTRAINT "workflow_migration_mapping_run_id_fkey" FOREIGN KEY("run_id") REFERENCES "catalog_backfill_run"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "workflow_migration_mapping" ADD CONSTRAINT "workflow_migration_mapping_workflow_id_fkey" FOREIGN KEY("workflow_id") REFERENCES "workflow_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "workflow_migration_mapping" ADD CONSTRAINT "workflow_migration_mapping_state_id_fkey" FOREIGN KEY("state_id") REFERENCES "workflow_state"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_slug_alias"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"entity_kind" VARCHAR NOT NULL,"entity_id" uuid NOT NULL,"scope" VARCHAR NOT NULL,"slug" VARCHAR NOT NULL,"current" BOOLEAN NOT NULL DEFAULT False,"redirect_status" INT8 NOT NULL DEFAULT 308,"created_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"retired_at" TIMESTAMP WITH TIME ZONE NULL);
ALTER TABLE "catalog_slug_alias" ADD CONSTRAINT "unique_catalog_slug_scope" UNIQUE("scope","slug");
ALTER TABLE "catalog_slug_alias" ADD CONSTRAINT "catalog_slug_alias_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_search_alias"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"entity_kind" VARCHAR NOT NULL,"entity_id" uuid NOT NULL,"locale_id" uuid NOT NULL,"term" VARCHAR NOT NULL,"normalized_term" VARCHAR NOT NULL,"source" VARCHAR NOT NULL DEFAULT 'manual',"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "catalog_search_alias" ADD CONSTRAINT "unique_catalog_search_alias" UNIQUE("catalog_id","entity_id","locale_id","normalized_term");
ALTER TABLE "catalog_search_alias" ADD CONSTRAINT "catalog_search_alias_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_scoped_default"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"entity_id" uuid NOT NULL,"scope_kind" VARCHAR NOT NULL,"scope_id" VARCHAR NOT NULL,"locale_id" uuid NULL,"effective_from" TIMESTAMP WITH TIME ZONE NULL,"effective_until" TIMESTAMP WITH TIME ZONE NULL,"active" BOOLEAN NOT NULL DEFAULT True,"created_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "catalog_scoped_default" ADD CONSTRAINT "catalog_scoped_default_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_dependency_rule"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"subject_entity_id" uuid NOT NULL,"predicate_kind" VARCHAR NOT NULL,"related_catalog_id" uuid NULL,"related_entity_id" uuid NULL,"context_kind" VARCHAR NOT NULL,"context_id" VARCHAR NULL,"effective_from" TIMESTAMP WITH TIME ZONE NULL,"effective_until" TIMESTAMP WITH TIME ZONE NULL,"priority" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"created_by" INT8 NOT NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "catalog_dependency_rule" ADD CONSTRAINT "catalog_dependency_rule_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "catalog_dependency_rule" ADD CONSTRAINT "catalog_dependency_rule_related_catalog_id_fkey" FOREIGN KEY("related_catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_merge_operation"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"source_entity_id" uuid NOT NULL,"target_entity_id" uuid NOT NULL,"status" VARCHAR NOT NULL,"reason" VARCHAR NOT NULL,"affected_references" VARCHAR NULL,"requested_by" INT8 NOT NULL,"approved_by" INT8 NULL,"executed_at" TIMESTAMP WITH TIME ZONE NULL,"reversed_at" TIMESTAMP WITH TIME ZONE NULL,"reversed_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"correlation_id" VARCHAR NOT NULL);
ALTER TABLE "catalog_merge_operation" ADD CONSTRAINT "catalog_merge_operation_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "catalog_usage_daily"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"entity_id" uuid NULL,"day" DATE NOT NULL,"selection_count" INT8 NOT NULL DEFAULT 0,"historical_reference_count" INT8 NOT NULL DEFAULT 0,"replacement_count" INT8 NOT NULL DEFAULT 0,"no_result_search_count" INT8 NOT NULL DEFAULT 0,"form_failure_count" INT8 NOT NULL DEFAULT 0);
ALTER TABLE "catalog_usage_daily" ADD CONSTRAINT "unique_catalog_usage_day" UNIQUE("catalog_id","entity_id","day");
ALTER TABLE "catalog_usage_daily" ADD CONSTRAINT "catalog_usage_daily_catalog_id_fkey" FOREIGN KEY("catalog_id") REFERENCES "catalog_definition"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "security_module"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"internal_only" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "security_module" ADD CONSTRAINT "unique_security_module_code" UNIQUE("code");
CREATe TABLE "security_action"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sensitive" BOOLEAN NOT NULL DEFAULT False,"grantable" BOOLEAN NOT NULL DEFAULT True,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "security_action" ADD CONSTRAINT "unique_security_action_code" UNIQUE("code");
CREATe TABLE "security_permission"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"module_id" uuid NOT NULL,"action_id" uuid NOT NULL,"resource_scope" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sensitive" BOOLEAN NOT NULL DEFAULT False,"public_metadata" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "security_permission" ADD CONSTRAINT "unique_security_permission_code" UNIQUE("code");
ALTER TABLE "security_permission" ADD CONSTRAINT "unique_security_permission_tuple" UNIQUE("module_id","action_id","resource_scope");
ALTER TABLE "security_permission" ADD CONSTRAINT "security_permission_module_id_fkey" FOREIGN KEY("module_id") REFERENCES "security_module"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "security_permission" ADD CONSTRAINT "security_permission_action_id_fkey" FOREIGN KEY("action_id") REFERENCES "security_action"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "security_role"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"system_role" BOOLEAN NOT NULL DEFAULT False,"emergency_administrator" BOOLEAN NOT NULL DEFAULT False,"self_assignable" BOOLEAN NOT NULL DEFAULT False,"automatic_assignable" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"published_revision" INT8 NOT NULL DEFAULT 1,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "security_role" ADD CONSTRAINT "unique_security_role_code" UNIQUE("code");
CREATe TABLE "security_role_assignment_policy"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"trigger_code" VARCHAR NOT NULL,"role_id" uuid NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"requires_verified_email" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"effective_from" TIMESTAMP WITH TIME ZONE NULL,"effective_to" TIMESTAMP WITH TIME ZONE NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "security_role_assignment_policy" ADD CONSTRAINT "unique_security_role_assignment_policy_code" UNIQUE("code");
ALTER TABLE "security_role_assignment_policy" ADD CONSTRAINT "unique_security_role_assignment_policy_trigger_role" UNIQUE("trigger_code","role_id");
ALTER TABLE "security_role_assignment_policy" ADD CONSTRAINT "security_role_assignment_policy_role_id_fkey" FOREIGN KEY("role_id") REFERENCES "security_role"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "security_grant_revision"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"change_kind" VARCHAR NOT NULL,"party_id" INT8 NULL,"role_id" uuid NOT NULL,"permission_id" uuid NULL,"desired_active" BOOLEAN NOT NULL,"expected_version" INT8 NOT NULL,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"submitted_at" TIMESTAMP WITH TIME ZONE NULL,"reviewed_by" INT8 NULL,"reviewed_at" TIMESTAMP WITH TIME ZONE NULL,"approved_by" INT8 NULL,"approved_at" TIMESTAMP WITH TIME ZONE NULL,"reviewer_notes" VARCHAR NULL,"rejection_reason" VARCHAR NULL,"approval_mode" VARCHAR NOT NULL DEFAULT 'normal',"emergency_reason" VARCHAR NULL,"source_platform" VARCHAR NOT NULL,"correlation_id" VARCHAR NOT NULL,"reason" VARCHAR NOT NULL,"result" VARCHAR NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "security_grant_revision" ADD CONSTRAINT "unique_security_grant_correlation" UNIQUE("correlation_id");
ALTER TABLE "security_grant_revision" ADD CONSTRAINT "security_grant_revision_role_id_fkey" FOREIGN KEY("role_id") REFERENCES "security_role"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "security_grant_revision" ADD CONSTRAINT "security_grant_revision_permission_id_fkey" FOREIGN KEY("permission_id") REFERENCES "security_permission"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "role_permission"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"role_id" uuid NOT NULL,"permission_id" uuid NOT NULL,"granted_by" INT8 NULL,"approved_by" INT8 NULL,"approval_mode" VARCHAR NOT NULL DEFAULT 'bootstrap',"emergency_reason" VARCHAR NULL,"source_revision_id" uuid NULL,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"revoked_at" TIMESTAMP WITH TIME ZONE NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "role_permission" ADD CONSTRAINT "unique_role_permission" UNIQUE("role_id","permission_id");
ALTER TABLE "role_permission" ADD CONSTRAINT "role_permission_role_id_fkey" FOREIGN KEY("role_id") REFERENCES "security_role"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "role_permission" ADD CONSTRAINT "role_permission_permission_id_fkey" FOREIGN KEY("permission_id") REFERENCES "security_permission"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "role_permission" ADD CONSTRAINT "role_permission_source_revision_id_fkey" FOREIGN KEY("source_revision_id") REFERENCES "security_grant_revision"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "party_security_role"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"party_id" INT8 NOT NULL,"role_id" uuid NOT NULL,"granted_by" INT8 NULL,"approved_by" INT8 NULL,"approval_mode" VARCHAR NOT NULL DEFAULT 'bootstrap',"emergency_reason" VARCHAR NULL,"source_revision_id" uuid NULL,"source_policy_id" uuid NULL,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"revoked_at" TIMESTAMP WITH TIME ZONE NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "party_security_role" ADD CONSTRAINT "unique_party_security_role" UNIQUE("party_id","role_id");
ALTER TABLE "party_security_role" ADD CONSTRAINT "party_security_role_role_id_fkey" FOREIGN KEY("role_id") REFERENCES "security_role"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "party_security_role" ADD CONSTRAINT "party_security_role_source_revision_id_fkey" FOREIGN KEY("source_revision_id") REFERENCES "security_grant_revision"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "party_security_role" ADD CONSTRAINT "party_security_role_source_policy_id_fkey" FOREIGN KEY("source_policy_id") REFERENCES "security_role_assignment_policy"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "security_audit_event"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"revision_id" uuid NULL,"source_policy_id" uuid NULL,"entity_kind" VARCHAR NOT NULL,"party_id" INT8 NULL,"role_id" uuid NOT NULL,"permission_id" uuid NULL,"operation" VARCHAR NOT NULL,"previous_active" BOOLEAN NULL,"new_active" BOOLEAN NULL,"actor_id" INT8 NULL,"reviewer_id" INT8 NULL,"approver_id" INT8 NULL,"occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"source_platform" VARCHAR NOT NULL,"reason" VARCHAR NULL,"correlation_id" VARCHAR NOT NULL,"approval_mode" VARCHAR NOT NULL,"result" VARCHAR NOT NULL);
ALTER TABLE "security_audit_event" ADD CONSTRAINT "security_audit_event_revision_id_fkey" FOREIGN KEY("revision_id") REFERENCES "security_grant_revision"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "security_audit_event" ADD CONSTRAINT "security_audit_event_source_policy_id_fkey" FOREIGN KEY("source_policy_id") REFERENCES "security_role_assignment_policy"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "security_audit_event" ADD CONSTRAINT "security_audit_event_role_id_fkey" FOREIGN KEY("role_id") REFERENCES "security_role"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "security_audit_event" ADD CONSTRAINT "security_audit_event_permission_id_fkey" FOREIGN KEY("permission_id") REFERENCES "security_permission"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "country_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"alpha2" VARCHAR NOT NULL,"alpha3" VARCHAR NOT NULL,"numeric_code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"standard" VARCHAR NOT NULL DEFAULT 'ISO 3166-1',"source_version" VARCHAR NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "country_reference" ADD CONSTRAINT "unique_country_reference_alpha2" UNIQUE("alpha2");
ALTER TABLE "country_reference" ADD CONSTRAINT "unique_country_reference_alpha3" UNIQUE("alpha3");
ALTER TABLE "country_reference" ADD CONSTRAINT "unique_country_reference_numeric" UNIQUE("numeric_code");
ALTER TABLE "country_reference" ADD CONSTRAINT "country_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "country_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "subdivision_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"country_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"subdivision_type" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"source_version" VARCHAR NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "subdivision_reference" ADD CONSTRAINT "unique_subdivision_reference_code" UNIQUE("country_id","code");
ALTER TABLE "subdivision_reference" ADD CONSTRAINT "subdivision_reference_country_id_fkey" FOREIGN KEY("country_id") REFERENCES "country_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "subdivision_reference" ADD CONSTRAINT "subdivision_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "subdivision_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "city_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"country_id" uuid NOT NULL,"subdivision_id" uuid NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"timezone" VARCHAR NULL,"latitude" DOUBLE PRECISION NULL,"longitude" DOUBLE PRECISION NULL,"source_name" VARCHAR NOT NULL,"source_version" VARCHAR NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "city_reference" ADD CONSTRAINT "unique_city_reference_code" UNIQUE("country_id","code");
ALTER TABLE "city_reference" ADD CONSTRAINT "city_reference_country_id_fkey" FOREIGN KEY("country_id") REFERENCES "country_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "city_reference" ADD CONSTRAINT "city_reference_subdivision_id_fkey" FOREIGN KEY("subdivision_id") REFERENCES "subdivision_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "city_reference" ADD CONSTRAINT "city_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "city_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "currency_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"numeric_code" VARCHAR NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"symbol" VARCHAR NOT NULL,"minor_units" INT8 NOT NULL,"standard" VARCHAR NOT NULL DEFAULT 'ISO 4217',"source_version" VARCHAR NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "currency_reference" ADD CONSTRAINT "unique_currency_reference_code" UNIQUE("code");
ALTER TABLE "currency_reference" ADD CONSTRAINT "currency_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "currency_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "tax_rate_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"rate_bps" INT8 NOT NULL,"country_id" uuid NULL,"standard" VARCHAR NOT NULL,"source_version" VARCHAR NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "tax_rate_reference" ADD CONSTRAINT "unique_tax_rate_reference_code" UNIQUE("code");
ALTER TABLE "tax_rate_reference" ADD CONSTRAINT "tax_rate_reference_country_id_fkey" FOREIGN KEY("country_id") REFERENCES "country_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "tax_rate_reference" ADD CONSTRAINT "tax_rate_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "tax_rate_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "language_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"iso6391" VARCHAR NULL,"iso6392_t" VARCHAR NOT NULL,"iso6392_b" VARCHAR NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"standard" VARCHAR NOT NULL DEFAULT 'ISO 639',"source_version" VARCHAR NOT NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "language_reference" ADD CONSTRAINT "unique_language_reference6391" UNIQUE("iso6391");
ALTER TABLE "language_reference" ADD CONSTRAINT "unique_language_reference6392_t" UNIQUE("iso6392_t");
ALTER TABLE "language_reference" ADD CONSTRAINT "language_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "language_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "locale_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"language_id" uuid NOT NULL,"country_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"fallback_locale_id" uuid NULL,"default_for_platform" BOOLEAN NOT NULL DEFAULT False,"source_version" VARCHAR NOT NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "locale_reference" ADD CONSTRAINT "unique_locale_reference_code" UNIQUE("code");
ALTER TABLE "locale_reference" ADD CONSTRAINT "locale_reference_language_id_fkey" FOREIGN KEY("language_id") REFERENCES "language_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "locale_reference" ADD CONSTRAINT "locale_reference_country_id_fkey" FOREIGN KEY("country_id") REFERENCES "country_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "locale_reference" ADD CONSTRAINT "locale_reference_fallback_locale_id_fkey" FOREIGN KEY("fallback_locale_id") REFERENCES "locale_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "locale_reference" ADD CONSTRAINT "locale_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "locale_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "deployment_currency_enablement"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"deployment_code" VARCHAR NOT NULL,"currency_id" uuid NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT True,"default_currency" BOOLEAN NOT NULL DEFAULT False,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "deployment_currency_enablement" ADD CONSTRAINT "unique_deployment_currency" UNIQUE("deployment_code","currency_id");
ALTER TABLE "deployment_currency_enablement" ADD CONSTRAINT "deployment_currency_enablement_currency_id_fkey" FOREIGN KEY("currency_id") REFERENCES "currency_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "deployment_locale_enablement"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"deployment_code" VARCHAR NOT NULL,"locale_id" uuid NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT True,"default_locale" BOOLEAN NOT NULL DEFAULT False,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "deployment_locale_enablement" ADD CONSTRAINT "unique_deployment_locale" UNIQUE("deployment_code","locale_id");
ALTER TABLE "deployment_locale_enablement" ADD CONSTRAINT "deployment_locale_enablement_locale_id_fkey" FOREIGN KEY("locale_id") REFERENCES "locale_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "external_provider"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"provider_kind" VARCHAR NOT NULL,"public_metadata" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"source_version" VARCHAR NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "external_provider" ADD CONSTRAINT "unique_external_provider_code" UNIQUE("code");
ALTER TABLE "external_provider" ADD CONSTRAINT "external_provider_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "external_provider"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "external_provider_code"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"provider_id" uuid NOT NULL,"code_set" VARCHAR NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"source_version" VARCHAR NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "external_provider_code" ADD CONSTRAINT "unique_external_provider_code_value" UNIQUE("provider_id","code_set","code");
ALTER TABLE "external_provider_code" ADD CONSTRAINT "external_provider_code_provider_id_fkey" FOREIGN KEY("provider_id") REFERENCES "external_provider"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "external_provider_code" ADD CONSTRAINT "external_provider_code_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "external_provider_code"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "ddex_standard_version"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"standard_code" VARCHAR NOT NULL,"version_code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"namespace_uri" VARCHAR NULL,"schema_uri" VARCHAR NULL,"source_uri" VARCHAR NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"source_version" VARCHAR NOT NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "ddex_standard_version" ADD CONSTRAINT "unique_ddex_standard_version" UNIQUE("standard_code","version_code");
ALTER TABLE "ddex_standard_version" ADD CONSTRAINT "ddex_standard_version_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "ddex_standard_version"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "ddex_standard_support"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"standard_version_id" uuid NOT NULL,"deployment_code" VARCHAR NOT NULL,"detection_enabled" BOOLEAN NOT NULL DEFAULT False,"validation_enabled" BOOLEAN NOT NULL DEFAULT False,"import_enabled" BOOLEAN NOT NULL DEFAULT False,"export_enabled" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "ddex_standard_support" ADD CONSTRAINT "unique_ddex_standard_support" UNIQUE("standard_version_id","deployment_code");
ALTER TABLE "ddex_standard_support" ADD CONSTRAINT "ddex_standard_support_standard_version_id_fkey" FOREIGN KEY("standard_version_id") REFERENCES "ddex_standard_version"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "ddex_message_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"standard_version_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"source_version" VARCHAR NOT NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"runtime_supported" BOOLEAN NOT NULL DEFAULT False,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "ddex_message_type" ADD CONSTRAINT "unique_ddex_message_type" UNIQUE("standard_version_id","code");
ALTER TABLE "ddex_message_type" ADD CONSTRAINT "ddex_message_type_standard_version_id_fkey" FOREIGN KEY("standard_version_id") REFERENCES "ddex_standard_version"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "ddex_message_type" ADD CONSTRAINT "ddex_message_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "ddex_message_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "ddex_vocabulary"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"standard_version_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"source_uri" VARCHAR NULL,"source_version" VARCHAR NOT NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"active" BOOLEAN NOT NULL DEFAULT True,"sort_order" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "ddex_vocabulary" ADD CONSTRAINT "unique_ddex_vocabulary" UNIQUE("standard_version_id","code");
ALTER TABLE "ddex_vocabulary" ADD CONSTRAINT "ddex_vocabulary_standard_version_id_fkey" FOREIGN KEY("standard_version_id") REFERENCES "ddex_standard_version"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "ddex_vocabulary" ADD CONSTRAINT "ddex_vocabulary_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "ddex_vocabulary"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "ddex_code"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"vocabulary_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"source_version" VARCHAR NOT NULL,"last_synced_at" TIMESTAMP WITH TIME ZONE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "ddex_code" ADD CONSTRAINT "unique_ddex_code" UNIQUE("vocabulary_id","code");
ALTER TABLE "ddex_code" ADD CONSTRAINT "ddex_code_vocabulary_id_fkey" FOREIGN KEY("vocabulary_id") REFERENCES "ddex_vocabulary"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "ddex_code" ADD CONSTRAINT "ddex_code_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "ddex_code"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "ddex_code_applicability"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code_id" uuid NOT NULL,"message_type_id" uuid NOT NULL,"required" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True);
ALTER TABLE "ddex_code_applicability" ADD CONSTRAINT "unique_ddex_code_applicability" UNIQUE("code_id","message_type_id");
ALTER TABLE "ddex_code_applicability" ADD CONSTRAINT "ddex_code_applicability_code_id_fkey" FOREIGN KEY("code_id") REFERENCES "ddex_code"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "ddex_code_applicability" ADD CONSTRAINT "ddex_code_applicability_message_type_id_fkey" FOREIGN KEY("message_type_id") REFERENCES "ddex_message_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "release_type_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"external_code" VARCHAR NULL,"source_version" VARCHAR NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "release_type_reference" ADD CONSTRAINT "unique_release_type_reference_code" UNIQUE("code");
ALTER TABLE "release_type_reference" ADD CONSTRAINT "release_type_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "release_type_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "recording_type_reference"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"external_code" VARCHAR NULL,"source_version" VARCHAR NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "recording_type_reference" ADD CONSTRAINT "unique_recording_type_reference_code" UNIQUE("code");
ALTER TABLE "recording_type_reference" ADD CONSTRAINT "recording_type_reference_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "recording_type_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "recording_session_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"external_code" VARCHAR NULL,"source_version" VARCHAR NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "recording_session_type" ADD CONSTRAINT "unique_recording_session_type_code" UNIQUE("code");
ALTER TABLE "recording_session_type" ADD CONSTRAINT "recording_session_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "recording_session_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "service_category"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"parent_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "service_category" ADD CONSTRAINT "unique_service_category_code" UNIQUE("code");
ALTER TABLE "service_category" ADD CONSTRAINT "unique_service_category_slug" UNIQUE("current_slug");
ALTER TABLE "service_category" ADD CONSTRAINT "service_category_parent_id_fkey" FOREIGN KEY("parent_id") REFERENCES "service_category"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "service_category" ADD CONSTRAINT "service_category_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "service_category"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "service_pricing_model"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "service_pricing_model" ADD CONSTRAINT "unique_service_pricing_model_code" UNIQUE("code");
ALTER TABLE "service_pricing_model" ADD CONSTRAINT "unique_service_pricing_model_slug" UNIQUE("current_slug");
ALTER TABLE "service_pricing_model" ADD CONSTRAINT "service_pricing_model_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "service_pricing_model"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "service_offering"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"category_id" uuid NOT NULL,"legacy_service_catalog_id" INT8 NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"pricing_model_id" uuid NULL,"pricing_model_code" VARCHAR NULL,"default_rate_cents" INT8 NULL,"tax_rate_id" uuid NULL,"tax_rate_code" VARCHAR NULL,"currency_id" uuid NOT NULL,"billing_unit_es" VARCHAR NULL,"billing_unit_en" VARCHAR NULL,"default_duration_minutes" INT8 NULL,"requires_engineer" BOOLEAN NOT NULL DEFAULT False,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "service_offering" ADD CONSTRAINT "unique_service_offering_code" UNIQUE("code");
ALTER TABLE "service_offering" ADD CONSTRAINT "unique_service_offering_slug" UNIQUE("current_slug");
ALTER TABLE "service_offering" ADD CONSTRAINT "unique_service_offering_legacy_id" UNIQUE("legacy_service_catalog_id");
ALTER TABLE "service_offering" ADD CONSTRAINT "service_offering_category_id_fkey" FOREIGN KEY("category_id") REFERENCES "service_category"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "service_offering" ADD CONSTRAINT "service_offering_pricing_model_id_fkey" FOREIGN KEY("pricing_model_id") REFERENCES "service_pricing_model"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "service_offering" ADD CONSTRAINT "service_offering_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "service_offering"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "pipeline_workflow_binding"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"service_offering_id" uuid NOT NULL,"workflow_id" uuid NOT NULL,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "pipeline_workflow_binding" ADD CONSTRAINT "unique_pipeline_workflow_service" UNIQUE("service_offering_id");
ALTER TABLE "pipeline_workflow_binding" ADD CONSTRAINT "pipeline_workflow_binding_service_offering_id_fkey" FOREIGN KEY("service_offering_id") REFERENCES "service_offering"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "service_resource_selection_mode"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "service_resource_selection_mode" ADD CONSTRAINT "unique_service_resource_selection_mode_code" UNIQUE("code");
ALTER TABLE "service_resource_selection_mode" ADD CONSTRAINT "unique_service_resource_selection_mode_slug" UNIQUE("current_slug");
ALTER TABLE "service_resource_selection_mode" ADD CONSTRAINT "service_resource_selection_mode_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "service_resource_selection_mode"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "radio_auto_stop_option"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"duration_minutes" INT8 NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "radio_auto_stop_option" ADD CONSTRAINT "unique_radio_auto_stop_option_code" UNIQUE("code");
ALTER TABLE "radio_auto_stop_option" ADD CONSTRAINT "unique_radio_auto_stop_option_duration" UNIQUE("duration_minutes");
ALTER TABLE "radio_auto_stop_option" ADD CONSTRAINT "unique_radio_auto_stop_option_slug" UNIQUE("current_slug");
ALTER TABLE "radio_auto_stop_option" ADD CONSTRAINT "radio_auto_stop_option_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "radio_auto_stop_option"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "appearance_mode_option"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "appearance_mode_option" ADD CONSTRAINT "unique_appearance_mode_option_code" UNIQUE("code");
ALTER TABLE "appearance_mode_option" ADD CONSTRAINT "unique_appearance_mode_option_slug" UNIQUE("current_slug");
ALTER TABLE "appearance_mode_option" ADD CONSTRAINT "appearance_mode_option_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "appearance_mode_option"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "service_offering_default_resource"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"service_offering_id" uuid NOT NULL,"resource_id" INT8 NOT NULL,"selection_mode_id" uuid NULL,"selection_mode" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "service_offering_default_resource" ADD CONSTRAINT "unique_service_offering_default_resource" UNIQUE("service_offering_id","resource_id");
ALTER TABLE "service_offering_default_resource" ADD CONSTRAINT "service_offering_default_resource_service_offering_id_fkey" FOREIGN KEY("service_offering_id") REFERENCES "service_offering"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "service_offering_default_resource" ADD CONSTRAINT "service_offering_default_resource_selection_mode_id_fkey" FOREIGN KEY("selection_mode_id") REFERENCES "service_resource_selection_mode"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "genre"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"parent_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"external_code" VARCHAR NULL,"external_source" VARCHAR NULL,"source_version" VARCHAR NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "genre" ADD CONSTRAINT "unique_genre_code" UNIQUE("code");
ALTER TABLE "genre" ADD CONSTRAINT "unique_genre_slug" UNIQUE("current_slug");
ALTER TABLE "genre" ADD CONSTRAINT "genre_parent_id_fkey" FOREIGN KEY("parent_id") REFERENCES "genre"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "genre" ADD CONSTRAINT "genre_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "genre"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "instrument"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"parent_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"external_code" VARCHAR NULL,"external_source" VARCHAR NULL,"source_version" VARCHAR NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "instrument" ADD CONSTRAINT "unique_instrument_code" UNIQUE("code");
ALTER TABLE "instrument" ADD CONSTRAINT "unique_instrument_slug" UNIQUE("current_slug");
ALTER TABLE "instrument" ADD CONSTRAINT "instrument_parent_id_fkey" FOREIGN KEY("parent_id") REFERENCES "instrument"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "instrument" ADD CONSTRAINT "instrument_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "instrument"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "event_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "event_type" ADD CONSTRAINT "unique_event_type_code" UNIQUE("code");
ALTER TABLE "event_type" ADD CONSTRAINT "unique_event_type_slug" UNIQUE("current_slug");
ALTER TABLE "event_type" ADD CONSTRAINT "event_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "event_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "booking_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"service_offering_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "booking_type" ADD CONSTRAINT "unique_booking_type_code" UNIQUE("code");
ALTER TABLE "booking_type" ADD CONSTRAINT "unique_booking_type_slug" UNIQUE("current_slug");
ALTER TABLE "booking_type" ADD CONSTRAINT "booking_type_service_offering_id_fkey" FOREIGN KEY("service_offering_id") REFERENCES "service_offering"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "booking_type" ADD CONSTRAINT "booking_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "booking_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "feedback_category"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "feedback_category" ADD CONSTRAINT "unique_feedback_category_code" UNIQUE("code");
ALTER TABLE "feedback_category" ADD CONSTRAINT "unique_feedback_category_slug" UNIQUE("current_slug");
ALTER TABLE "feedback_category" ADD CONSTRAINT "feedback_category_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "feedback_category"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "feedback_severity"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"effective_from" DATE NULL,"effective_until" DATE NULL,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "feedback_severity" ADD CONSTRAINT "unique_feedback_severity_code" UNIQUE("code");
ALTER TABLE "feedback_severity" ADD CONSTRAINT "unique_feedback_severity_slug" UNIQUE("current_slug");
ALTER TABLE "feedback_severity" ADD CONSTRAINT "feedback_severity_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "feedback_severity"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "content_category"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"parent_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "content_category" ADD CONSTRAINT "unique_content_category_code" UNIQUE("code");
ALTER TABLE "content_category" ADD CONSTRAINT "unique_content_category_slug" UNIQUE("current_slug");
ALTER TABLE "content_category" ADD CONSTRAINT "content_category_parent_id_fkey" FOREIGN KEY("parent_id") REFERENCES "content_category"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "content_category" ADD CONSTRAINT "content_category_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "content_category"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "tag"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "tag" ADD CONSTRAINT "unique_tag_code" UNIQUE("code");
ALTER TABLE "tag" ADD CONSTRAINT "unique_tag_slug" UNIQUE("current_slug");
ALTER TABLE "tag" ADD CONSTRAINT "tag_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "tag"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "reaction_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"emoji" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "reaction_type" ADD CONSTRAINT "unique_reaction_type_code" UNIQUE("code");
ALTER TABLE "reaction_type" ADD CONSTRAINT "unique_reaction_type_slug" UNIQUE("current_slug");
ALTER TABLE "reaction_type" ADD CONSTRAINT "reaction_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "reaction_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "content_reaction_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"emoji" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "content_reaction_type" ADD CONSTRAINT "unique_content_reaction_type_code" UNIQUE("code");
ALTER TABLE "content_reaction_type" ADD CONSTRAINT "unique_content_reaction_type_slug" UNIQUE("current_slug");
ALTER TABLE "content_reaction_type" ADD CONSTRAINT "content_reaction_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "content_reaction_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "creator_badge_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "creator_badge_type" ADD CONSTRAINT "unique_creator_badge_type_code" UNIQUE("code");
ALTER TABLE "creator_badge_type" ADD CONSTRAINT "unique_creator_badge_type_slug" UNIQUE("current_slug");
ALTER TABLE "creator_badge_type" ADD CONSTRAINT "creator_badge_type_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "creator_badge_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "content_type"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"entity_kind" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"schema_json" VARCHAR NOT NULL,"schema_version" INT8 NOT NULL,"public_route_pattern" VARCHAR NULL,"admin_route_pattern" VARCHAR NULL,"public_read" BOOLEAN NOT NULL DEFAULT False,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "content_type" ADD CONSTRAINT "unique_content_type_code" UNIQUE("code");
CREATe TABLE "authored_content"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"content_type_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NOT NULL,"public_route" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"published_revision" INT8 NOT NULL DEFAULT 1,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "authored_content" ADD CONSTRAINT "unique_authored_content_code" UNIQUE("code");
ALTER TABLE "authored_content" ADD CONSTRAINT "unique_authored_content_slug" UNIQUE("current_slug");
ALTER TABLE "authored_content" ADD CONSTRAINT "authored_content_content_type_id_fkey" FOREIGN KEY("content_type_id") REFERENCES "content_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "record_release"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"release_type_id" uuid NOT NULL,"title_es" VARCHAR NOT NULL,"title_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"release_date" DATE NULL,"current_slug" VARCHAR NULL,"cover_asset_id" uuid NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "record_release" ADD CONSTRAINT "unique_record_release_code" UNIQUE("code");
ALTER TABLE "record_release" ADD CONSTRAINT "unique_record_release_slug" UNIQUE("current_slug");
ALTER TABLE "record_release" ADD CONSTRAINT "record_release_release_type_id_fkey" FOREIGN KEY("release_type_id") REFERENCES "release_type_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "record_release" ADD CONSTRAINT "record_release_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "record_release"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "recording"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"recording_type_id" uuid NOT NULL,"title_es" VARCHAR NOT NULL,"title_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"duration_ms" INT8 NULL,"language_id" uuid NULL,"explicit_content" BOOLEAN NOT NULL DEFAULT False,"current_slug" VARCHAR NULL,"image_asset_id" uuid NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "recording" ADD CONSTRAINT "unique_recording_code" UNIQUE("code");
ALTER TABLE "recording" ADD CONSTRAINT "unique_recording_slug" UNIQUE("current_slug");
ALTER TABLE "recording" ADD CONSTRAINT "recording_recording_type_id_fkey" FOREIGN KEY("recording_type_id") REFERENCES "recording_type_reference"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "recording" ADD CONSTRAINT "recording_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "recording"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "recording_session"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"session_type_id" uuid NOT NULL,"title_es" VARCHAR NOT NULL,"title_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"recorded_at" TIMESTAMP WITH TIME ZONE NULL,"current_slug" VARCHAR NULL,"venue_id" uuid NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"published_revision" INT8 NOT NULL DEFAULT 0,"deprecated_at" TIMESTAMP WITH TIME ZONE NULL,"replacement_id" uuid NULL,"usage_count" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "recording_session" ADD CONSTRAINT "unique_recording_session_code" UNIQUE("code");
ALTER TABLE "recording_session" ADD CONSTRAINT "unique_recording_session_slug" UNIQUE("current_slug");
ALTER TABLE "recording_session" ADD CONSTRAINT "recording_session_session_type_id_fkey" FOREIGN KEY("session_type_id") REFERENCES "recording_session_type"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "recording_session" ADD CONSTRAINT "recording_session_replacement_id_fkey" FOREIGN KEY("replacement_id") REFERENCES "recording_session"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "release_recording"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"release_id" uuid NOT NULL,"recording_id" uuid NOT NULL,"disc_number" INT8 NOT NULL DEFAULT 1,"sort_order" INT8 NOT NULL,"primary_recording" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "release_recording" ADD CONSTRAINT "unique_release_recording" UNIQUE("release_id","recording_id");
ALTER TABLE "release_recording" ADD CONSTRAINT "unique_release_recording_order" UNIQUE("release_id","disc_number","sort_order");
ALTER TABLE "release_recording" ADD CONSTRAINT "release_recording_release_id_fkey" FOREIGN KEY("release_id") REFERENCES "record_release"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "release_recording" ADD CONSTRAINT "release_recording_recording_id_fkey" FOREIGN KEY("recording_id") REFERENCES "recording"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "session_recording"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"session_id" uuid NOT NULL,"recording_id" uuid NOT NULL,"sort_order" INT8 NOT NULL,"primary_recording" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "session_recording" ADD CONSTRAINT "unique_session_recording" UNIQUE("session_id","recording_id");
ALTER TABLE "session_recording" ADD CONSTRAINT "unique_session_recording_order" UNIQUE("session_id","sort_order");
ALTER TABLE "session_recording" ADD CONSTRAINT "session_recording_session_id_fkey" FOREIGN KEY("session_id") REFERENCES "recording_session"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "session_recording" ADD CONSTRAINT "session_recording_recording_id_fkey" FOREIGN KEY("recording_id") REFERENCES "recording"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "editorial_collection"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"collection_type" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"current_slug" VARCHAR NULL,"public_route" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"updated_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"published_revision" INT8 NOT NULL DEFAULT 0,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "editorial_collection" ADD CONSTRAINT "unique_editorial_collection_code" UNIQUE("code");
ALTER TABLE "editorial_collection" ADD CONSTRAINT "unique_editorial_collection_slug" UNIQUE("current_slug");
CREATe TABLE "collection_release"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"collection_id" uuid NOT NULL,"release_id" uuid NOT NULL,"sort_order" INT8 NOT NULL,"featured" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "collection_release" ADD CONSTRAINT "unique_collection_release" UNIQUE("collection_id","release_id");
ALTER TABLE "collection_release" ADD CONSTRAINT "unique_collection_release_order" UNIQUE("collection_id","sort_order");
ALTER TABLE "collection_release" ADD CONSTRAINT "collection_release_collection_id_fkey" FOREIGN KEY("collection_id") REFERENCES "editorial_collection"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "collection_release" ADD CONSTRAINT "collection_release_release_id_fkey" FOREIGN KEY("release_id") REFERENCES "record_release"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "collection_recording"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"collection_id" uuid NOT NULL,"recording_id" uuid NOT NULL,"sort_order" INT8 NOT NULL,"featured" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "collection_recording" ADD CONSTRAINT "unique_collection_recording" UNIQUE("collection_id","recording_id");
ALTER TABLE "collection_recording" ADD CONSTRAINT "unique_collection_recording_order" UNIQUE("collection_id","sort_order");
ALTER TABLE "collection_recording" ADD CONSTRAINT "collection_recording_collection_id_fkey" FOREIGN KEY("collection_id") REFERENCES "editorial_collection"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "collection_recording" ADD CONSTRAINT "collection_recording_recording_id_fkey" FOREIGN KEY("recording_id") REFERENCES "recording"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "collection_session"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"collection_id" uuid NOT NULL,"session_id" uuid NOT NULL,"sort_order" INT8 NOT NULL,"featured" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "collection_session" ADD CONSTRAINT "unique_collection_session" UNIQUE("collection_id","session_id");
ALTER TABLE "collection_session" ADD CONSTRAINT "unique_collection_session_order" UNIQUE("collection_id","sort_order");
ALTER TABLE "collection_session" ADD CONSTRAINT "collection_session_collection_id_fkey" FOREIGN KEY("collection_id") REFERENCES "editorial_collection"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "collection_session" ADD CONSTRAINT "collection_session_session_id_fkey" FOREIGN KEY("session_id") REFERENCES "recording_session"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "record_contributor"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"catalog_id" uuid NOT NULL,"code" VARCHAR NOT NULL,"contributor_kind" VARCHAR NOT NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "record_contributor" ADD CONSTRAINT "unique_record_contributor_code" UNIQUE("code");
CREATe TABLE "release_contributor"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"release_id" uuid NOT NULL,"contributor_id" uuid NOT NULL,"credit_role" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_credit" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "release_contributor" ADD CONSTRAINT "unique_release_contributor" UNIQUE("release_id","contributor_id","credit_role");
ALTER TABLE "release_contributor" ADD CONSTRAINT "unique_release_contributor_order" UNIQUE("release_id","credit_role","sort_order");
ALTER TABLE "release_contributor" ADD CONSTRAINT "release_contributor_release_id_fkey" FOREIGN KEY("release_id") REFERENCES "record_release"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "release_contributor" ADD CONSTRAINT "release_contributor_contributor_id_fkey" FOREIGN KEY("contributor_id") REFERENCES "record_contributor"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "recording_contributor"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"recording_id" uuid NOT NULL,"contributor_id" uuid NOT NULL,"credit_role" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_credit" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "recording_contributor" ADD CONSTRAINT "unique_recording_contributor" UNIQUE("recording_id","contributor_id","credit_role");
ALTER TABLE "recording_contributor" ADD CONSTRAINT "unique_recording_contributor_order" UNIQUE("recording_id","credit_role","sort_order");
ALTER TABLE "recording_contributor" ADD CONSTRAINT "recording_contributor_recording_id_fkey" FOREIGN KEY("recording_id") REFERENCES "recording"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "recording_contributor" ADD CONSTRAINT "recording_contributor_contributor_id_fkey" FOREIGN KEY("contributor_id") REFERENCES "record_contributor"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "session_contributor"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"session_id" uuid NOT NULL,"contributor_id" uuid NOT NULL,"credit_role" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_credit" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "session_contributor" ADD CONSTRAINT "unique_session_contributor" UNIQUE("session_id","contributor_id","credit_role");
ALTER TABLE "session_contributor" ADD CONSTRAINT "unique_session_contributor_order" UNIQUE("session_id","credit_role","sort_order");
ALTER TABLE "session_contributor" ADD CONSTRAINT "session_contributor_session_id_fkey" FOREIGN KEY("session_id") REFERENCES "recording_session"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "session_contributor" ADD CONSTRAINT "session_contributor_contributor_id_fkey" FOREIGN KEY("contributor_id") REFERENCES "record_contributor"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "record_external_resource"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"provider_id" uuid NOT NULL,"external_code" VARCHAR NOT NULL,"resource_kind" VARCHAR NOT NULL,"canonical_url" VARCHAR NOT NULL,"label_es" VARCHAR NULL,"label_en" VARCHAR NULL,"duration_ms" INT8 NULL,"thumbnail_url" VARCHAR NULL,"active" BOOLEAN NOT NULL DEFAULT True,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "record_external_resource" ADD CONSTRAINT "unique_record_external_resource" UNIQUE("provider_id","resource_kind","external_code");
CREATe TABLE "release_external_resource"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"release_id" uuid NOT NULL,"resource_id" uuid NOT NULL,"relation_kind" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_resource" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "release_external_resource" ADD CONSTRAINT "unique_release_external_resource" UNIQUE("release_id","resource_id","relation_kind");
ALTER TABLE "release_external_resource" ADD CONSTRAINT "unique_release_external_resource_order" UNIQUE("release_id","relation_kind","sort_order");
ALTER TABLE "release_external_resource" ADD CONSTRAINT "release_external_resource_release_id_fkey" FOREIGN KEY("release_id") REFERENCES "record_release"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "release_external_resource" ADD CONSTRAINT "release_external_resource_resource_id_fkey" FOREIGN KEY("resource_id") REFERENCES "record_external_resource"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "recording_external_resource"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"recording_id" uuid NOT NULL,"resource_id" uuid NOT NULL,"relation_kind" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_resource" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "recording_external_resource" ADD CONSTRAINT "unique_recording_external_resource" UNIQUE("recording_id","resource_id","relation_kind");
ALTER TABLE "recording_external_resource" ADD CONSTRAINT "unique_recording_external_resource_order" UNIQUE("recording_id","relation_kind","sort_order");
ALTER TABLE "recording_external_resource" ADD CONSTRAINT "recording_external_resource_recording_id_fkey" FOREIGN KEY("recording_id") REFERENCES "recording"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "recording_external_resource" ADD CONSTRAINT "recording_external_resource_resource_id_fkey" FOREIGN KEY("resource_id") REFERENCES "record_external_resource"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "session_external_resource"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"session_id" uuid NOT NULL,"resource_id" uuid NOT NULL,"relation_kind" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_resource" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "session_external_resource" ADD CONSTRAINT "unique_session_external_resource" UNIQUE("session_id","resource_id","relation_kind");
ALTER TABLE "session_external_resource" ADD CONSTRAINT "unique_session_external_resource_order" UNIQUE("session_id","relation_kind","sort_order");
ALTER TABLE "session_external_resource" ADD CONSTRAINT "session_external_resource_session_id_fkey" FOREIGN KEY("session_id") REFERENCES "recording_session"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "session_external_resource" ADD CONSTRAINT "session_external_resource_resource_id_fkey" FOREIGN KEY("resource_id") REFERENCES "record_external_resource"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "collection_external_resource"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"collection_id" uuid NOT NULL,"resource_id" uuid NOT NULL,"relation_kind" VARCHAR NOT NULL,"sort_order" INT8 NOT NULL DEFAULT 0,"primary_resource" BOOLEAN NOT NULL DEFAULT False);
ALTER TABLE "collection_external_resource" ADD CONSTRAINT "unique_collection_external_resource" UNIQUE("collection_id","resource_id","relation_kind");
ALTER TABLE "collection_external_resource" ADD CONSTRAINT "unique_collection_external_resource_order" UNIQUE("collection_id","relation_kind","sort_order");
ALTER TABLE "collection_external_resource" ADD CONSTRAINT "collection_external_resource_collection_id_fkey" FOREIGN KEY("collection_id") REFERENCES "editorial_collection"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
ALTER TABLE "collection_external_resource" ADD CONSTRAINT "collection_external_resource_resource_id_fkey" FOREIGN KEY("resource_id") REFERENCES "record_external_resource"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;
CREATe TABLE "navigation_item"("id" uuid PRIMARY KEY UNIQUE DEFAULT gen_random_uuid(),"code" VARCHAR NOT NULL,"parent_id" uuid NULL,"name_es" VARCHAR NOT NULL,"name_en" VARCHAR NOT NULL,"description_es" VARCHAR NULL,"description_en" VARCHAR NULL,"route_path" VARCHAR NOT NULL,"icon_code" VARCHAR NULL,"feature_code" VARCHAR NULL,"required_permission_id" uuid NULL,"platform_scope" VARCHAR NOT NULL,"public_visible" BOOLEAN NOT NULL DEFAULT False,"sort_order" INT8 NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT True,"workflow_state_id" uuid NOT NULL,"created_by" INT8 NULL,"approved_by" INT8 NULL,"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,"version" INT8 NOT NULL DEFAULT 1);
ALTER TABLE "navigation_item" ADD CONSTRAINT "unique_navigation_item_code" UNIQUE("code");
ALTER TABLE "navigation_item" ADD CONSTRAINT "unique_navigation_item_route" UNIQUE("platform_scope","route_path");
ALTER TABLE "navigation_item" ADD CONSTRAINT "navigation_item_parent_id_fkey" FOREIGN KEY("parent_id") REFERENCES "navigation_item"("id") ON DELETE RESTRICT  ON UPDATE RESTRICT;

\else
DO $catalog_canonical_schema_gate$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM (VALUES
      ('workflow_definition'::text),
      ('workflow_state'::text),
      ('workflow_transition'::text),
      ('workflow_default_state'::text),
      ('workflow_state_capability'::text),
      ('catalog_definition'::text),
      ('catalog_revision'::text),
      ('catalog_audit_event'::text),
      ('catalog_import_job'::text),
      ('catalog_import_review_entry'::text),
      ('catalog_backfill_run'::text),
      ('catalog_migration_mapping'::text),
      ('workflow_migration_mapping'::text),
      ('catalog_slug_alias'::text),
      ('catalog_search_alias'::text),
      ('catalog_scoped_default'::text),
      ('catalog_dependency_rule'::text),
      ('catalog_merge_operation'::text),
      ('catalog_usage_daily'::text),
      ('security_module'::text),
      ('security_action'::text),
      ('security_permission'::text),
      ('security_role'::text),
      ('security_role_assignment_policy'::text),
      ('security_grant_revision'::text),
      ('role_permission'::text),
      ('party_security_role'::text),
      ('security_audit_event'::text),
      ('country_reference'::text),
      ('subdivision_reference'::text),
      ('city_reference'::text),
      ('currency_reference'::text),
      ('tax_rate_reference'::text),
      ('language_reference'::text),
      ('locale_reference'::text),
      ('deployment_currency_enablement'::text),
      ('deployment_locale_enablement'::text),
      ('external_provider'::text),
      ('external_provider_code'::text),
      ('ddex_standard_version'::text),
      ('ddex_standard_support'::text),
      ('ddex_message_type'::text),
      ('ddex_vocabulary'::text),
      ('ddex_code'::text),
      ('ddex_code_applicability'::text),
      ('release_type_reference'::text),
      ('recording_type_reference'::text),
      ('recording_session_type'::text),
      ('service_category'::text),
      ('service_pricing_model'::text),
      ('service_offering'::text),
      ('pipeline_workflow_binding'::text),
      ('service_resource_selection_mode'::text),
      ('radio_auto_stop_option'::text),
      ('appearance_mode_option'::text),
      ('service_offering_default_resource'::text),
      ('genre'::text),
      ('instrument'::text),
      ('event_type'::text),
      ('booking_type'::text),
      ('feedback_category'::text),
      ('feedback_severity'::text),
      ('content_category'::text),
      ('tag'::text),
      ('reaction_type'::text),
      ('content_reaction_type'::text),
      ('creator_badge_type'::text),
      ('content_type'::text),
      ('authored_content'::text),
      ('record_release'::text),
      ('recording'::text),
      ('recording_session'::text),
      ('release_recording'::text),
      ('session_recording'::text),
      ('editorial_collection'::text),
      ('collection_release'::text),
      ('collection_recording'::text),
      ('collection_session'::text),
      ('record_contributor'::text),
      ('release_contributor'::text),
      ('recording_contributor'::text),
      ('session_contributor'::text),
      ('record_external_resource'::text),
      ('release_external_resource'::text),
      ('recording_external_resource'::text),
      ('session_external_resource'::text),
      ('collection_external_resource'::text),
      ('navigation_item'::text)
    ) AS expected(table_name)
    WHERE to_regclass('public.' || expected.table_name) IS NULL
  ) THEN
    RAISE EXCEPTION 'canonical catalog schema is partial; refusing idempotent skip' USING ERRCODE='55000';
  END IF;
END
$catalog_canonical_schema_gate$;
\endif

COMMIT;
